### ISSUE TITLE
Feature request: Support 'shellslash' on Windows

### ISSUE THREAD

**Issue by Hans-Guenter** [lambdalisue/fern.vim#102]
When the shellslah option is set on Windows Fern does not work and an error message like
`fern: {base} ("C:/TEMP") must be an absolute path`
is returned.

**Comment by lambdalisue** [comment]
Fern currently does not support `'shellslash'` but could you try if the following (partially) fix the issue?

```vim
let g:fern#internal#filepath#is_windows = 0
```

**Comment by Hans-Guenter** [comment]
Unfortunately introducing the variable
g:fern#internal#filepath#is_windows = 0
**didn't** help. The behaviour of the Fern command is the same.

**Comment by lambdalisue** [comment]
Then explicit 'shellslash' support is required.

Unfortunately, I don't have enough motivation to support it by myself while people usually stop using `'shellslash'` at the end while it breaks (numerous) plugins behavior AFAIK.

But I'm OK to review PR for `'shellslash'` if someone wants. So I'll leave this issue as a feature request.

**Comment by lambdalisue** [comment]
It's possible to overwrite `Fern` command itself like below **but it's not enough while a lot of actions would not be fixed by it.**

```vim
" Overwrite 'Fern' command to support shellslash
command! -bar -nargs=*
      \ -complete=customlist,fern#internal#command#fern#complete
      \ Fern
      \ call s:support_shellslash({ -> fern#internal#command#fern#command(<q-mods>, [<f-args>]) })
function! s:support_shellslash(func) abort
  let restores = []
  if exists('+shellslash')
    call add(restores, &shellslash ? { -> execute('set shellslash') } : { -> 0 })
    set shellslash&
  endif
  if exists('+completeslash')
    let completeslash_saved = &completeslash
    call add(restores, { -> execute('set completeslash' . completeslash_saved) })
    set completeslash&
  endif
  try
    return a:func()
  finally
    for l:Restore in restores
      call Restore()
    endfor
  endtry
endfunction
```

**Comment by lambdalisue** [comment]
TODO:

Write that fern does not support `shellslash` and why I'm not planning to support it in help.
