### ISSUE TITLE
Old entry does not clear when renaming expanded directory.

### ISSUE THREAD

**Issue by hrsh7th** [lambdalisue/fern.vim#103]
Thank you for provided the very high-quality drawer plugin.

I met the problem when renaming expanded directory.
The problem is that fern.vim does not clear old directory when renaming an expanded directory.

The repro steps are following.

1. Open fern buffer by `Fern % -drawer`
2. Create directory (e.g. `test`)
3. Expand tree
4. Rename the directory `test` to `testaiueo`.

In this case, the fern.vim does not clear `test` directory.

**Comment by lambdalisue** [comment]
Reproduced. Thanks
