### ISSUE TITLE
Automatically remove statusline and line number.

### ISSUE THREAD

**Issue by ADAM5048** [lambdalisue/fern.vim#105]

**Comment by lambdalisue** [comment]
I'm not esp

**Comment by kkk669** [comment]
I encountered the same problem. Can I remove line number in a project drawer?

![image](https://user-images.githubusercontent.com/601636/94369944-a9429f00-0127-11eb-956b-34b79f3afa74.png)

**Comment by lambdalisue** [comment]
Execute 'setlocal nonumber' on fern buffer. See Wiki Tips to find how to execute code on  fern buf.

**Comment by kkk669** [comment]
I understand. Thank you.
