### ISSUE TITLE
Restore fern panel from session

### ISSUE THREAD

**Issue by dcampos** [lambdalisue/fern.vim#116]
The docs mention it should be possible to restore Fern panels from a saved session, but I'm having trouble trying to achieve this. Every time I save a session containing a fern window, it's just an empty window when I try to restore the session later.

Should I set some option or there is any trick to get it to work?

**Comment by lambdalisue** [comment]
Honestly, I don't use the session thus I didn't notice that. It's definietly a bug so I'll try to fix.

**Comment by lambdalisue** [comment]
Could you try if https://github.com/lambdalisue/fern.vim/pull/117 fix the issue?

**Comment by dcampos** [comment]
It works fine for me after the changes. Thanks for the quick response!
