### ISSUE TITLE
going up a directory

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/fern.vim#119]
In NerdTree there is a way to go up the directory. Is there an equivalent in fern.vim either by having a flag to add or by some keybindings?

![image](https://user-images.githubusercontent.com/287744/85915692-7c1be300-b7fe-11ea-87b2-cc3a4b5d61bc.png)

**Comment by lambdalisue** [comment]
The `leave` action which is mapped to `<Backspace>` in default.

**Comment by prabirshrestha** [comment]
Works thanks.

**Comment by ubaldot** [comment]
I just switched to Fern, congrats! However, it would be handy to have that option like in NERDTree (and other standard non-vim file explorers) I must say.... But perhaps as it is 2024 is implemented by now?

**Comment by lambdalisue** [comment]
I see. Do you have any reason why that is required?

**Comment by lambdalisue** [comment]
Got it. I add a new issue to implement that feature. @ubaldot

**Comment by lambdalisue** [comment]
@ubaldot Could you try https://github.com/lambdalisue/fern.vim/pull/497? As I explained in #496, adding `.. up a dir` line was a bit difficult so I add alternative feature.
