### ISSUE TITLE
CursorHold is blocked while Fern buffer is shwon

### ISSUE THREAD

**Issue by amerov** [lambdalisue/fern.vim#120]
how to reproduce:
`:autocmd CursorHold * echo 'cursor hold'`
it works but stopped after open Fern

version: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow
 -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32
 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"
```
UPD: Fern should be open with `-drawer` option

**Comment by lambdalisue** [comment]
Could not be reproduced with the following minimal vimrc. 
Please find a **minimal** vimrc to reproduce.

```vim
" vim -u ~/.vim/vimrc.min
if has('vim_starting')
  set nocompatible
endif

nnoremap ; :
nnoremap : ;

set packpath=
set runtimepath+=~/.config/nvim/pack/minpac/start/fern.vim

filetype plugin indent on
syntax on

autocmd CursorHold * echo 'cursor hold'
```

**Comment by amerov** [comment]
How to reproduce: Open Fern with `-drawer` option

minimal vimrc:

```viml
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lambdalisue/fern.vim'
call plug#end()
filetype indent on
filetype plugin on
set nobackup
set nowritebackup
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set hidden
set magic
set number
set autoindent
set smartindent
set smarttab
set ruler
set modeline
set showcmd
set showmode
set showmatch
set autoread
set autowrite
set smartcase
set ignorecase
set wildmenu
set wildmode=longest:full,full
set laststatus=2
set lazyredraw
set updatetime=200
set incsearch
set inccommand=split
set title
set titlestring=vim
set list
set visualbell
set wildoptions=pum
set splitbelow
set splitright

if has("patch-8.1.1564")
  set signcolumn=number
else
  set signcolumn=yes
endif

if has('mouse')
  set mouse=a
endif

if has("persistent_undo")
    set undodir=~/.nvim/undo
    set undofile
endif

let mapleader=" "

if has("termguicolors")
  set termguicolors
endif

autocmd CursorHold * echo 'C Hold'
```

**Comment by lambdalisue** [comment]
Please make it **minimal**.

**Comment by amerov** [comment]
> Please make it **minimal**.
+

**Comment by amerov** [comment]
> Please make it **minimal**.

edited

**Comment by lambdalisue** [comment]
Reproduced. It does not happen on Vim thus probably https://github.com/neovim/neovim/issues/12587 cause this issue.

**Comment by antoinemadec** [comment]
@amerov , @lambdalisue , could you please try to use this plugin and tell me if it fixed it?
https://github.com/antoinemadec/FixCursorHold.nvim

**Comment by amerov** [comment]
> @amerov , @lambdalisue , could you please try to use this plugin and tell me if it fixed it?
> https://github.com/antoinemadec/FixCursorHold.nvim

It fixed CursorHold blocking, but with this plugin it fire twice

**Comment by antoinemadec** [comment]
> It fixed CursorHold blocking, but with this plugin it fire twice

@amerov , I just fixed it.
Please update **FixCursorHold.nvim** and let me know :smiley:

**Comment by amerov** [comment]
> > It fixed CursorHold blocking, but with this plugin it fire twice
> 
> @amerov , I just fixed it.
> Please update **FixCursorHold.nvim** and let me know

It works.

**Comment by bluz71** [comment]
This Neovim bug is annoying, it breaks [vim-gitgutter](https://github.com/airblade/vim-gitgutter) when a file is opened by fern and fern remains open. The *gitgutter* signs will not be emitted. Closing fern will result in the signs be displayed.

The interim fix is to include:

```viml
if has("nvim")
  Plug 'antoinemadec/FixCursorHold.nvim'
endif
```

Hopefully Neovim will be fixed eventually.

**Comment by lambdalisue** [comment]
Neovim took too long to fix that. Probably we should note users about this in README

**Comment by lambdalisue** [comment]
Done https://github.com/lambdalisue/fern.vim/commit/8433792f4e8c093cf1b03426b01780d1e8fe6926

**Comment by jonescamilla** [comment]
> Neovim took too long to fix that. Probably we should note users about this in README

Does this mean that this additional plugin is no longer required? I'm inferring from your statement, it took neovim a long time but the issue has been resolved.

**Comment by bluz71** [comment]
The Neovim issue is not fixed. It is recommended to use the plugin to workaround the cursor hold issue.

**Comment by bluz71** [comment]
Note for those concerned, Neovim fixed [CursorHold issue 12587](https://github.com/neovim/neovim/issues/12587) in [this PR](https://github.com/neovim/neovim/pull/20198).

Upcoming Neovim 0.8 (to be released very soon, probably before Oct 2022) will incorporate the fix (which already is in nightly).

Folks who use Neovim nightly or 0.8 can now remove the [`antoinemadec/FixCursorHold.nvim` plugin](https://github.com/antoinemadec/FixCursorHold.nvim).
