### ISSUE TITLE
Add a way to customize statusline appearance on "select" action

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern.vim#127]
Hello,

I have been transitioning from vimfiler to fern.vim. It is very nice that fern.vim contains a window selector for `open:select` just like vimfiler. Works very well, solves the oil and vinegar problem. Thank you!

My query is about the style, best explained by these two screenshots, first vimfiler plugin:

![vimfiler_choose](https://user-images.githubusercontent.com/11382509/89016776-a4968000-d35c-11ea-8680-0e62eb4f5b9e.png)

Second, fern.vim plugin:

![fern_choose](https://user-images.githubusercontent.com/11382509/89016792-aa8c6100-d35c-11ea-8de9-ae734adff687.png)

The query is about the `statusline`, notice in fern.vim that the bar mostly disappears  replaced by the normal editing background color. On a large screen with many splits the disappearance of the normal `statusline` dividers makes it hard to figure out how the screen is divided. The `statusline` visualises the splits better.

I like the style of `a` and `b` choices. I just wish the Vim theme `statusline` color remained as well. Is that possible? The combination of `a` / `b` with normal `statusline` would look excellent with my theme.

Thanks.

**Comment by lambdalisue** [comment]
Got it. I'll consider adding a way to customize the appearance.

**Comment by bluz71** [comment]
Note, in the screenshots, I like the blue selection indicators that fern displays, they look even nicer than vimfiler. Just the statusline background is my issue, nothing more.

**Comment by lambdalisue** [comment]
Please try #131.

**Comment by bluz71** [comment]
Thanks, I will send feedback within the next day.

**Comment by bluz71** [comment]
@lambdalisue,

Yes, #131 is **100% perfect**. I love it. 

And you also now allow separate colours for branch symbols and branch text which is also fantastic. Many thanks for that as well.

Screenshot with the latest update:

![New_Style](https://user-images.githubusercontent.com/11382509/89146850-5077df80-d598-11ea-914d-13c988a4fce2.png)

Please merge.

Many thanks for this awesome (Neo)vim file manager. I enjoy this plugin so much I created [this Reddit post about fern.vim](https://www.reddit.com/r/vim/comments/i1p3s9/fernvim_a_modern_asynchronous_file_manager_for_vim/) which linked back to [my Vim plugins I like Blog post](https://bluz71.github.io/2017/05/21/vim-plugins-i-like.html#fernvim).

Keep up the great work.

**Comment by lambdalisue** [comment]
> Many thanks for this awesome (Neo)vim file manager. I enjoy this plugin so much I created this Reddit post about fern.vim which linked back to my Vim plugins I like Blog post.

Thanks. That kind of things encourage me a lot 👍 

Additionally, I'm planning to create a screenshot page on Wiki to share users custom design. Can I use yours at then?

**Comment by bluz71** [comment]
> Thanks. That kind of things encourage me a lot.

NERDTree has been driving me crazy with it's poor performance for years. I got so feed up six months ago I dumped it for vimfiler. However, vimfiler is now deprecated.

So when I came across fern.vim recently it was a breath of fresh air, especially with regard to performance. fern.vim is **SO MUCH** faster the NERDTree when dealing with large directories, it is not even close.

So thanks to you.

> Additionally, I'm planning to create a screenshot page on Wiki to share users custom design. Can I use yours at then?

Please use this image without the Alacritty heading and window manager buttons:

![Screenshot](https://user-images.githubusercontent.com/11382509/89149076-e57dd700-d59e-11ea-9895-999900c1ce9a.png)

Cheers.
