### ISSUE TITLE
How to refresh fern explorer?

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern.vim#128]
Hello,

I have been experimenting with fern.vim and I can't seem to figure out how to trigger a refresh of fern explorer **if** files are added or removed in the current directory from outside Vim.

I thought `fern-action-reload` may do it, but that doesn't appear to find new or deleted files.
Same for `fern-action-redraw`.

Maybe I have missed something obvious? Which action do I use?

If not, can I request a new action that does a full rescan of the current working directory.

Many thanks.

**Comment by lambdalisue** [comment]
Reload is correct. Just execute that action on a parent directory.

**Comment by lambdalisue** [comment]
Or use 3rd party plugins

https://github.com/lambdalisue/fern.vim/wiki#plugins
![fern vim Wiki 2020-07-31 18-27-44](https://user-images.githubusercontent.com/546312/89021478-8e3bf480-d35b-11ea-9e42-5eb92af07c54.png)

**Comment by bluz71** [comment]
Ok,

I was doing reload at project root and could not figure out why nothing was changing.

Now I understand.

Thanks.
