### ISSUE TITLE
Rename corresponding buffer "filename" after rename/move action

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#129]
With NERDTree there was the `let g:NERDTreeAutoDeleteBuffer=1` option which when set allows you to rename a file and then have the newly renamed file replace the old file in the buffer and retain things like syntax highlighting, jumps, etc.

I didn't see such an option with fern, but IMO this is a deal breaker to use fern as an NT replacement because to rename a file with fern requires:

1. Initiating the rename command
2. Typing in the new name of the file
3. Closing the old / originally named file in the buffer
4. Opening the newly renamed file

But the same thing with NT only requires the first 2 steps.

Any chance you can add this behavior by default, or expose an option to enable it?

**Comment by lambdalisue** [comment]
Intresting. Well, I think I can implement such features. I'll let you know when I implement it here.

**Comment by lambdalisue** [comment]
It's more difficult than I thought. We need to solve https://github.com/lambdalisue/fern.vim/issues/111 first otherwise new names are not determined stably.

**Comment by nickjj** [comment]
Thanks for keeping us in the loop. I wish I knew more about Vim Script to help, but in #111 it mentions multiple files. Does the problem also occur with single file renames? Perhaps a temporary solution could arise that solves the single file use case and then once that's ironed out and thought out in detail, you may stumble into what's causing #111?

**Comment by lambdalisue** [comment]
I'm sorry but I don't think it's a good idea to add a temporal solution on this while the suggestion is for enhancement rather than bug fix.

**Comment by bluz71** [comment]
99% of renames would be single file.

If single file renames avoid the complication of #111, then I too would favour a solution like the following

```
if renaming a single file
  do file rename
  do buffer replacement if necessary
else multiple-files rename
  do file renames
end
```

I am not too fussed either way, I generally do my renames, often `g mv`, outside Neovim.

My 2cents.

**Comment by lambdalisue** [comment]
I noticed that the feature can be implemented independently from #111 
WIP but you can try https://github.com/lambdalisue/fern.vim/pull/135

**Comment by bluz71** [comment]
> WIP but you can try #135

My quick single-file move was a success, the buffer was also updated.

@nickjj uses move/rename a lot more than I do, so his response will be more authoritative.

**Comment by nickjj** [comment]
I'm with @bluz71 here. 99% of the time I'm renaming 1 file at a time with Vim. But I will also say that this is due to NT. However with that said, it's super rare for me to want to rename multiple files. Usually when that happens I go off on a side quest to either do it manually outside of Vim, or come up with some crazy Shell script or Vim macro to handle a 1 off unique case.

I really like how you've added a way to spawn a Vim buffer to do the rename, so I may explore using that more once #111 is addressed.

I tested #135 and it seems good when you're moving the outer most file. For example, if you select a file in `foo/bar/hello.txt` and move `hello.txt` to `hello2.txt` it works, but it has an issue that I saw after a few minutes of testing:

- If you select and move `foo/bar/hello.txt` to `foo/something/hello.txt` then `something` gets created as a new directory and as a separate sub-issue if you happened to also include changing the `hello.txt` it creates a new file with that name too instead of renaming it

I didn't do an exhaustive test but that's what I found so far.

As for moving work flows. One work flow I did all the time with NT was having a long file name in `_drafts/long-file-name.md` and then in NT I toggled NT to open and select that file, and then I moved the file but instead of changing its name I moved it to `_posts/long-file-name.md`. I think this type of work flow of wanting to select a file and move it to a different directory is a very common thing to do.

**Comment by lambdalisue** [comment]
I didn't get what you've mean. I tried to follow the steps you've written but I could not find any issues on that. The corresponding buffer has correctly renamed.

![Kapture 2020-08-03 at 22 55 15](https://user-images.githubusercontent.com/546312/89190486-80e16d00-d5dc-11ea-8ae8-99eb62f7080c.gif)

With

```vim
" vim -u ~/.vim/vimrc.min
if has('vim_starting')
  set nocompatible
endif

nnoremap ; :
nnoremap : ;

set packpath=
set runtimepath+=~/.config/nvim/pack/minpac/start/fern.vim

filetype plugin indent on
syntax on
```

So could you write a step by step procedure?

**Comment by nickjj** [comment]
Are you using Vim or NeoVim? I'm using Vim 8.1.

In the report I noticed these problems in a real world project in a repeatable way with more deeply nested directories that each had multiple directories and files in it. I will try to come up with reproduceable steps later today.

**Comment by lambdalisue** [comment]
Merged. Please make a new issue if you found a reproducable steps. @nickjj

**Comment by nickjj** [comment]
Sorry on the delayed response.

I'm still getting this behavior on the latest master and I can reproduce it in a minimal case. New issue has been created at https://github.com/lambdalisue/fern.vim/issues/150.

**Comment by lambdalisue** [comment]
Reopened while implementation added on #135 cause E13 and it's a bit too complex to handle and reverted.
https://github.com/lambdalisue/fern.vim/pull/167

**Comment by lambdalisue** [comment]
### Rename buffer

Use `:file {dst}` to rename the buffer. It uses existing one thus anything related to the buffer is retained.
However, it causes E13 and it seems there is no straight way to avoid E13 in all cases.

### Replace buffer (NERDTree)

Use `:edit {dst}` to replace a buffer shown in a window. It opens a new buffer thus the following are NOT retained.

- Unsaved changes
- Undo history
- Jumps (`keepjumps` may help?)
- Alternate files (`keepalt` may help?)
- Cursor position
- etc. Probably a lot more

**Comment by lambdalisue** [comment]
I think I've found a workaround for "Rename buffer".

https://github.com/lambdalisue/fern.vim/pull/168
