### ISSUE TITLE
Suggestion: Allow creating directories with new-file if the path ends with /

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#133]
Needless to say I'm in the process of moving from NERDTree to this extension (mainly for the speed boosts when manipulating files in directories that have hundreds of files).

One really nice feature of NT is that if you run `ma` which "modifies" a node and then "adds" something to it, you can create a new file by running `ma` and then creating `foo.txt` but you can also run `ma` and create a directory by doing `foo/`. The rule is that NT will create a directory if the path you're creating ends with `/`, otherwise it'll be a file.

This might not seem like a big deal but it is a nice quality of life enhancement. It means only having to remember one bind or work flow for creating both a file or directory. Currently with fern you need to perform either a `new-file` or `new-dir`. It adds a bit of mental overhead.

I know fern will create dependent paths when creating a file with `new-file` but sometimes you just want to create a directory on its own. Perhaps long term this could even mean replacing `new-file` and `new-dir` with `new-path`.

**Comment by lambdalisue** [comment]
I like the idea. Let's implement it.

**Comment by bluz71** [comment]
I like `new-file` and `new-directory` binds. So I would not like to see them go. In NERDTree I often forgot the ending `/` which annoyed me.

Rather, a new command `new-path` should be created for this task whilst keeping the existing commands as they are. Users can then choose which they like, the pair of `new-file` / `new-dir` or the unified `new-path`. Hopefully @lambdalisue does not remove the existing commands.

@nickjj,

> Needless to say I'm in the process of moving from NERDTree to this extension (mainly for the speed boosts when manipulating files in directories that have hundreds of files).

It seems my Reddit post got you to change file manager in the end :grin:

The performance of fern.vim compared to NERDTree is like night and day. It is addictive, once you experience it you can't go back.

One thing is that fern.vim generally appears more a spiritual successor to Shougo's [vimfiler](https://github.com/Shougo/vimfiler.vim) plugin than it being a descendant of NERDTree. Especially with regards to separate commands for `new-dir` and `new-file` and using *marking* for bulk files tasks.

**Comment by lambdalisue** [comment]
Thanks for the feedback. OK, I'll **add** `new-path` rathern than *replace* :+1:.

**Comment by lambdalisue** [comment]
@nickjj @bluz71 I've added "new-path" action on #138. Could you try?

**Comment by nickjj** [comment]
Seems to be working here for a few basic tests (creating nested files and directories).

**Comment by bluz71** [comment]
From my tests, `new-path` works well :thumbsup:

I still prefer separate `new-file` and `new-directory` most of the time, however `new-path` is better when creating a deep path with a file at the end.

So I will have a mapping for all three: `new-file`, `new-directory` and `new-path`.

**Comment by lambdalisue** [comment]
> I still prefer separate new-file and new-directory most of the time, however new-path is better when creating a deep path with a file at the end.

You can use `new-file` with `a/nested/path/like/this` to create a file in a deep nested path.

**Comment by bluz71** [comment]
Your right, one learns something new every day. That's cool.

Only two mappings needed for me.

As for NERDTree --> fern.vim, would adding:

```viml
nmap <buffer> ma <Plug>(fern-action-new-path)
```

to your [Tips page](https://github.com/lambdalisue/fern.vim/wiki/Tips#define-nerdtree-like-mappings) be worthwhile?

**Comment by lambdalisue** [comment]
> to your Tips page be worthwhile?

Yes please.

**Comment by bluz71** [comment]
Done.
