### ISSUE TITLE
When toggling the draw with reveal, subsequent reveals of the same file name do not get revealed

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#136]
Repeatable steps:

1. Create a mapping of `noremap <silent> <Leader>f :Fern . -drawer -reveal=% -toggle -width=35<CR><C-w>=` (thanks @bluz71)

2. Set up something to test with

```
mkdir -p /tmp/testfern \
  && touch /tmp/testfern/foo \
  && touch /tmp/testfern/bar
```

3. `cd /tmp/testfern && vim .`

4. In Vim `:e foo`

5. Use custom mapping to toggle fern open

6. Notice how `foo` is selected

7. Use custom mapping to toggle fern closed

8. Use custom mapping to toggle fern open

9. Notice how `foo` is no longer selected, instead the first item in the tree is which is the `testfern` directory

There's other potentially related issues too, like if you semi-randomly start clicking foo and bar to open them in a single pane and toggle the draw a few times, sometimes the wrong file will be revealed. I can't reproduce this exactly, but it happens often. This is different than the repeatable steps because in this case it reveals and highlights the wrong file, not the root item in the tree. This is more easily tested by adding the contents "foo" and "bar" to each file so you can see the foo file being open but the bar item is revealed.

**Comment by lambdalisue** [comment]
Confirmed with Vim. It does not happen on Neovim.

```vim
" vim -u ~/.vim/vimrc.min
if has('vim_starting')
  set nocompatible
endif

nnoremap ; :
nnoremap : ;

set packpath=
set runtimepath+=~/.config/nvim/pack/minpac/start/fern.vim

noremap <silent> <Leader>f :Fern . -drawer -reveal=% -toggle -width=35<CR><C-w>=

filetype plugin indent on
syntax on
```

**Comment by lambdalisue** [comment]
I fixed this issue but maybe the current correct behavior is not what you want.
In that case, create a new issue as a feature request with more clear description of the ideal behavior @nickjj

**Comment by nickjj** [comment]
Hi,

The ideal behavior would be following steps 1-9 and no matter the previous state of the draw, whenever the draw becomes visible the file you have actively focused would end up being revealed / highlighted in the draw. If the draw remains open (such as not toggling), then focusing a different buffer would always reveal that file in the draw upon calling Fern with reveal.

**Comment by lambdalisue** [comment]
I've close this while the corresponding bug has fixed. 

It sounds you've to need "force reveal mode" or whatever. It would be nice to create a new issue as a feature request.
Additionally, it sounds once feature explained here (https://github.com/lambdalisue/fern.vim/issues/114) would be implemented, it may help

**Comment by nickjj** [comment]
Thanks, if it's all the same to you, can we use #114 as that?

Or feel free to open another issue and copy / paste my previous response.
