### ISSUE TITLE
rename not available when you do `Fern .`

### ISSUE THREAD

**Issue by thisguychris** [lambdalisue/fern.vim#142]
Hi @lambdalisue 👋 Thanks for making this plugin. I think a bump on issue.

The action `rename`, isn't shown when you do: `:Fern .` I have to do `:Fern %:h` to make it available?

Steps:
1. `vim`
2. `:Fern .`
3. highlight a file then do `a` for action,
4. type ren then <tab>

![no rename](https://i.imgur.com/Pxv5zsA.png)

After I do `:Fern %:h`, it magically appears

![with rename](https://i.imgur.com/a9iaYOW.png)

**Comment by lambdalisue** [comment]
Prob. already fixed by https://github.com/lambdalisue/fern.vim/pull/140

**Comment by thisguychris** [comment]
hey @lambdalisue, confirmed! just updated, I can now see :rename

Thanks for the quick fix! 🙌
