### ISSUE TITLE
Reveal bug in commit 3a8f2a7, fern window goes blank

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern.vim#143]
Hello again,

I think commit [3a8f2a7](https://github.com/lambdalisue/fern.vim/commit/3a8f2a7cb6ef04526548398baee8d90c6f1c852a) introduced a reveal bug, or so `git bisect` tells me.

Steps to reproduce the bug:

- Open (Neo)vim in fern.vim repository

- Start fern with `:Fern . -drawer -toggle`

- Scroll down and open License file in the editor

- Close drawer with `:Fern . -drawer -toggle`

- Reveal License with `:Fern -drawer -reveal=%`

- Close drawer with `:Fern -drawer -toggle`

- Open drawer with `:Fern -drawer -toggle`

The fern window is now blank, and remains blank.

Best regards.

**Comment by lambdalisue** [comment]
Thanks. Fixed.

**Comment by bluz71** [comment]
That was super fast :clap:

Bug fixed. Many thanks.
