### ISSUE TITLE
Fern cannot enter a directory with %xx, #, or $ (Hard to fix)

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/fern.vim#145]
It seems fern failed to enter a directory that contains `#` or `$` on its path. Note that `expand` action works.

```
mkdir $
touch $/hello
mkdir #
touch #/hello
vim
:Fern .
```

![Kapture 2020-08-04 at 22 21 56](https://user-images.githubusercontent.com/546312/89298905-eeef6800-d6a0-11ea-9ca2-4b0a9809dc29.gif)

https://vim-jp.slack.com/archives/CLKR04BEF/p1596546767351500

**Comment by Milly** [comment]
Can not open directory named `%[hexdigit][hexdigt]` too.
```
mkdir %20
touch %20/hello
Fern .
```

**Comment by bluz71** [comment]
Does vimfiler work with such directory names?

**Comment by lambdalisue** [comment]
Probably. This limitation basically comes from FRI what fern defines.

**Comment by lambdalisue** [comment]
@Milly Fixed. Please try #169

**Comment by Milly** [comment]
Everything is working fine.

### About path conversion

path|FRI
--|--
a b/|fern://9ae84588/file:///C:/tmp/a%252520c$
a#b/|fern://9ae84588/file:///C:/tmp/a%252523b$
a$b/|fern://9ae84588/file:///C:/tmp/a$b$
a%20b/|fern://9ae84588/file:///C:/tmp/a%25252520b$
a%b/|fern://9ae84588/file:///C:/tmp/a%252525b$

* Percent-encoding is **triple** applied, is it correct?
* `$` in path is not percent-encoding, is it correct?
* The directory mark `$` is confusing, better change it to `/`?

**Comment by lambdalisue** [comment]
> Percent-encoding is triple applied, is it correct?

Actually, I'm not sure. I think it could be **double** but it's working well with **triple** at least thus I just let it.

> $ in path is not percent-encoding, is it correct?

Yes. The trailing `$` is now a special character defined on FRI.

> The directory mark $ is confusing, better change it to /?

It sounds fair but I didn't want to add extra changes at least on #169

**Comment by Milly** [comment]
>> $ in path is not percent-encoding, is it correct?
>
> Yes. The trailing $ is now a special character defined on FRI.

I said `$` in paht `a$b/`, not the trailing `$`.

**Comment by lambdalisue** [comment]
> I said $ in paht a$b/, not the trailing $.

Got it. I think the behavior is just OK (not really correct/incorrect)

**Comment by Milly** [comment]
> > Percent-encoding is triple applied, is it correct?
> 
> Actually, I'm not sure. I think it could be **double** but it's working well with **triple** at least thus I just let it.

I used `fern#fri#parse(...)` in my customization (eg, show parsed path in statusline).
But, `path` in the result is not a file-URI.
It's a percent-encoded file-URI (means **double** encoded).

real path: `C:\tmp\a b\`
FRI: `fern://9ae84588/file:///C:/tmp/a%252520c$`
fern#fri#parse(...)['path']: `file:///C:/tmp/a%2520c`
expected file-URI: `file:///C:/tmp/a%20c`

Sorry, if `fern#fri#parse(...)` is only for internal.

If possible, I want an API that gets the real path from the FRI.

**Comment by lambdalisue** [comment]
I understand it would be nice if the FRI encodes character twice rather than three times while it seems correct behavior. 
However, I think it's not a bug while it's working well. So I'll investigate it when I have time or send me PR 👍 

Well, It's not documented (yet) but you can use `fern#fri#to#filepath({fri})` for that purpose like

```vim
let fri = fern#fri#parse('fern://9ae84588/file:///C:/tmp/a%252520c$')
let path = fern#fri#to#filepath(fern#fri#parse(fri.path))
echo path
" C:\tmp\a c\
```

It returns a real path in a working platform
