### ISSUE TITLE
The "-reveal" option should have more priority than cursor restorement or add a way to force it

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern.vim#146]
Hello,

Steps to reproduce the issue:

- Open (Neo)vim in fern.vim repository

- Start fern with `:Fern . -drawer -toggle`

- Open tree `autoload/fern/comparator` (with `l` keys by default) and then open `default.vim` file

- Navigate back to fern and close `autoload/fern/comparator` tree (with `h` keys by default). Note, close all subtrees as well.

- Close fern with `:Fern . -drawer -toggle`

- Reveal current `default.vim` file, this should work fine

- Again close the tree `autoload/fern/comparator`, including subtrees

- Close fern again with `:Fern . -drawer -toggle`

- Reveal current `default.vim` file, this will **not** reveal the file in tree.

The expectation is that reveal should always reveal the file.

Best regards.

**Comment by lambdalisue** [comment]
Note: This is what the issue author also expects in https://github.com/lambdalisue/fern.vim/issues/136

**Comment by lambdalisue** [comment]
For now, it's correct behavior. So this is a kind feature request.

**Comment by bluz71** [comment]
> Add a way to forcedly apply reveal

Yes, this is what I would consider reveal should be. It ideally should force since it is an explicit action to display the file revealed in the project tree. Sometimes revealing and sometimes is confusing.

I recommend that file reveal should actually be force reveal.

**Comment by lambdalisue** [comment]
@bluz71 @nickjj Fixed. Please check #170.

**Comment by bluz71** [comment]
@lambdalisue 

Two thumbs up. Just tested. Looks good to me. Reveal works great.

Many thanks.
