### ISSUE TITLE
Reloading only reloads the selected item + children but maybe it should reload all nodes?

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#156]
The documentation says: `Reload on a cursor node and its children.`

So it is working as intended, but in practice I'm finding myself always wanting to do a full reload, not just a specific node. This often means having to do a bunch of extra key presses and movements to get that effect.

Imagine having:

```
foo/
  hello.py
  test.jpg
  test-2.jpg
```

And you're editing `hello.py`, and then you toggle reveal fern. So now `hello.py` is highlighted, but outside of Vim you decided to  use an image editor to create `test-3.jpg`. So you pop focus over to fern and issue the reload command, except nothing changes because you had `hello.py` selected.

In NT, the reload command would reload all nodes, which I think seems reasonable because chances are you want to update the tree's state as a whole.

The above example is pretty contrived but it demonstrates the issue. In a real world project you might have many deeply nested directories and perhaps you run a script (like a web app file generator) that generates 5 different files in 5 different directories but that happened outside of Vim. It's very tedious to have to goto those 5 directories and manually reload each one, or manually have to unselect the revealed file to find the root node, and then reload based on that and then go back and reveal the file you were editing.

Would it be possible to get an option to `reload-all` to get that behavior, or maybe even change `reload` to always reload all? I'm having difficulty thinking of a use case where I wouldn't want the tree to be fully updated when I want to explicitly issue a reload.

What do you think?

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/issues/128

**Comment by nickjj** [comment]
No chance of this ever making its way into the core fern?

Using the `fern-mapping-reload-all` plugin with a custom mapping requires almost as much vimrc config as the plugin's code itself.

**Comment by lambdalisue** [comment]
Good point. OK, I'll make it.

**Comment by lambdalisue** [comment]
I've applied the change. Could you try #158?

**Comment by nickjj** [comment]
Awesome, thanks a lot for this.

Confirmed working with a test of:

- `git pull && git checkout reload-all`
- In a project with multiple files and directories, revealing a file, ensuring the highlight is active
- Renaming a file outside of Vim
- Creating a new file outside of Vim
- Deleting a file outside of Vim
- Executing the regular `reload` action

Everything was reloaded as expected.
