### ISSUE TITLE
Toggle fern

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#157]
Hello. I have read manual and I can't find ability toggle fern. It means to open and to close fern by same shortcut. Could you please implement this feature?

**Comment by lambdalisue** [comment]
![fern vim: 🌿 General purpose asynchronous tree viewer written in Pure Vim script 2020-08-09 01-26-15](https://user-images.githubusercontent.com/546312/89715233-5843e380-d9df-11ea-9a30-671d10611734.png)

![fern vim 2020-08-09 01-26-48](https://user-images.githubusercontent.com/546312/89715255-6b56b380-d9df-11ea-9f6a-3a9d8ad047bd.png)
