### ISSUE TITLE
Opening a file in a horizontal split takes ~3 seconds, splitting vertically is effectively instant

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#162]
Reproduceable steps with Vim 8.2 (but the same problem happens with Vim 8.1 too):

1. Create a few files `mkdir /tmp/testfern && touch /tmp/testfern/1 && touch /tmp/testfern/2`
2. Open the directory with Vim `vim /tmp/testfern`
3. Toggle the fern draw open
4. Select file `1` or `2` in fern
5. Execute the `split` (horizontal) action, notice how long it takes to open
6. Execute the `vsplit` (vertical) action, notice how it opens pretty much instantly

My binds are set up like this:

```vim
function! FernInit() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-expand-collapse)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:select)",
        \   "\<Plug>(fern-action-expand)",
        \   "\<Plug>(fern-action-collapse)",
        \ )
  nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> <2-LeftMouse> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> n <Plug>(fern-action-new-path)
  nmap <buffer> d <Plug>(fern-action-remove)
  nmap <buffer> m <Plug>(fern-action-move)
  nmap <buffer> M <Plug>(fern-action-rename)
  nmap <buffer> h <Plug>(fern-action-hidden-toggle)j
  nmap <buffer> r <Plug>(fern-action-reload)
  nmap <buffer> k <Plug>(fern-action-mark-toggle)j
  nmap <buffer> s <Plug>(fern-action-open:split)
  nmap <buffer> v <Plug>(fern-action-open:vsplit)
  nmap <buffer><nowait> < <Plug>(fern-action-leave)
  nmap <buffer><nowait> > <Plug>(fern-action-enter)
endfunction

augroup FernGroup
  autocmd!
  autocmd FileType fern call FernInit()
augroup END
```

Using the `s` and `v` binds are how I performed the test.

System info:

- 3.2ghz i5 quad core
- 16gb of memory
- Running inside of WSL 2 (Ubuntu 20.04 LTS)

**Comment by Shougo** [comment]
You should check s mapping.
:verbose nmap s.

**Comment by nickjj** [comment]
It shows this result: `n  s*          * :let @/='\<'.expand('<cword>').'\>'<CR>cgn` where as `:verbose nmap v` shows no results.

I have these 2 mappings:

```
nnoremap <silent> s* :let @/='\<'.expand('<cword>').'\>'<CR>cgn
xnoremap <silent> s* "sy:let @/=@s<CR>cgn
```

I didn't think they would conflict with a regular `s` mapping.

Thanks for leading me to this. If I remap the fern key to something else then there's no delay.

Is there any way to keep `s` for both tho?

**Comment by Shougo** [comment]
> I didn't think they would conflict with a regular s mapping.

It is conflicted.  Because Vim cannot decide which map is executed when `s` is pressed.

> Is there any way to keep s for both tho?

If the mappings really needed, you should define it as buffer level instead of global.

**Comment by lambdalisue** [comment]
Thank you @Shougo !

**Comment by bluz71** [comment]
<nowait> is handy as well in similar scenarios.

I needed to use it for a few fern mappings.

**Comment by bluz71** [comment]
Sorry, `<nowait>` got scrubbed in my previous post.
