### ISSUE TITLE
Open a drawer when a script is opened with vim

### ISSUE THREAD

**Issue by AFAgarap** [lambdalisue/fern.vim#164]
Hello. Thank you for this great plugin.

I just want to ask if there's a way to open a Fern drawer automatically when I open a file with vim, i.e. when I do something like this `vim script_1.py` should open both `script_1.py` and the Fern drawer. 

Thank you!

**Comment by lambdalisue** [comment]
Start from https://github.com/lambdalisue/fern.vim/wiki/Tips#start-fernvim-on-vim-startup-with-a-particular-directory

**Comment by lambdalisue** [comment]
It sounds this is a question about Vim script rather than fern.vim itself thus try Stackoverflow or whatever to get more help.

**Comment by AFAgarap** [comment]
I'll just go back to NERDTree or try something else. Thank you.

**Comment by jonescamilla** [comment]
> I just want to ask if there's a way to open a Fern drawer automatically when I open a file with vim, i.e. when I do something like this `vim script_1.py` should open both `script_1.py` and the Fern drawer.

Were you able to find a solution to this? I'm currently looking into implementing something like this but my knowledge in vim scipt is limited.
