### ISSUE TITLE
Default mapint for removing files

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#171]
Hey. Why fern have no default key bind for deleting files?

**Comment by lambdalisue** [comment]
Because `remove` is not undoable operator. In contract to that, `trash` has default mapping.

**Comment by timsofteng** [comment]
Oh, got it. I didn't scroll help page enough:)

**Comment by jonescamilla** [comment]
I just deleted a folder of components by accident, is there no way to undo a delete?
