### ISSUE TITLE
Feature request: option to display full path on FernRootText

### ISSUE THREAD

**Issue by joenye** [lambdalisue/fern.vim#178]
It would be useful to have the option to display the full/absolute path (with text overflow ellipsis prefix) on FernRootText, rather than only the current directory name. Full path is the default behavior of NERDTree.

Is there any way to configure this at the moment? It feels to me that this is something a [renderer plugin](https://github.com/lambdalisue/fern.vim/wiki/Plugins#renderer-plugins) should be able to override.

**Comment by lambdalisue** [comment]
Unfortunately no. As you said, if someone made a render plugin, it's possible.

Additionally, I'm not going to provide such an option or render plugin officially while it would be a bit difficult for the non-file schemes (e.g. What is the full/absolute path of `dict://` scheme?)

**Comment by joenye** [comment]
Thanks for the quick response.

I have a working solution that you may wish to consider inside the `render_node` function. Here's a working example based on the [nerdfont.vim renderer](https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/master/autoload/fern/renderer/nerdfont.vim).

```vim
function! s:render_node(node, base, options) abort
  let level = len(a:node.__key) - a:base
  if level is# 0
    let suffix = a:node.label =~# '/$' ? '' : '/'
    if stridx(a:node.bufname, 'fern:\/\/\/file:\/\/\/')
      " Show full path if in file:// scheme
      let prefix = a:node.bufname[15:-2]
    else
      let prefix = a:node.label
    endif
    return prefix . suffix . '' . a:node.badge
  endif
  let leading = repeat(a:options.leading, level - 1)
  let symbol = s:get_node_symbol(a:node)
  let suffix = a:node.status ? '/' : ''
  return leading . symbol . a:node.label . suffix . '' . a:node.badge
endfunction
```

**Comment by lambdalisue** [comment]
I'm sorry but fern is not only for `file://` scheme thus I don't want to add `file://` specific code in any renderer.

I'll think of an acceptable way to get a similar result.

**Comment by lambdalisue** [comment]
@joenye is #181 satisfied your request?

**Comment by joenye** [comment]
This looks really great! Two comments I have:

1. You could keep the custom function signature more generic, and thus not require a special flag for `root_node` if it's possible to deduce whether a node is a root node by looking at the node itself (e.g. it has no parent, or depth/layer is 0).
2. Would this work with existing custom renderers? Ideally it would be something that custom renderers don't need to manually support, and inherit automatically.

**Comment by lambdalisue** [comment]
> You could make the custom function signature more generic by not requiring a special flag for is_root if it's possible to deduce whether a node is a root node by looking at the node itself (e.g. it has no parent, or depth/layer is 0).

Correct. We can remove `is_root`.

> Would this work with existing custom renderers? Ideally it would be something that custom renderers don't need to manually support, and inherit automatically.

Unfortunately no. That's kind a reason why I'm not satisfied the API yet.

**Comment by lambdalisue** [comment]
@joenye I've changed the way completely. Please try #190 instead.

**Comment by joenye** [comment]
Thanks @lambdalisue. I think this should be sufficient for now.

To make it more friendly for "non-power-users", you could consider providing named built-in functions, so that the majority of users don't have to provide their own. This could then be documented in `fern.txt`, and details for writing their own custom function could be documented in `fern-developer.txt`.

For the "non-power-user" their config could then look something like:

```vim
 call fern#hook#add(
        \ 'core:update_visible_nodes',
        \ funcref('g:fern_update_root_full_path'),
        \)
```

Where `g:fern_update_root_full_path` would be one of many built-in functions that can be used here.

**Comment by lambdalisue** [comment]
Sorry for bothering you. Please try #195 @joenye

**Comment by joenye** [comment]
Sorry for the late reply, @lambdalisue. I've now tested this change and can confirm it works well and addresses #178.
