### ISSUE TITLE
feature: add option to preview file

### ISSUE THREAD

**Issue by babygau** [lambdalisue/fern.vim#193]
it would be helpful if we could see the content of file while traveling through _fern tree_

**Comment by lambdalisue** [comment]
What do you mean by "preview"? You can open it.

**Comment by babygau** [comment]
i mean when i travel through the tree up and down, a temporary _preview buffer_ would show up without opening the file. this will work just like `fzf preview`.

**Comment by lambdalisue** [comment]
What is a temporary *preview buffer*? Vim itself has *preview window*. Are you talking about that?

**Comment by babygau** [comment]
sorry for any confusion. if you use vscode you might come across this behaviour aka [preview mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode)

**Comment by lambdalisue** [comment]
I'm sorry but that link doesn't help me... I could not get any actual image or behavior or whatever from a screenshot pasted on that link (a part of the screenshot of VS code?)

![image](https://user-images.githubusercontent.com/546312/92316905-0b880400-efaf-11ea-8160-b656bf271ebd.png)

**Comment by babygau** [comment]
with preview mode

![Screen Recording 2020-09-06 at 12 58 41 pm](https://user-images.githubusercontent.com/1514823/92317209-c7920f00-f041-11ea-8936-4654a1f07d13.gif)

without preview mode 

![Screen Recording 2020-09-06 at 1 00 54 pm](https://user-images.githubusercontent.com/1514823/92317213-cf51b380-f041-11ea-9bf1-efc98fa2494a.gif)

pls look at the tab, new file will not open a new tab in preview mode unless you edit this file.

in (neo)vim, preview mode will reuse current buffer without creating a new buffer when we use `j`, `k` to navigate up and down. it would work like `fzf.vim` with `--preview` option

i'm not sure if it's possible to do so.

**Comment by lambdalisue** [comment]
Now I got it. Well, I'm not sure if it's useful as VS code while it would cause some performance issue but combinations of `fern#smart#leaf()`, `fern#smart#drawer()` and `<C-w>p` would mimic that behavior like

![Kapture 2020-09-06 at 12 53 06](https://user-images.githubusercontent.com/546312/92317820-d59c4d00-efb9-11ea-826e-35bf638f3dc5.gif)

The entier code is something like:

```vim
function! s:fern_preview_init() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-preview-or-nop)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:edit)\<C-w>p",
        \   "",
        \ )
  nmap <buffer><expr> j
        \ fern#smart#drawer(
        \   "j\<Plug>(fern-my-preview-or-nop)",
        \   "j",
        \ )
  nmap <buffer><expr> k
        \ fern#smart#drawer(
        \   "k\<Plug>(fern-my-preview-or-nop)",
        \   "k",
        \ )
endfunction

augroup my-fern-preview
  autocmd! *
  autocmd FileType fern call s:fern_preview_init()
augroup END
```

**Comment by babygau** [comment]
awesome! that's exactly what i want. imho, you could make it as an option for the plugin `let g:fern#previewmode=0` etc.

thank you so much!

**Comment by lambdalisue** [comment]
> imho, you could make it as an option for the plugin let g:fern#previewmode=0 etc.

I'm sorry but I'm trying to avoid adding features as much as possible to keep the fern.vim itself simple and clean.
Instead of adding the feature, I've added Wiki section for that https://github.com/lambdalisue/fern.vim/wiki/Tips#preview-leaf-content-by-jk-like-vs-code
