### ISSUE TITLE
Cursor is hidden when inside of a fern rename buffer

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#196]
This is with Vim 8.2.

I'm not sure if this is a recent issue. I just pulled master 2 minutes before the time of this issue.

If I mark a few files and run `action-rename`, the buffer where I can do the renaming has no visible cursor. Also there's no cursor in the main fern buffer too, but to be honest I can't remember if that was there or not before.

In the most simple case I can reproduce this 100% of the time. Just opening Vim with fern visible causes the cursor to be gone in the fern buffer. The cursor is still visible in any non-fern buffer.

**Comment by lambdalisue** [comment]
1. Cursor is hidden in fern buffer is a feature
2. Cursor is hidden in fern rename buffer is a bug

You can disable that feature by https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L378

**Comment by lambdalisue** [comment]
Fixed on [1.21.1](https://github.com/lambdalisue/fern.vim/releases/tag/v1.21.1).

**Comment by nickjj** [comment]
Confirmed working with that latest build. Thanks!
