### ISSUE TITLE
With Vim 8.0, the disable netwr wiki example throws: vim error E492: Not an editor command: ++nested call s:hijack_directory()

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#201]
Hi,

Someone who is using my dotfiles with Vim 8.0 (the default version on Ubuntu 18.04) is getting that error and I believe it stems from this `autocmd BufEnter * ++nested call s:hijack_directory()`, which is taken from this wiki example of Fern:

```vim
" Disable netrw.
let g:loaded_netrw  = 1
let g:loaded_netrwPlugin = 1
let g:loaded_netrwSettings = 1
let g:loaded_netrwFileHandlers = 1

augroup my-fern-hijack
  autocmd!
  autocmd BufEnter * ++nested call s:hijack_directory()
augroup END

function! s:hijack_directory() abort
  let path = expand('%:p')
  if !isdirectory(path)
    return
  endif
  bwipeout %
  execute printf('Fern %s', fnameescape(path))
endfunction
```

Is there a version of this snippet that works for Vim 8.0+ instead of 8.1+?

And on a related note, let's say an example can be made to fix this on Vim 8.0, does Fern itself work with 8.0?

**Comment by lambdalisue** [comment]
No. Fern does NOT support Vim 8.0

**Comment by nickjj** [comment]
Thanks. I missed the badge in the readme that stated 8.1+.
