### ISSUE TITLE
Having user defined Sort function breaks ? mapping

### ISSUE THREAD

**Issue by habamax** [lambdalisue/fern.vim#202]
I press `?` to get available mappings and it errors with:

![image](https://user-images.githubusercontent.com/234774/92736593-17930d80-f383-11ea-95c1-c35e5ce9f49a.png)

If I remove/rename function `Sort` everything works.

**Comment by lambdalisue** [comment]
Wow... I didn't know that the function local variable conflicts with the global variable...... Thanks for the report. I'll consider ways to avoid that.

**Comment by lambdalisue** [comment]
Prob. #205 fix the issue. Please try @habamax

**Comment by habamax** [comment]
@lambdalisue thx, it works now

**Comment by habamax** [comment]
But I think there is another issue apeared:

![image](https://user-images.githubusercontent.com/234774/92874415-b1ed6280-f410-11ea-8aef-42bc4ab6a181.png)


1. I have toggled fern drawer
2. call a command that closes all windows and loads set of new buffers

```
" Open vim configs
command! Init :silent only
            \<bar>:exe printf("e %s/vimrc", fnamemodify($MYVIMRC, ":p:h"))
            \<bar>:exe printf("bo vs %s/plugin/mappings.vim", fnamemodify($MYVIMRC, ":p:h"))
            \<bar>:exe printf("bo vs %s/plugin/pack_list.vim", fnamemodify($MYVIMRC, ":p:h"))
            \<bar>:exe printf("bo vs %s/plugin/pack_setup.vim", fnamemodify($MYVIMRC, ":p:h"))
            \<bar>:exe printf("bo vs %s/after/plugin/setup.vim", fnamemodify($MYVIMRC, ":p:h"))
            \<bar>:1wincmd w
```
3. Try to change windows with `C-w w`


PS, and it is actually even simpler: just toggle fern drawer with:

     nnoremap <F8> :Fern . -drawer -toggle -reveal=%<CR>


![image](https://user-images.githubusercontent.com/234774/92874874-1c060780-f411-11ea-9122-a988bd3dd576.png)

**Comment by lambdalisue** [comment]
Ah sorry. I've noticed that bug. I've applied nonrelated changes as well on that PR. I'll fix that before the merge 👍

**Comment by habamax** [comment]
Thx!
