### ISSUE TITLE
Back cursor to window where fern was called

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#203]
Imagine you open few windows inside vim. Then you try to open fern from one of them. And then you close fern by toggle option. In this way your cursor will locate in one specific window which is situated first from left side of terminal everytime. But I want back my cursor to window where I called fern.

Implement this feature please

**Comment by lambdalisue** [comment]
@timsofteng Please try #206

**Comment by timsofteng** [comment]
> @timsofteng Please try #206

I did :PlugUpdate
If that's all i need to do it's doen't work.

**Comment by lambdalisue** [comment]
No. You need to use the `restore-focus` branch.

**Comment by timsofteng** [comment]
> No. You need to use the `restore-focus` branch.

Great. Looks like it works like I expected.
Thanks.
Can You merge it into master please?
