### ISSUE TITLE
Automatically close fern after opening file

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#204]
How I can automatically close fern after opening file?

I have tried this solution
`nmap <silent><buffer> <CR> <Plug>(fern-action-open)<ESC><BAR>:FernDo close<CR>`

I just put it into my .vimrc but it doesn't help. Fern still opened.

**Comment by lambdalisue** [comment]
I'm sorry what I've addressed on #200 was wrong. The correct one is

https://github.com/lambdalisue/fern.vim/wiki/Tips#close-fern-after-open

```vim
nmap <buffer><silent> <Plug>(fern-my-open-and-close)
      \ <Plug>(fern-action-open)
      \ :<C-u>FernDo close -drawer -stay<CR>
```

But I confirmed that the above still does not work. I'll investigate it.

**Comment by lambdalisue** [comment]
It seems that the tips are wrong. I tested on v1.2.0 but did not work. So this is kind a feature request.

**Comment by lambdalisue** [comment]
Found. Use the following mappings to open and close. Wiki has updated as well.

```vim
  nnoremap <Plug>(fern-close-drawer) :<C-u>FernDo close -drawer -stay<CR>
  nmap <buffer><silent> <Plug>(fern-action-open-and-close)
      \ <Plug>(fern-action-open)
      \ <Plug>(fern-close-drawer)
```

**Comment by timsofteng** [comment]
> Found. Use the following mappings to open and close. Wiki has updated as well.
> 
> ```viml
>   nnoremap <Plug>(fern-close-drawer) :<C-u>FernDo close -drawer -stay<CR>
>   nmap <buffer><silent> <Plug>(fern-action-open-and-close)
>       \ <Plug>(fern-action-open)
>       \ <Plug>(fern-close-drawer)
> ```

I'm using toggle for open and close fern by same shortcut. 
`map <C-p> :Fern . -reveal=% -drawer -toggle <CR>`
What shuold I do to try your solution and keep toggle feature?

**Comment by lambdalisue** [comment]
I don't get what you didn't get... I've no idea why you are talking about opening a fern window...

**Comment by timsofteng** [comment]
I just want autoclosing feature. It means fern close itself when I open file from it.

**Comment by lambdalisue** [comment]
> I just want autoclosing feature. It means fern close itself when I open file from it.

That [what my post](https://github.com/lambdalisue/fern.vim/issues/204#issuecomment-691637575) does. Did you try?

![Kapture 2020-09-19 at 18 29 19](https://user-images.githubusercontent.com/546312/93663914-11e5a800-faa6-11ea-9dee-328a545f2c84.gif)

**Comment by lambdalisue** [comment]
@timsofteng is your issue solved?

**Comment by timsofteng** [comment]
> @timsofteng is your issue solved?

Yes. It works. But how can I trigger this action by default when I'm press enter or E?

**Comment by lambdalisue** [comment]
Just directly overwrite `<CR>` or https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L935-L942

**Comment by paraduxos** [comment]
> 
> 
> Just directly overwrite `<CR>` or https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L935-L942

I can't make it work.
```vim
" Open fern as drawer
noremap <silent> <leader>e :Fern . -drawer -toggle <CR>

" Open file and automatically close fern
nnoremap <Plug>(fern-close-drawer) :<C-U>FernDo close -drawer -stay<CR>
nmap <buffer><silent> <Plug>(fern-action-open-and-close)
        \ <Plug>(fern-action-open)
        \ <Plug>(fern-close-drawer)

function! s:init_fern() abort
  " map to <CR>
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-or-expand-or-collapse)
	\ fern#smart#leaf(
        \   "\<Plug>(fern-action-open-and-close)", " Substitute default function
	\   "\<Plug>(fern-action-expand)",
	\   "\<Plug>(fern-action-collapse)",
	\ )
endfunction
```

**Comment by lambdalisue** [comment]
Put 

```vim
nmap <buffer><silent> <Plug>(fern-action-open-and-close)
       \ <Plug>(fern-action-open)
       \ <Plug>(fern-close-drawer)
```

in `s:init_fern()`

**Comment by paraduxos** [comment]
Still not working

```vim

noremap <silent> <leader>e :Fern . -drawer -toggle <CR>
nnoremap <Plug>(fern-close-drawer) :<C-U>FernDo close -drawer -stay<CR>

function! s:init_fern() abort
  nmap <buffer><silent> <Plug>(fern-action-open-and-close)
        \ <Plug>(fern-action-open)
        \ <Plug>(fern-close-drawer)

  nmap <buffer><expr>
        \ <Plug>(fern-my-open-or-expand-or-collapse)
	\ fern#smart#leaf(
        \   "\<Plug>(fern-action-open-and-close)",
	\   "\<Plug>(fern-action-expand)",
	\   "\<Plug>(fern-action-collapse)",
	\ )
endfunction
```
I also try move some lines in and out of `s:init_fern()` but nothing seems to work.
Or do I have to use `<CR>` mapping somewhere else, not just `<expr>`?

And just in case, I don't have any mapping to `<CR>`.
```vim
$ :verbose imap <cr>
// No mapping found
```

**Comment by lambdalisue** [comment]
I think you forgot to map `<Plug>(fern-my-open-or-expand-or-collapse)` to `<CR>`

```vim
nmap <buffer> <CR> <Plug>(fern-my-open-or-expand-or-collapse)`
```

**Comment by paraduxos** [comment]
Ok. Now it's work. Thanks!!

I just confused on how `<CR>` work since it works out of the box, so I didn't map in the first place.
