### ISSUE TITLE
Cursor is not restored event after Neovim has closed

### ISSUE THREAD

**Issue by winkee01** [lambdalisue/fern.vim#207]
neovim open a directory and then type `:Fern .`  to open the browsing view, the cursor type will become verticle bar.

steps:

1) open current directory, my cursor type is box
![image](https://user-images.githubusercontent.com/49930785/93280929-7b8f5900-f7fd-11ea-9b5c-a39f2233f268.png)

2) use `:Fern .` to browse, now my box cursor becomes vertical bar
![image](https://user-images.githubusercontent.com/49930785/93197947-e6e61600-f77e-11ea-9b6f-548847af4e77.png)

3) exit neovim, but cursor is still vertical bar
![image](https://user-images.githubusercontent.com/49930785/93198060-0d0bb600-f77f-11ea-911d-1d6c04d25187.png)

##### my iterm2's settings for cursor:
![image](https://user-images.githubusercontent.com/49930785/93197753-9bcc0300-f77e-11ea-9f92-fc3e4a872fab.png)

plugins:

```
Plug 'antoinemadec/FixCursorHold.nvim'
Plug 'lambdalisue/fern.vim'
```

OS: Mac OS X, Catalina
Terminal: iTerm2
Editor: neovim

PS:
I test fern in vim, but it will not change my cursor, so I guess there is some problem with working in neovim?

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L378-L380

**Comment by lambdalisue** [comment]
Oops. Sorry, I did'nt notice the last line

> exit neovim, but cursor is still vertical bar

But I could not reproduce. Please write a **minimum** vimrc and steps to reproduce.

**Comment by winkee01** [comment]
#### 1) ~/.vimrc
```
set nocompatible " must be first
set encoding=utf-8

" ================ General Config ====================
set number
set backspace=indent,eol,start  " Allow backspace in insert mode
set history=1000                " Store lots of :cmdline history
set showcmd                     " Show what command you are typing at the bottom
set showmode                    " Show current mode down the bottom
set gcr=a:blinkon0              " Disable cursor blink
set visualbell                  " No sounds
set autoread                    " Reload files changed outside vim
set clipboard+=unnamed          " Global clipboard
" set paste                     " Causing auto-pairs not work

set numberwidth=1           " minimum column size to display line numbers
set whichwrap+=<,>,[,],h,l  " Make these chars can go beyond current line
set vb t_vb=                " disable visualbell and window flashing when error occurs

set hidden

" == Indentation ==
set autoindent
set smartindent " deprecated
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

set cindent             " ----------------- C/C++ Code Style Setting --------------
                        " V select a block of code, then =, code will auto indent
                        " :set paste before do a paste where the buffer is
                        " another file, after paste, :set nopaste to get back
                        " autoindent

filetype plugin on
filetype indent on
syntax on

set list listchars=tab:\ \ ,trail:·
"set list listchars=tab:→\ ,space:·,nbsp:␣,eol:¶,precedes:«,extends:»,trail:·
set nowrap
set linebreak
set nostartofline

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default
" set viminfo='100,f1

 " Enable a menu at the bottom of the window for command completion when type command in vim
set wildmenu  wildmode=full
set wildchar=<Tab> wildcharm=<C-Z>

set scrolloff=3         "Start scrolling when we're 3 lines away from margins
set sidescrolloff=5
set sidescroll=1
set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

" ================ Completion =======================

set wildmode=list:longest
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~,*.so,*.swp,*.zip "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

" Turn off auto-indent when pasting text
:set pastetoggle=<F3>

" == Turn Off Swap Files ==
set noswapfile
set nobackup
set nowb

if has('persistent_undo')
  let myUndodir = expand('$HOME/.undodir')
  if !isdirectory(myUndodir)
    call system('mkdir -p ' . myUndodir)
  endif

  let &undodir = myUndodir
  set undofile
  set undolevels=5000
  set undoreload=10000
endif

" auto commands
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2

call plug#begin('~/.vim/plugged')
Plug 'antoinemadec/FixCursorHold.nvim'
Plug 'lambdalisue/fern.vim'
call plug#end()
```

#### 2) ~/.config/nvim/init.vim

```
set termguicolors
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

**Comment by winkee01** [comment]
I found that if in tmux window, it will reproduce the issue. otherwise ok.

**Comment by winkee01** [comment]
Another, it does not display a box cursor even if work "normally", in my case, the effect is like below:
![image](https://user-images.githubusercontent.com/49930785/93209494-ca52d980-f790-11ea-800b-4ce6eabfde6c.png)
as you can see, there is no cursor, but a highlighted line indicates on which line the cursor is.

**Comment by lambdalisue** [comment]
Please make it a minimum.

**Comment by winkee01** [comment]
the minimun can be 
```
set nocompatible " must be first
set encoding=utf-8

call plug#begin('~/.vim/plugged')
Plug 'antoinemadec/FixCursorHold.nvim'
Plug 'lambdalisue/fern.vim'
call plug#end()
```

**Comment by winkee01** [comment]
hi, are you able to reproduce the issue?

**Comment by winkee01** [comment]
g:fern#disable_viewer_hide_cursor in some cases but it seems not work with neovim.

**Comment by lambdalisue** [comment]
> hi, are you able to reproduce the issue?

Unfortunately no.

**Comment by winkee01** [comment]
do you use tmux? I open nvim in tmux, and this reproduces every time. I tested on different machines.

**Comment by ludamillion** [comment]
When I have some time I'll try to reproduce with a minimum config but I'm also having the exact issues described. I'm currently using Tmux and kitty terminal

**Comment by lambdalisue** [comment]
Unfortunately, I'm using Tmux on iTerm2 as well but I could not reproduce it...

**Comment by lambdalisue** [comment]
@winkee01 @ludamillion 

The PR description has several topics thus I'd like to make sure if both of your face a real issue

> use :Fern . to browse, now my box cursor becomes vertical bar

> Another, it does not display a box cursor even if work "normally", in my case, the effect is like below:
> as you can see, there is no cursor, but a highlighted line indicates on which line the cursor is.

Above are **feature**. Fern **hide** cursor in fern buffer so you'll never see cursor on fern buffer (disable this feature by `g:fern#disable_viewer_hide_cursor = 1`)

So if you are talking about this. The issue is definitely invalid.

> exit neovim, but cursor is still vertical bar

This is **not feature** and I could not reproduce this in the following environment

- macOS Catalina 10.15.6
- iTerm 2 Build 3.3.12
- Tmux 3.1b
- Zsh 5.8
- Vim 8.2.1456 or Neovim v0.4.4

If you are talking about this. Please make minimum information to reproduce the issue.
Additionally, I feel it's kind Neovim's issue rather than fern itself while you said that the cursor is not restored after Neovim has closed.

**Comment by winkee01** [comment]
Somehow it works normally today, just don't know why.

**Comment by lambdalisue** [comment]
Closable?
