### ISSUE TITLE
delete files

### ISSUE THREAD

**Issue by winkee01** [lambdalisue/fern.vim#208]
I have two enhancement suggestions:
1) currently, when deleting a file, the cursor will jump to its parent node, would it be better if the cursor just jumps to its neighbor node(file)?

2) a quicker delete key like `dy` might be helpful, in some cases we just need to delete useless files faster and more efficiently.

other issues:
when type d to delete a file, I can sense a bit of delay, usually, I should expect an instant pop-up of confirmation, a few milliseconds I have to wait, it this the case in your machine? 

thanks

OS: Mac OS X, Catalina
Editor: neovim
Terminal: iTerm2 + fish + tmux

**Comment by lambdalisue** [comment]
1. Duplicated https://github.com/lambdalisue/fern.vim/issues/134
2. User can define their own mappings

> other issues:
> when type d to delete a file, I can sense a bit of delay, usually, I should expect an instant pop-up of confirmation, a few milliseconds I have to wait, it this the case in your machine?

No. I'm not sure but `:help map-nowait` may helps you

**Comment by winkee01** [comment]
```
function! FernInit() abort
  nmap <buffer> n <Plug>(fern-action-new-path)
  nmap <buffer> d <Plug>(fern-action-remove)
  nmap <buffer> m <Plug>(fern-action-move)
endfunction
```

I used an online version of config copied from somewhere, and its mapping is like above. is this the problem? what's the manual way to do so.

**Comment by lambdalisue** [comment]
It's definitely Vim's feature. Read `:help map-nowait` or go stackoverflow.
