### ISSUE TITLE
duplicate a file?

### ISSUE THREAD

**Issue by winkee01** [lambdalisue/fern.vim#209]
would it be ok to duplicate a file?

```
proj/
   copy.sh     : cursor at this lime, press dup
```

```
proj/
  copy.sh
  copy1.sh    :file is copied, and the cursor is placed on editing the new file name
```

**Comment by winkee01** [comment]
this is useful when I need to create several files that have a similar content structure, for example, I create several commodities pages, 

```
fruit/
   apple.js
   banana.js
   orange.js
```

so when I create the first file `apple.js` filled with some contents, then I can simply duplicate this file to many others, modify their names accordingly, and then do specific editing to those files.

**Comment by lambdalisue** [comment]
I'll think about it. For now, use `clipboard-copy` and `clipboard-paste` combination like `CP`

**Comment by lambdalisue** [comment]
I'm sorry but I think `copy` action itself is enough while everyone thinks "which name is correct for duplicated file" differently.
