### ISSUE TITLE
Do NOT move cursor down when the expanded branch does not have children

### ISSUE THREAD

**Issue by winkee01** [lambdalisue/fern.vim#210]
currently, when opening an empty folder, the cursor will move down to other files, e.g.

before:
```
+empty/.       : cursor position, press open
     file.txt
```

after:
```
-empty/.      
     file.txt       : cursor position
```

this causes an unpleasant user experience because when I want to create a file in this empty folder, I have to open it first (make + to -), otherwise the newly created file will not reside inside of this folder.

so, a better way may be: keep this cursor at the original line if the folder is empty

after:
```
-empty/.      :cursor position
     file.txt 
```

**Comment by lambdalisue** [comment]
Got it. I'll try.

**Comment by noscript** [comment]
I think these should be separate actions to expand and expand + jump-to-child.

In general it would be great to match the behavior to other tree widget implementations (Qt, GTK, TK, WPF, VSCode, NERDTree). Neither one moves the cursor to child node automatically AFAIK.

![output](https://user-images.githubusercontent.com/717109/94007206-ca169780-fda9-11ea-999b-5673421de693.gif)

**Comment by lambdalisue** [comment]
@noscript Make sense. OK, I'll change the default behavior of `expand` action and may add `expand:jump-to-child` or whatever for backward compatibility.

**Comment by lambdalisue** [comment]
@winkee01 @noscript Please try https://github.com/lambdalisue/fern.vim/pull/217

Note that I didn't change the default behavior, mean that what @noscript suggested is mapped to `expand:stay` which is NOT aliased to `expand` in default. To change it, users need to map it manually like

```vim
nmap <buffer> <Plug>(fern-action-expand) <Plug>(fern-action-expand:stay)
```

**Comment by noscript** [comment]
Thanks for implementing it.


> ```viml
> nmap <buffer> <Plug>(fern-action-expand) <Plug>(fern-action-expand:stay)
> ```

However this doesn't work, `fern#mapping#node#init()` remaps is back to `<Plug>(fern-action-expand:in)`.

**Comment by lambdalisue** [comment]
Oops. I made a new issue for that thanks 👍 
https://github.com/lambdalisue/fern.vim/issues/221

**Comment by lambdalisue** [comment]
@noscript Fixed. Please try the latest master.
