### ISSUE TITLE
Cascade nested directories

### ISSUE THREAD

**Issue by eyalch** [lambdalisue/fern.vim#211]
There are many situations in which a directory has only a single directory, so I think it would be better to cascade them.

Take the following structure for example:
![image](https://user-images.githubusercontent.com/5116133/93604097-99abb380-f9cd-11ea-9a2c-e4d4af4ce1f0.png)

Wouldn't it be better to show `nvim/.config/nvim/` instead of `nvim/` in the first line and just list the nested files under it?

NERDTree has this feature turned on by default (`g:NERDTreeCasadeOpenSingleChildDir`).

Thanks!

**Comment by lambdalisue** [comment]
Hum... It's way complicated. I'm not sure if the feature is useful enough to make the code complicate. The feature would reduce the maintainability.

**Comment by lambdalisue** [comment]
I'm sorry but it conflicts with the current feature design. Fern list up children asynchronously when the branch node has expanded (that's why fern is quite fast compared to Netrw, NERDTree). To implement the feature you described, fern need to **recursively** list up children and **it would drastically reduce the performance**. I don't think the feature worth reducing the performance drastically.

**Comment by eyalch** [comment]
@lambdalisue I too think that this feature doesn't worth the performance impact, but just for the matter of discussion, how bad would the performance be if we just check whether a directory contains only a single directory?

**Comment by lambdalisue** [comment]
To check that, we need to expand the branch nodes **recursively**. For example, fern took a bit time to expand `node_modules` and it's ok usually while users don't expand it. However, with the feature, fern must expand that directly as well to check if the directory has children or not.

> if we just check whether a directory contains only a single directory

Unfortunately, fern does not have such a feature, and introducing that is adding extra complexity in the individual scheme implementations. [Fern already provides a **strict** specs for the scheme implementation (provider)](https://github.com/lambdalisue/fern.vim/blob/master/doc/fern-develop.txt#L196-L237) and I don't want to break it.

Well, I don't have any negative aspects of the feature itself. I just don't think I (or anyone) can make it.
I'm OK for adding that feature if someone success adding that feature without performance issue and break existing scheme provider spec.

**Comment by brandon1024** [comment]
I would definitely agree that this could have performance implications with large directories (definitely `node_modules`). In spite of this, this is a feature I would love to see in later versions of the plugin. This is particularly useful in Java projects, which typically have a src/main/java/com/<your company>/product nested package structure. Other editors, like IntelliJ, will expand nested structures like this, and it's a pretty nice feature.

I'm going to take a bit of time to hack on this and see if it's not something that can be implemented in our own vimrc, with little modification to the plugin itself.
