### ISSUE TITLE
Feature request: activate with "-"

### ISSUE THREAD

**Issue by duganchen** [lambdalisue/fern.vim#215]
The reason I love vim-dirvish is because it's so easy to activate ("-" key) and deactivate. Are there any plans to either set up default mappings for that, or to document copy-and-paste-ready code snippets to set it up so that it has roughly the same keybindings as dirvish?

**Comment by lambdalisue** [comment]
What is activate?

**Comment by lambdalisue** [comment]
@duganchen Could you explain what is "activate" while I've no idea the behavior of vim-dirvish?

**Comment by duganchen** [comment]
Oh, you haven't used Dirvish? It's... good too.

In Dirvish (as in Vinegar), "-" opens a window, pretty much the equivalent of "Fern .".It's true that "nnoremap <silent> :Fern ." isn't a difficult mapping for an individual user to come up with. I'm just saying it might (if you agree, of course) be appropriate to either officially document it or make default.

**Comment by lambdalisue** [comment]
> Oh, you haven't used Dirvish? It's... good too.

Actually I had tried but didn't satisfy a long time ago.

> In Dirvish (as in Vinegar), "-" opens a window, pretty much the equivalent of "Fern .".It's true that "nnoremap :Fern ." isn't a difficult mapping for an individual user to come up with. I'm just saying it might (if you agree, of course) be appropriate to either officially document it or make default.

Well, I don't want to mess up users' mappings by unnecessary global mappings. Additionally, as you said, it's really easy to say "map the command to whatever you want."

And you may miss that there is a Tips page on Wiki which mentioned very similar functionality.
https://github.com/lambdalisue/fern.vim/wiki/Tips#how-to-map-a-command-to-open-a-buffer-parent-directory-or-current-working-directory-when-the-buffer-is-not-a-file
