### ISSUE TITLE
Allow to remove the trailing slashes from dir nodes

### ISSUE THREAD

**Issue by xvitcoder** [lambdalisue/fern.vim#223]
Allow to remove the trailing slashes from dir nodes.
It would be nice to have this as a global variable

**Comment by lambdalisue** [comment]
Unfortunately, no. The trailing slashes are used to determine if the node is a branch or not on syntax highlight thus it's not possible to remove it.

**Comment by brandon1024** [comment]
@lambdalisue had a quick look through the source for the default renderer and this looks like a fairly easy feature to implement now.

I don't really have a need for this feature myself, but wouldn't it just be a matter of adding the `/` suffix if some config option is set?

```vim
function! s:render_node(node, base, options) abort
  let level = len(a:node.__key) - a:base
  if level is# 0
    return a:options.root_symbol . a:node.label . '' . a:node.badge
  endif
  let leading = repeat(a:options.leading, level - 1)
  let symbol = a:node.status is# s:STATUS_NONE
        \ ? a:options.leaf_symbol
        \ : a:node.status is# s:STATUS_COLLAPSED
        \   ? a:options.collapsed_symbol
        \   : a:options.expanded_symbol
  let suffix = a:node.status && a:options.with_suffix ? '/' : ''
  return leading . symbol . a:node.label . suffix . '' . a:node.badge
endfunction
```
