### ISSUE TITLE
An error occurs if the directory name starts with a dot

### ISSUE THREAD

**Issue by Milly** [lambdalisue/fern.vim#224]
Open directory that is starts with a dot.
Such an error occurs.
> [fern] ERROR: {'throwpoint': 'function <SNR>69__worker[12]..<SNR>67__publish[22]..<SNR>67__invoke_callback[6]..<lambda>2
490[1]..<SNR>164_sync_restore_cursor[6]..<SNR>164_sync_focus_node, 行 12', 'exception': 'failed to find a node []'}

OS: Windows 10 1909
Editor: gVim.exe 8.2.1719

**Comment by lambdalisue** [comment]
I could not reproduce it with 

```vim
if has('vim_starting')
  set encoding=utf-8
  scriptencoding utf-8
endif

function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  call minpac#add('lambdalisue/fern.vim')
endfunction

syntax on
filetype indent plugin on
```

in

- OS: Windows 10 19041.264
- GVim 8.2.1734
- Fern: 1.26.0 (latest)

![Kapture 2020-09-26 at 16 32 41](https://user-images.githubusercontent.com/546312/94335323-eae32500-0015-11eb-8aa8-689942c46409.gif)

Please provide me a minimal vimrc and minimal steps.

**Comment by Milly** [comment]
Probably because of my own settings.
Now close.
