### ISSUE TITLE
Lose position after open: Cursor jumps to top when Fern is opened

### ISSUE THREAD

**Issue by rafi** [lambdalisue/fern.vim#229]
1. Open `Fern -drawer -toggle .`
2. Scroll-down the tree
3. Close Fern by toggling `Fern -drawer -toggle .`
4. Open again `Fern -drawer -toggle .`
5. Cursor jumps to line no. 1 after a few milliseconds

(I also tried with `-keep`)

Is it possible to disable cursor jump after opening Fern?
I'd like to preserve my position in file-tree.

**Comment by lambdalisue** [comment]
@rafi Fixed. Please upgrade your fern.vim to the latest.
