### ISSUE TITLE
Fern drawer is duplicated when opened after opening a file

### ISSUE THREAD

**Issue by rafi** [lambdalisue/fern.vim#232]
1. `nvim`
1. `Fern -toggle -drawer .`
1. Select ~~an item~~ a vim file and open it (`<Plug>(fern-action-open)`)
1. `Fern -toggle -drawer .`

Fern window is duplicated, and not re-used as expected. (I tried toggling `g:fern#disable_viewer_auto_duplication`)

**Comment by lambdalisue** [comment]
Could not reproduce.

![Kapture 2020-09-27 at 00 53 59](https://user-images.githubusercontent.com/546312/94344683-f5281200-005b-11eb-8e23-9000aa7961d3.gif)

**Comment by rafi** [comment]
@lambdalisue It actually happens only if the file I open is a *.vim file.

**Comment by lambdalisue** [comment]
No, I could not reproduce it.

**Comment by rafi** [comment]
@lambdalisue 

NVIM v0.5.0-nightly-273-g4a996bc43

```
" minimal vimrc
if &compatible | set nocompatible | endif

let g:python3_host_prog = $XDG_DATA_HOME . '/python/pyenv/versions/neovim/bin/python'

let $DEIN_DIR = $XDG_CACHE_HOME . '/vim/dein/repos/github.com/'

set runtimepath^=$DEIN_DIR/lambdalisue/fern.vim

filetype plugin indent on
syntax enable
```

1. `nvim -u minimal.vim`
1. `:Fern -toggle -drawer .`
1. Open vim type file
1. `:Fern -toggle -drawer .`

![image](https://user-images.githubusercontent.com/147918/94346127-42dc5480-0033-11eb-89da-1cb04695c0a1.png)

**Comment by lambdalisue** [comment]
@rafi 

Unfortunately, no.

![Kapture 2020-09-27 at 02 15 58](https://user-images.githubusercontent.com/546312/94346406-6faa5f00-0067-11eb-8b2e-159d4955e19f.gif)

I've used the following equivalent vimrc

```vim
if exists('+compatible') && &compatible
  set nocompatible
endif

nnoremap ; :
nnoremap : ;

set packpath=
set runtimepath^=~/ghq/github.com/lambdalisue/fern.vim

filetype plugin indent on
syntax on
```

**Comment by lambdalisue** [comment]
@rafi Any update?

**Comment by lambdalisue** [comment]
@rafi https://github.com/lambdalisue/fern.vim/pull/279 may solve the issue

**Comment by rafi** [comment]
@lambdalisue it does! thanks. :)
