### ISSUE TITLE
How to exclude multiple files or directories ??

### ISSUE THREAD

**Issue by Goku-San** [lambdalisue/fern.vim#233]
Hello Could you please tell me how to exclude multiple files or directories ??? 
E.x. I want to **hide .git directory and .byebug file** but  **show .gitingore file**

I have set  ```let g:fern#default_hidden=1```, so what do I enter here ``` let g:fern#default_exclude= ??? ```

I've tried 
```let g:fern#default_exclude=['.git','.byebug']``` and
```let g:fern#default_exclude='.git,.byebug'```

**Comment by lambdalisue** [comment]
You need to specify a string pattern. See ':help pattern' for detail.

Note that the value is the default value of 'exclude' action, mean that it much easier to find a correct value by try and error with that action rather than with the variable.

**Comment by Goku-San** [comment]
Hello @lambdalisue 
I have seen ```:help pattern``` and I still can't do it.

I've tried bunch of different things like
```
\v\.(git\/)
\v\(\.git)[\/]
\.git\/
```   
etc...
These all match on a folder in normal mode when you try with regular search ```/ ```
 
And even tried a regular folder and still can not exclude it!! Also tried through the action exclude ``` normal a ...```

Any help is appreciated 'cause am out of ideas. 🤷‍♂️

**Comment by lambdalisue** [comment]
Try

```
let g:fern#default_exclude = '^\%(\.git\|\.byebug\)$'
```

**Comment by Goku-San** [comment]
Thank you very much @lambdalisue **this worked!** 

The thing is, all the combinations that I tried (*tried your combination as well*) , I did them through the  normal search ```/``` to get a hl match and then through the action exclude and they did't work, because it never occurred to me to add a  start ```^``` and  end ```$``` of string/line when trying with the action.So I chopped  the regex to just exclude the folder, after that I wrote you :) 

Thanks again, I appreciate the time you took to answer me.

**Comment by jwatts21** [comment]
Hello,
I'm struggling to get this to work, trying to exclude the node_modules directory. Read the  `:help pattern `  Tried variations of the examples above, no luck. 
```
`^\%(\node_modules\)$'`
'^node_modules$'
```

**Comment by lambdalisue** [comment]
```vim
let g:fern#default_exclude = '^node_modules$'
```

**Comment by Goku-San** [comment]
Hello @jwatts21, this is what I have and it works for me. I hope it works for you as well. :) 

```vim
" Add dirs and files inside the brackets that need to remain hidden
let hide_dirs  = '^\%(\.git\|node_modules\)$'  " here you write the dir names 
let hide_files = '\%(\.byebug\|\.ruby-\)\+'    " here you write the file names

let g:fern#default_exclude = hide_dirs . '\|' . hide_files  " here you exclude them
```

**Comment by jwatts21** [comment]
ok, so it appears i had it working with `'^node_modules$'` ... it was late. @Goku-San, I like your solution much better, thank you.  BTW, awesome plugin, discovered it a day ago from a blog post... really liking it. :)

**Comment by dragonlobster** [comment]
> Hello @jwatts21, this is what I have and it works for me. I hope it works for you as well. :)
> 
> ```viml
> " Add dirs and files inside the brackets that need to remain hidden
> let hide_dirs  = '^\%(\.git\|node_modules\)$'  " here you write the dir names 
> let hide_files = '\%(\.byebug\|\.ruby-\)\+'    " here you write the file names
> 
> let g:fern#default_exclude = hide_dirs . '\|' . hide_files  " here you exclude them
> ```

In a lua config for neovim, i had to escape the forward slashes:
```lua
﻿local hide_dirs  = "^\\%(\\.git\\|node_modules\\)$"
local hide_files = "\\%(\\.byebug\\|\\.ruby-\\)\\+"

vim.g["fern#default_exclude"] = hide_dirs .. "\\|" .. hide_files
```
