### ISSUE TITLE
overwrite some default key mappings

### ISSUE THREAD

**Issue by smartding** [lambdalisue/fern.vim#235]
I use `<C-l>`, `<C-h>` for jumping between vim splits, I usually map them as follows:
```vim
noremap <C-j> <C-W>j
noremap <C-k> <C-W>k
noremap <C-h> <C-W>h
noremap <C-l> <C-W>l
```
fern has mapped them for some other purposes, e.g. redraw. How can I map `<C-l>` back to `<C-W>j`?
I tried `let g:fern#disable_default_mappings = 1`, but that disabled way too many fern key mappings.

**Comment by lambdalisue** [comment]
Just overwrite that mapping when on `FileType` autocmd.
https://github.com/lambdalisue/fern.vim/wiki/Tips#how-to-customize-fern-buffer

e.g.

```vim
function! s:init_fern() abort
  nnoremap <buffer> <C-h> <C-w>h
  nnoremap <buffer> <C-l> <C-w>l
endfunction

**Comment by smartding** [comment]
Thanks, problem solved!

**Comment by ejoubaud** [comment]
Anyone else using tmux-vim-navigator and looking for a solution to this, here's mine:

```
function! s:init_fern() abort
  nmap <buffer><nowait> <C-j> :<C-U>TmuxNavigateDown<cr>
  nmap <buffer><nowait> <C-k> :<C-U>TmuxNavigateUp<cr>
  nmap <buffer><nowait> <C-h> :<C-U>TmuxNavigateLeft<cr>
  nmap <buffer><nowait> <C-l> :<C-U>TmuxNavigateRight<cr>
endfunction
augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
```

**Comment by KsenoxCr** [comment]
For people using Neovim:

`
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'fern',
  callback = function()
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-k>', '<C-w>k', { noremap = true, desc = 'Move focus to the top window' })
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-j>', '<C-w>j', { noremap = true, noremap = true, desc = 'Move focus to the bottom window' })
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-h>', '<C-w>h', { noremap = true, desc = 'Move focus to the left window' })
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-l>', '<C-w>l', { noremap = true, desc = 'Move focus to the right window' })
  end,
})
`

**Comment by KsenoxCr** [comment]
For people using neovim:

```
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'fern',
  callback = function()
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-k>', '<C-w>k', { noremap = true, desc = 'Move focus to the top window' })
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-j>', '<C-w>j', { noremap = true, noremap = true, desc = 'Move focus to the bottom window' })
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-h>', '<C-w>h', { noremap = true, desc = 'Move focus to the left window' })
    vim.api.nvim_buf_set_keymap(0, 'n', '<C-l>', '<C-w>l', { noremap = true, desc = 'Move focus to the right window' })
  end,
})
´´´
