### ISSUE TITLE
FernReveal does not work with an absolute path

### ISSUE THREAD

**Issue by Sevensidedmarble** [lambdalisue/fern.vim#236]
Whether I use `FernDo FernReveal PATH` or `Fern reveal=PATH`, they both don't work with absolute paths.

For context, I'm using it like this:

```vim
function! OpenDrawer()
  if &modifiable
    execute "FernDo -stay FernReveal " . @%
  endif
endfunction

autocmd BufEnter * :call OpenDrawer()
```

All I want is an autocmd that will automatically reveal the file I'm in, in my fern drawer, whenever I change buffers. I am pretty bad when it comes to vimscript, so it's totally possible that this is a dumb way of accomplishing that. If you have a better suggestion please let me know.

This does actually accomplish that, but I also use a ranger plugin as part of my development workflow, (I only want fern to be a drawer) and specifically when I open a new file from ranger, it seems to mangle my CWD for some reason, and `@%` always evaluates to an absolute path. If I open a file like `:e SOME_FILE`, this cmd works fine.

So is there a better way of doing this, or is it possible to make fern's reveal functionality work with absolute paths too?

**Comment by lambdalisue** [comment]
How about the following (I've not tested though)?
Note that I've no idea about `@%` thus I've used `%` instead.

```vim
function! s:OpenDrawer() abort
  if &modifiable && filereadable(expand('%'))
    execute printf('FernDo -stay FernReveal %s', fnameescape(expand('%:p')))
  endif
endfunction

autocmd BufEnter * ++nested call s:OpenDrawer()
```

Note that

- Using a script local function (`s:`) is better to keep global clean
- Using `abort` is better while Vim script won't stop on error. See `:help func-abort`
- Using `filereadable()` is better while there would be non-file modifiable buffers
- Using `printf()` make it a bit clear
- Using `fnameescape()` is prob. required while the path may contain characters needed to be escape. See `:help fnameescape()`
- Using `expand()` is prob. required while `%` is NOT expanded automatically in script. See `:help expand()`
- Using `++nested` is prob. required. See `:help autocmd-nested`
- You don't need `:` on autocmd


P.S.
You need a leading `-` on `Fern` command like

```
:Fern / -reveal=/Users/alisue
```

**Comment by Sevensidedmarble** [comment]
That particular snippet gives me a 'autocmd nesting too deep' error.

**Comment by lambdalisue** [comment]
Then

```vim
function! s:OpenDrawer() abort
  if &modifiable && filereadable(expand('%'))
    execute printf('FernDo -stay FernReveal %s', fnameescape(expand('%:p')))
  endif
endfunction

autocmd BufEnter * call s:OpenDrawer()
```

**Comment by Sevensidedmarble** [comment]
That doesn't give the nesting error, but unfortunately it always returns absolute paths, which fern's reveal argument doesn't seem to be able to parse.

**Comment by lambdalisue** [comment]
Got it and it's a bug as what you've first said. I'll fix it.

**Comment by lambdalisue** [comment]
@Sevensidedmarble 
Please try https://github.com/lambdalisue/fern.vim/pull/238 with settings on https://github.com/lambdalisue/fern.vim/issues/236#issuecomment-703433710

**Comment by Sevensidedmarble** [comment]
Nice, that works perfectly now. Thanks @lambdalisue.

**Comment by Sevensidedmarble** [comment]
I'd also propose this autocmd would be good for the readme, others might find it cool.

**Comment by lambdalisue** [comment]
It would fit on Wiki Tips. https://github.com/lambdalisue/fern.vim/wiki/Tips 👍
