### ISSUE TITLE
Fern on AIX with vim 8.1

### ISSUE THREAD

**Issue by arozehnal** [lambdalisue/fern.vim#237]
I made a few attempts with Fern on the Windows first, Then I installed:
 Plug 'lambdalisue/fern.vim'
 Plug 'lambdalisue/fern-hijack.vim'
on my main box with AIX and vim 8.1.

When calling e.g. 'Fern /tmp -drawer' only the empty split window is displayed, 
The tree of folders the left part of the window does not appear, only first line contains 'tmp'.
Fern does not respond at the touch of a key 'hjkl' - this works for me on Windows.
I have vim 8.1 on AIX box - is not this to be the cause of the problem?

[AIX_vim8.1_ver.txt](https://github.com/lambdalisue/fern.vim/files/5324204/AIX_vim8.1_ver.txt)

**Comment by lambdalisue** [comment]
I've no idea about AIX but Fern uses `ls` or `find` in non Windows thus if those command works on the terminal, Fern should works.

Does `Fern /` or `Fern .` shows result? Does the issue happen only when you try to open `/tmp` or `-drawer`?

**Comment by arozehnal** [comment]
ls and find works on the terminal fine.

'Fern .' is similar to 'Fern /tmp -drawer' - only name my $HOME appears.

an error is displayed when I press 'l' 

 4 unix[fern] <f77d1d4/file:///intax/roze$[-] 05.10. 13:29    1/1   1 32 0x0020
Error detected while processing function <SNR>141__exit_cb[14]..<lambda>103[1]..
<SNR>173_update:
line   18:
E155: Unknown sign: FernSignSpinner2

**Comment by lambdalisue** [comment]
Does `:mes`command show any messages?

**Comment by arozehnal** [comment]
AIX is a bit odd OS :-(

it has own implementation of *nix utilities, but they do not have some of the switches that the GNU version of utilities has :-(
e.g.. AIX find don't know switch -maxdepth
fortunately AIX allows GNU utils to be installed...

when I saw the output from ':mes'
    :mes
     fern] ERROR: Vim(sign):E239: Invalid sign text: ???
    fern] ERROR: find: bad option -maxdepth
   Error detected while processing function <lambda>103[1]..<SNR>173_update:
    line   18:
    155: Unknown sign: FernSignSpinner9
    fern] ERROR: find: bad option -maxdepth
    Error detected while processing function <SNR>141__exit_cb[14]..<lambda>103[1]..
    SNR>173_update:
    line   18:
    155: Unknown sign: FernSignSpinner2
    fern] ERROR: find: bad option -maxdepth
    492: Not an editor command: mescommand

I changed PATH (I prioritized the use GNU utils).

So, 'Fern /tmp -drawer' already displays the directory tree, keys 'hjkl' started working
But this error appears:
   Error detected while processing function <SNR>114__exit_cb[5]..<lambda>6644[1]..<SNR>146_update:
line   18:
   E155: Unknown sign: FernSignSpinner5

it appears only for some directories

**Comment by lambdalisue** [comment]
I think there are two issues

### Sign

```
ERROR: Vim(sign):E239: Invalid sign text: ???
```

It seems AIX could not show the default sign text. It probably causes `E155: Unknown sign: FernSignSpinnerX`.
Use the following code to apply custom frames on AIX. Note that the variable is **undocumented** thus it might be changed without announcement.

```vim
let g:fern#internal#spinner#frames = ['-', '+']
```

### -maxdepth

If `find` is not GNU compatible, it cannot be used as a provider. Use one of the following which works. Note that the variable is **undocumented** thus it might be changed without announcement.

```vim
let g:fern#scheme#file#provider#impl = 'ls'
```
```vim
let g:fern#scheme#file#provider#impl = 'readdir'
```
```vim
let g:fern#scheme#file#provider#impl = 'glob'
```

**Comment by lambdalisue** [comment]
@arozehnal 

Please provide me a result of the following

```
:echo &encoding
```

**Comment by lambdalisue** [comment]
@arozehnal 

Please try if https://github.com/lambdalisue/fern.vim/pull/239 solves **Sign** issue (that PR does not focus on `-maxdepth` issue)

**Comment by arozehnal** [comment]
echo &encoding -> iso-8859-2 

encoding utf-8 is prerequisite ?

==========================

let g:fern#internal#spinner#frames = ['-', '+']  solved Sign issue

`ERROR: Vim(sign):E239: Invalid sign text: ???`

==========================

I'm sorry I'm newbie to git/github =>
I don't understand your request ... _Please try if #239 solves Sign issue_

**Comment by lambdalisue** [comment]
> encoding utf-8 is prerequisite ?

Not sure yet. I haven't think about it.

> I'm sorry I'm newbie to git/github =>
> I don't understand your request ... Please try if #239 solves Sign issue

#239 is on the `printable` branch so you can try it by using that branch. For example, if you use [vim-plug](https://github.com/junegunn/vim-plug) to install fern.vim, you can get that branch version by:

```vim
Plug 'lambdalisue/fern.vim', { 'branch': 'printable' }
```

If you still couldn't get that, please let me know the result of the following. I'd like to know if the following expression is available to detect the issue

```vim
:echo '⠋' =~# '^[[:print:]]$'
```
Additionally, did you solve the issue of `-maxpath` by changing `g:fern#scheme#file#provider#impl` manually?

**Comment by arozehnal** [comment]
The issue issue of -maxpath I solved prioritized the use GNU utils in $PATH.

printable branch #239  works fine for me

echo '⠋' =~# '^[[:print:]]$'  return '1'

I think we can close this issue. 

I am admin of cca 20 boxes wit AIX. But only one box has vim 8.1, others have vim 8.0.
Now, I have to wait for summary rollout of vim 8.1 or 8.2.
Then I'll probably start using fern.

**Comment by athar-qadri** [comment]
I am facing the same issue on my Solaris Box. (Yes… you heard it right). Is there fix available for this?

**Comment by arozehnal** [comment]
I never ended up using Fern because I had a version of AIX that wouldn't let me install Fern, I ended up using https://github.com/tpope/vim-vinegar

But, so the result of that issue was that Fern ran on AIX.
