### ISSUE TITLE
what's that ^_ following the selected item?

### ISSUE THREAD

**Issue by smartding** [lambdalisue/fern.vim#240]
![pic-selected-201006-0908-35](https://user-images.githubusercontent.com/16423944/95147632-db9d6d80-07b3-11eb-8bc9-6d71f36c0165.png)
I'm using neovim-nightly with fern, and I noticed this `^_` following the selected item in fern as shown above. `^_` disappears when I focus on some other split in neovim.

What is this `^_`? Can I disable it?

**Comment by lambdalisue** [comment]
That's a character used in https://github.com/lambdalisue/fern-renderer-nerdfont.vim to distinguish columns.
I guess you may changed `conceallevel` or `concalcursor` which is used to hide that character, so please don't touch those options on the fern buffer.
If the issue still exist, please make a new issue on https://github.com/lambdalisue/fern-renderer-nerdfont.vim side.

**Comment by smartding** [comment]
> That's a character used in https://github.com/lambdalisue/fern-renderer-nerdfont.vim to distinguish columns.
> I guess you may changed `conceallevel` or `concalcursor` which is used to hide that character, so please don't touch those options on the fern buffer.
> If the issue still exist, please make a new issue on https://github.com/lambdalisue/fern-renderer-nerdfont.vim side.

It's the indentLine plugin that's changing the concealcursor. I was able to make that `^_` disappear by changing some settings of indentLine.
