### ISSUE TITLE
Feature request : when fern buffer enter, change pwd(cd/lcd/tcd) to root or old pwd

### ISSUE THREAD

**Issue by tsuyoshicho** [lambdalisue/fern.vim#244]
# fern cd/tcd/lcd on moves between fern and other buffers rather than within fern operation.

## Current status

When fern is opened, it becomes the pwd of the buffer before opening.
If open a file from fern, then cd/lcd/tcd and return  with <C-o> from file, pwd will be the file's.

## Feature request

When entering fern, returning from a file, switching to another buffer
Providing a way to return to the root or previous fern pwd.

## Trial result.

suggest from lambdalisue.
(change tcd to tcd:root)

```vim
  function! s:fern_init() abort
    " define autocmd for buffer
    autocmd BufEnter <buffer> ++nested
      \ :<C-u>call feedkeys("\<Plug>(fern-wait)\<Plug>(fern-action-tcd:root)", "x")<CR>
  endfunction

  augroup vimrc_init-fern
    autocmd!
    autocmd FileType fern nested call s:fern_init()
  augroup END
```

autocmd

```
--- Autocommands ---
BufEnter
    <buffer=2>
              :<C-u>call feedkeys("\<Plug>(fern-wait)\<Plug>(fern-action-tcd:root)", "x")<CR>
```

### result

not work
When tab switch / return from file occur message

```
BufEnter Autocommands for "<buffer=2>" の処理中にエラーが検出されました:
E21: 'modifiable' がオフなので、変更できません: :<C-u>call feedkeys("\<Plug>(fern-wait)\<Plug>(fern-action-tcd:root)", "x")<CR>
```

**Comment by tsuyoshicho** [comment]
## Trial2 result

modified suggest from Shougo.

```vim
  function! s:fern_init() abort
    " define autocmd for buffer
    " trial
    autocmd BufEnter <buffer>
     \ :call feedkeys("\<Plug>(fern-wait)\<Plug>(fern-action-tcd:root)", "x")
  endfunction

  augroup vimrc_init-fern
    autocmd!
    autocmd FileType fern nested call s:fern_init()
  augroup END
```

### result

It works fine.
Thank you both for lambdalisue,Shougo.

The main problem is solved, this code tips write to Wiki?
lambdalisue, please judge close or other handing it.

**Comment by lambdalisue** [comment]
```vim
function! s:fern_init() abort
  augroup my_fern_tcd
    autocmd! * <buffer>
    autocmd BufEnter <buffer> call feedkeys("\<Plug>(fern-action-tcd:root)")
  augroup
endfunction

augroup vimrc_init-fern
  autocmd!
  autocmd FileType fern ++nested call s:fern_init()
augroup END
```

Simplified.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Tips#perform-tcd-on-the-root-node-on-bufenter-autocmd
