### ISSUE TITLE
Fern -drawer changing the alternate-file register

### ISSUE THREAD

**Issue by mackarelfish** [lambdalisue/fern.vim#249]
Hey, firstly thank you for the awesome plugin!

When I was using fern with the -drawer option, the alternate-file register would be overridden by the fern buffer. This would happen if I open the drawer and then toggling it without selecting any file from the drawer. Thankfully there is a fix for this by mapping the toggle key with the `:keepalt` command like this,
` nnoremap <silent> <C-n> :keepalt Fern . -drawer -toggle<CR> `

Shouldn't this be the default behavior at least for the -drawer option? As this is the default behavior for other file drawer plugins like NERDTree and coc-explorer.

**Comment by lambdalisue** [comment]
Got it and I agree with that. I'll do it.

**Comment by lambdalisue** [comment]
Implemented. Please try #254 @mackarelfish

**Comment by mackarelfish** [comment]
> 
> 
> Implemented. Please try #254 @mackarelfish

Will do!

**Comment by mackarelfish** [comment]
> 
> 
> Implemented. Please try #254 @mackarelfish

Works like a charm! closing the issue :))
