### ISSUE TITLE
The 'terminal' action does not work from drawer style with "ERROR: Vim(edit):E32: No file name

### ISSUE THREAD

**Issue by mattn** [lambdalisue/fern.vim#252]
Repro steps

```vim
function! s:fern_setup() abort
  nmap <buffer> <nowait> X <plug>(fern-action-terminal)
  nnoremap <buffer> <nowait> q :<c-u>quit<cr>
endfunction

augroup __fern__
  au!
  autocmd FileType fern call s:fern_setup()
augroup END
nnoremap ,t :<c-u>Fern . -drawer -stay -keep -toggle -reveal=%<cr>
```

1. start Vim with empty buffer
2. type `,t`
3. select file
4. type `X`

:messages
```
[fern] ERROR: Vim(edit):E32: No file name
```

**Comment by lambdalisue** [comment]
It seems the 'terminal' action does not work from drawer style.

**Comment by mattn** [comment]
https://github.com/lambdalisue/fern.vim/blob/1cf4533d02cc73ec27f56912c0c894a0ca0ce326/autoload/fern/scheme/file/mapping/terminal.vim#L49-L52

This call makes command `execute 'edit'` with `No Name` buffer.

![image](https://user-images.githubusercontent.com/10111/96534984-d53ae580-12cb-11eb-9b3c-e995b7e6140d.png)

**Comment by lambdalisue** [comment]
Yes. So fern may should avoid `E32` on `fern#internal#buffer#open()` I guess.

**Comment by lambdalisue** [comment]
Fixed. Please try #253 @mattn

**Comment by mattn** [comment]
This works perfectly. Thank you.
