### ISSUE TITLE
Having a hard time styling Fern

### ISSUE THREAD

**Issue by sh0w98** [lambdalisue/fern.vim#258]
Hi! I've looked through the help files an the repo, but I can't figure out how to disable line numbers in the Fern buffer. Also, I was wondering if I can do something about the buffer name? I use xtabline for my tabline, and the long buffername kind of annoys me.
If the solution to these problems can be found in the docs, please show me where; there's a pretty decent change I just overlooked it.
Cheers!

**Comment by lambdalisue** [comment]
> but I can't figure out how to disable line numbers in the Fern buffer

See https://github.com/lambdalisue/fern.vim/wiki/Tips#how-to-customize-fern-buffer

> Also, I was wondering if I can do something about the buffer name? I use xtabline for my tabline, and the long buffername kind of annoys me.

I've no idea about xtabline and you should probably ask how to shrink it on that side.

**Comment by sh0w98** [comment]
Cheers, that helps a ton!

**Comment by MonstrousOgre** [comment]
> > but I can't figure out how to disable line numbers in the Fern buffer
> 
> See https://github.com/lambdalisue/fern.vim/wiki/Tips#how-to-customize-fern-buffer

How do I disable it only for the fern buffer? Adding `set nonumber` removes it for all of vim, even if I place it in `s:init_fern()`

**Comment by Shougo** [comment]
You need to use setlocal instead of set.

**Comment by MonstrousOgre** [comment]
@Shougo thanks! I'm new to vim
