### ISSUE TITLE
Correct width

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#270]
Hello. I'm using `linebreak` option in my vimrc, but this makes fern unpretty. Is it any option to prevent it on fern or some another way to make it more useful?

![image](https://user-images.githubusercontent.com/51912173/100603934-7cb92800-330e-11eb-81bd-7641b14bc707.png)

**Comment by mackarelfish** [comment]
You can add an autocommand to your vimrc to set specific rules to only apply for the fern buffer. Try adding this to your vimrc, it will disable line numbers and linebreak on the fern buffer
```
function! s:init_fern() abort
	setlocal nornu nonumber nolbr signcolumn=no
endfunction

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
```
