### ISSUE TITLE
Is there any way to set the drawer to open on the right side?

### ISSUE THREAD

**Issue by s9chroma** [lambdalisue/fern.vim#272]
Currently `Fern . -drawer` opens the drawer to the left side of vim, can it be configured to open on the right side?

**Comment by fitrh** [comment]
Yeah, currently digging for this, it's nice to have an option to open on the right side

**Comment by renanbrayner** [comment]
> Yeah, currently digging for this, it's nice to have an option to open on the right side

Yes, it doesn't mess with the code position on screen when it opens on the right side, im trying to find a way to do this too

**Comment by lambdalisue** [comment]
Unfortunately no and I'm not going to make it possible while it would add extra complexities which would cause tons of bugs. I decided to fix fern only on the left side to make things simple thus there are a lot of code which relies on that decision.  For example, [`<Plug>(fern-action-open:side)`](https://github.com/lambdalisue/fern.vim/blob/master/autoload/fern/mapping/open.vim#L22) would be broke if the drawer opens on the right side.

I may change my mind if the request is quite common but I doubt that if fern must be placed on the right side.

Sorry for this.

**Comment by sethen** [comment]
It would be nice to be able to position it on the right side.

**Comment by krehwell** [comment]
you can make a binding for it I guess, after opening it then bind it too with `<C-w> L` to move it to most right of the screen.
it would be like this, I tested it and it works
``` vim
nnoremap <silent> <Plug>(my-fern-toggle) :Fern . -drawer -reveal=% -width=27 -toggle<CR><C-w>L
nmap <Leader>pv <Plug>(my-fern-toggle)<Plug>(fern-action-zoom:reset)
```
make an nmap is a must too for fern to zoom-reset too so that it will reset the size when it is toggle

**Comment by lambdalisue** [comment]
I've changed my mind and tried to implement that feature so please try https://github.com/lambdalisue/fern.vim/pull/354 and give me feedbacks.

@s9chroma @fitrh @renanbrayner @sethen @krehwell

**Comment by krehwell** [comment]
seems pretty sycho if anyone really open it from right. anyway its good though if it has the option for it.

**Comment by lambdalisue** [comment]
syncho...? I'm sorry what that mean?

**Comment by krehwell** [comment]
psychopath, haha. I've never really seen anyone open file-tree on the right side unless Visual Studio user. (just a joke basically)

**Comment by s9chroma** [comment]
Thanks a lot for implementing this. It seems to work great. I'll inform if I get any issues.
