### ISSUE TITLE
Fern broke after `set iskeyword+=:`

### ISSUE THREAD

**Issue by paraduxos** [lambdalisue/fern.vim#278]
### Bug
Run this command twice or more
```vim
:Fern . -drawer -toggle
```

### Expected behavior
Fern should be closed

### What actually happen
Fern open duplicated window or more

### Environment
- Windows10
- NVIM v0.5.0-dev+992-gf3a8c930a
- [fern] 591e200

### Minimal vimrc
```vim
set runtimepath^=path/to/fern.vim
set iskeyword+=:

" nvim -u path/to/minimalvimrc.vim
```

**Comment by paraduxos** [comment]
Not sure if this related to #232 , but I guess I would mention here as well.

**Comment by lambdalisue** [comment]
Thanks for the report. I could reproduce the behavior 👍

**Comment by lambdalisue** [comment]
Got it. `\<` and `\>` are affected by `iskeyword`

```
							*/\<*
\<	Matches the beginning of a word: The next char is the first char of a
	word.  The 'iskeyword' option specifies what is a word character.
	|/zero-width|

							*/\>*
\>	Matches the end of a word: The previous char is the last char of a
	word.  The 'iskeyword' option specifies what is a word character.
	|/zero-width|
```

**Comment by lambdalisue** [comment]
@paraduxos Please try https://github.com/lambdalisue/fern.vim/pull/279

**Comment by paraduxos** [comment]
It's fixed now. :)

Ps. I actually want to debug myself, but I don't know where to start. How could you probe into source of this bug? Just curious.

**Comment by lambdalisue** [comment]
> Ps. I actually want to debug myself, but I don't know where to start. How could you probe into source of this bug? Just curious.

Because I knew that `iskeyword` affects some special characters in pattern comparison. And I've guessed that the issue exists around drawer detection.
