### ISSUE TITLE
The 'trash' action does not work on FreeBSD

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#280]
Hello. When I try to remove file or directory with press D and then Y nothing happens. File still exist.

FreeBSD 12.2

**Comment by lambdalisue** [comment]
Did you add additional requirements and confirm that those software works properly?
https://github.com/lambdalisue/fern.vim/wiki#additional-requirements

**Comment by timsofteng** [comment]
> Did you add additional requirements and confirm that those software works properly?
> https://github.com/lambdalisue/fern.vim/wiki#additional-requirements

Is it only one way to achive it? Unfortunately there is no one of these tools in freebsd repo.

**Comment by lambdalisue** [comment]
> Is it only one way to achive it? Unfortunately there is no one of these tools in freebsd repo.

Yes. Then fern does not support `trash` action on FreeBSD. Use `remove` action instead to execute `rm <file>` internally.

**Comment by lambdalisue** [comment]
Or PR is welcome. 

https://github.com/lambdalisue/vital-Whisky/blob/master/autoload/vital/__vital__/Async/File.vim#L275

**Comment by timsofteng** [comment]
Got it. One of necessary trash application id already in ports.
Thanks.

Can be closed.

**Comment by lambdalisue** [comment]
> One of necessary trash application is already in ports.

Which one and how did you get it work?

**Comment by timsofteng** [comment]
> > One of necessary trash application is already in ports.
> 
> Which one and how did you get it work?

I've just ask one of freebsd's ports mainteiners add `gomi` to ports. And it works with it now.

Thanks
