### ISSUE TITLE
On file open, buffer path is absolute and not relative to cwd

### ISSUE THREAD

**Issue by rafi** [lambdalisue/fern.vim#284]
I've noticed a strange behavior when opening files with `Fern`: The buffer name/path is **not** relative to current working-directory, in-fact, it is an absolute path. This causes strange behaviors later on in workflow.

**Reproduce:**

1. `cd` into a random project
2. Run `Fern .`
3. Open a file
4. Hit <kbd>C</kbd>+<kbd>g</kbd> -- you will see the path is absolute, and not relative to current project.
5. Execute `:echo bufname('%')` -- again, same result.

**Expected:**

Fern should open files with relative path to current-working directory.

**Minimal init.vim:**

```viml
if &compatible | set nocompatible | endif
let g:python3_host_prog = $XDG_DATA_HOME . '/python/pyenv/versions/neovim/bin/python'
let $PLUGINS_DIR = $XDG_CACHE_HOME . '/vim/dein/repos/github.com/'

set runtimepath^=$PLUGINS_DIR/lambdalisue/fern.vim
filetype plugin indent on
syntax enable
```

**Tested with:**
- Fern 1.28.9 316c8ad9
- NVIM `v0.5.0-dev+nightly-585-g2390a0d3c` and vim `8.2 1-2300`
- macOS 11.1

**Comment by lambdalisue** [comment]
The behavior is made on purpose. What kind of strange behavior you've faced?

**Comment by rafi** [comment]
@lambdalisue off the top of my head, anything that uses `bufname('%')` and expects a relative path. For example status and tablines. Other plugins might base other decisions on buffer path, lsp, ctags, etc.

What's the purpose of this behavior?

![image](https://user-images.githubusercontent.com/147918/104725330-98e81b80-573a-11eb-9c74-1f530cadd0c2.png)

**Comment by lambdalisue** [comment]
I believed that using an absolute path is less buggy but it seems it's not... I'll fix the behavior.

### What I confirmed

Prepare files and open Vim without plugins.

```
echo "Hello" > hello
echo "World" > world
vim -u NONE
```

Opening a buffer by a relative path shows relative path on `bufname('%')`

```
:e hello
:echo bufname('%')
hello
```

Opening a buffer by an absolute path shows an absolute path on `bufname('%')`

```
:e ~/world
:echo bufname('%')
~/world
```

Changing current working directory results both relative somehow.

```
:cd ..
:echo bufname('%')
alisue/world
:bp
:echo bufname('%')
alisue/hello
```

**So it seems using a relative path is more correct** as @rafi said.

**Comment by lambdalisue** [comment]
@rafi Colud you try https://github.com/lambdalisue/fern.vim/pull/286

**Comment by rafi** [comment]
Thanks for the quick response and action @lambdalisue, I'm enjoying Fern.
The branch works as expected so far. I use the git-status and nerdfont plugins, haven't used the ssh plugin yet.
