### ISSUE TITLE
Error when deleting directory outside of vim

### ISSUE THREAD

**Issue by rafi** [lambdalisue/fern.vim#287]
**Problem**

Directory deleted outside of Fern is still appearing and reload fails with:

> [fern] ERROR: find: /Users/rafi/some/directory/i/just/deleted: No such file or directory

**Reproduce**

1. Open Fern and expand a specific directory
2. Open a terminal and delete that specific directory
3. Return to Fern and reload (`<Plug>(fern-action-reload)`)
4. Error appears and directory is still displayed in Fern

> [fern] ERROR: find: /Users/rafi/some/directory/i/just/deleted: No such file or directory

**Comment by lambdalisue** [comment]
Thanks. Reproduced.

**Comment by lambdalisue** [comment]
I've tried to fix but it's too difficult. So probably this bug won't be fixed unless someone success.

What I've tried is

```diff
diff --git a/autoload/fern/internal/node.vim b/autoload/fern/internal/node.vim
index e095723..8b072a1 100644
--- a/autoload/fern/internal/node.vim
+++ b/autoload/fern/internal/node.vim
@@ -173,17 +173,19 @@ function! fern#internal#node#reload(node, nodes, provider, comparator, token) ab
   let inner = s:Promise.resolve(copy(a:nodes))
         \.then(s:AsyncLambda.filter_f({ v -> K(v) == k  }))
         \.then(s:AsyncLambda.filter_f({ v -> v.status is# s:STATUS_EXPANDED }))
-  let descendants = inner
-        \.then({v -> copy(v)})
         \.then(s:AsyncLambda.map_f({ v ->
-        \   fern#internal#node#children(v, a:provider, a:token, { 'cache': 0 }).then({ children ->
-        \     s:Lambda.if(v.status is# s:STATUS_EXPANDED, { -> children }, { -> []})
+        \   fern#internal#node#children(
+        \     v, a:provider, a:token, { 'cache': 0 },
+        \   ).then({ children ->
+        \     s:Lambda.if(v.status is# s:STATUS_EXPANDED, { -> [v] + children }, { -> [v]})
+        \   }).catch({ error ->
+        \     s:Lambda.pass([], fern#logger#warn(e))
         \   })
         \ }))
         \.then({ v -> s:Promise.all(v) })
         \.then(s:AsyncLambda.reduce_f({ a, v -> a + v }, []))
   let l:Done = fern#internal#node#process(a:node)
-  return s:Promise.all([outer, inner, descendants])
+  return s:Promise.all([outer, inner])
         \.finally({ -> Profile('all') })
         \.then(s:AsyncLambda.reduce_f({ a, v -> a + v }, []))
         \.finally({ -> Profile('reduce') })
```

But above code does not keep `status` of each nodes so calling `reload` twice break tree.

**Comment by lambdalisue** [comment]
@rafi I think I did. Please try https://github.com/lambdalisue/fern.vim/pull/288

Above changes a deep inside of the fern so I'll use it by myself at least for a week to make sure that the commit does not break existing behavior.

**Comment by rafi** [comment]
Thanks @lambdalisue, I'll checkout and use it to test.
