### ISSUE TITLE
'exception': 'Vim(return):E132: Function call depth is higher than ''maxfuncdepth'''}

### ISSUE THREAD

**Issue by trailblazing** [lambdalisue/fern.vim#290]
:Fern . -drawer
 [fern] ERROR: {'throwpoint': 'function <SNR>46__worker[12]..<SNR>45__publish[22]..<SNR>45__invoke_callback[6]..<lambda>2251[1]..<SNR>232_async_update_nodes[4]..<SNR>230_sync_save_cursor[3]..<SNR>230_sync_get_cursor_node[3]..<SNR>230_sync_get_cursor[3]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_get_cursor[8]..<SNR>231_', 'exception': 'Vim(return):E132: Function call depth is higher than ''maxfuncdepth'''}

**Comment by trailblazing** [comment]
vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 04 2020 10:58:20)
Included patches: 1-1948
Compiled by buildbot@vm1-a-mci-us
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
+clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
-dnd               +mouse             -sound             +xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: cc -c -I. -Iproto -DHAVE_CONFIG_H     -fstack-clash-protection -mtune=generic -O2 -pipe   -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: cc   -L. -Wl,-z,relro -Wl,-z,now     -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now     -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf   -lncursesw -lacl -lattr  -L/usr/lib -llua5.3 -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -Wl,-z,stack-size=2097152 -pthread  -L/usr/lib/perl5/core_perl/CORE -lperl -lm -lcrypt -lpthread -ldl  -L/usr/lib/python3.9/config-3.9-x86_64-linux-gnu -lpython3.9 -ldl -lm -lm  -lruby -lm

**Comment by lambdalisue** [comment]
No idea. Let me know

1. **MINIMAL** vimrc to reproduce
2. **MINIMAL** steps to reproduce

**Comment by trailblazing** [comment]
[vimrc.zip](https://github.com/lambdalisue/fern.vim/files/5885500/vimrc.zip)
Hello @lambdalisue ,
I packaged the "minimium" .vimrc file and the environment parameters. Hope it will help to reproduce the issue. 
Thank you for your patience :)

**Comment by lambdalisue** [comment]
This is not **minimal**. Start from the following to make a minimal vimrc and minimal steps to reproduce.

```vim
if exists('+compatible') && &compatible
  set nocompatible
endif

set packpath=
set runtimepath^=~/ghq/github.com/lambdalisue/fern.vim

filetype plugin indent on
syntax on
```

**Comment by trailblazing** [comment]
Hello @lambdalisue,
Thnaks for the guidance. 
I finally figured out the confict:
When I commented out line 191 of my .vimrc file,
`autocmd BufEnter * lcd %:p:h`
everything went back to normal.
`Fern . -drawer` works as expected.
Thank you for developing such a powerful tool :+1:

**Comment by victoriastuart** [comment]
I am also on occasion seeing this error, similar to `<SNR> ... get_cursor... :E132: Function call depth is higher than ''maxfuncdepth ...` but otherwise virtually identical as reported by the OP.

**Comment by lambdalisue** [comment]
Please investigate your vimrc first. Start from https://github.com/lambdalisue/fern.vim/issues/290#issuecomment-769325553
