### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by mrwonderfulness** [lambdalisue/fern.vim#293]
Are there issues with this plugin on MacOS?
I have it loaded with vim plug and when I run it in vim with `Fern .` at the command prompt I get a blank vim screen and this:

fern:///file:///Users/my_username;$

I also tried it with the -drawer option but still nothing.
Does it conflict with some other plugin or vim setting?

**Comment by lambdalisue** [comment]
I'm using macOS

> Does it conflict with some other plugin or vim setting?

Probably. Investigate the situation by using minimal vimrc like https://github.com/lambdalisue/fern.vim/issues/290#issuecomment-769325553

**Comment by lambdalisue** [comment]
No response. Close it

**Comment by omenking** [comment]
I just did a fresh install on my mac and this fern plugin refuses to load. I keep getting newtree instead:

.vimrc file

```
call plug#begin('~/.vim/plugged')

Plug 'sickill/vim-monokai'
Plug 'lambdalisue/fern.vim'

call plug#end()

autocmd VimEnter *
  \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall --sync | q
  \| endif
```  
  
<img width="252" alt="Screen Shot 2021-03-27 at 11 50 45 AM" src="https://user-images.githubusercontent.com/7776/112726220-aff17980-8ef2-11eb-8f2c-b61b4196a544.png">
