### ISSUE TITLE
When the floating window is opened from the drawer, resize is executed on the floating window

### ISSUE THREAD

**Issue by yuki-yano** [lambdalisue/fern.vim#294]
When nvim_open_win is executed in the drawer, the floating window that is created is resized.

It seems that the resize in BufEnter and BufLeave is also applied to the floating window.
See https://github.com/lambdalisue/fern.vim/blob/b461945bfe5dc08847c1dd4359659578a13d2e31/autoload/fern/internal/drawer/auto_resize.vim#L8-L9

You can reproduce this by running the following map in the drawer.
`nnoremap <buffer> z :call nvim_open_win(bufnr(''), v:true, {'relative': 'cursor', 'height': 100, 'width': 100, 'row': 1, 'col': 1})<CR>`

**Comment by lambdalisue** [comment]
It's kind correct behavior while `bufnr('')` is equivalent to `bufnr('%')`, that means `nvim_open_win(bufnr(''), ...)` opened fern buffer on the float window.

But, well, I think calling `fern#internal#drawer#resize()` on the float window is useless so I'll fix the behavior.
