### ISSUE TITLE
How to open fern on a parent directory of a current buffer and focus

### ISSUE THREAD

**Issue by quolpr** [lambdalisue/fern.vim#295]
I found in doc:

```
Or open fern on a parent directory of a current buffer by:

:Fern %:h
```

But how to also focus on the file of the previous buffer?

**Comment by quolpr** [comment]
> :Fern %:h -reveal=%

Doesn't work 😞️

**Comment by lambdalisue** [comment]
```
:Fern %:h -reveal=<C-r>=expand("%")<CR>
```

may work

**Comment by quolpr** [comment]
Nope. I checked, it doesn't. 
 
Btw, fern is so cool! I very like it; it is like a fresh breath after NerdTree. Thank you for all your efforts! 🙂️

**Comment by lambdalisue** [comment]
```
function! s:open() abort
  let path = expand("%")
  execute "Fern" shellescape(path)
endfunction
command FernOpen call s:open()
```

may?

btw

> Btw, fern is so cool! I very like it; it is like a fresh breath after NerdTree. Thank you for all your efforts! 🙂️

Thanks 🎉

**Comment by lambdalisue** [comment]
I got the situation. It's kind a bug of fern.

```
Fern autoload -reveal=autoload/fern.vim
```

Does not focus to `autoload/fern.vim` but

```
Fern autoload -reveal=fern.vim
```

Does. Correct command should be the first one so it's a bug.

**Comment by lambdalisue** [comment]
No. I was wrong. It's spec

> 	The {reveal} must be a relative path separated by "/" from the
>	specfied {url}.

https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L572

While fern is general purpose tree viewer, I should NOT consider "current working directory" so this behavior *won't* be fixed.


So, if you need to do that, you need to use an absolute path on `-reveal` option like:

```
:Fern %:h -reveal=%:p
```

**Comment by lambdalisue** [comment]
**The answer is**

```
:Fern %:h -reveal=%:p
```

https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L574-L575

**Comment by quolpr** [comment]
Thanks 👍️ It works as expected 🙂️
