### ISSUE TITLE
Have hidden files shown by default

### ISSUE THREAD

**Issue by MonstrousOgre** [lambdalisue/fern.vim#300]
I'd prefer not to use `hidden:set` or toggle it every time I open neovim.

Is there a way to have them displayed from the beginning? Or at least be able to execute an action when fern starts up?

**Comment by lambdalisue** [comment]
Please read the doc. https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L515

**Comment by MonstrousOgre** [comment]
> Please read the doc. https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L515

Thanks!

**Comment by MonstrousOgre** [comment]
@lambdalisue thanks!

**Comment by acro5piano** [comment]
For lua users:

```lua
vim.g["fern#default_hidden"] = 1
```
