### ISSUE TITLE
Fern %:h -reveal=% -drawer has a wrong focus

### ISSUE THREAD

**Issue by windwp** [lambdalisue/fern.vim#301]
I open file ./plugin/abcdef.vim then 

I run that command `Fern %:h -reveal=% -drawer`  and the focus is wrong.  

it should focus on abcdef.vim

**Comment by lambdalisue** [comment]
Because you are opening a fern buffer, the focus is moved on the fern buffer. Use `-stay` option to stay on the buffer you were in.

**Comment by windwp** [comment]
no i want that cursor is focus on line have file abcdef.vim on drawner

**Comment by lambdalisue** [comment]
Oops. Sorry you said "focus" thus I thought window focus.

Prob. https://github.com/lambdalisue/fern.vim/issues/295#issuecomment-774401337

**Comment by windwp** [comment]
Ok thanks
