### ISSUE TITLE
Delete directory (trash action)

### ISSUE THREAD

**Issue by gabrielbeauchemin** [lambdalisue/fern.vim#304]
Hello :) ,

When I try to delete a repository ("R" mapping with default mapping), it asks me to confirm with "Y[es]", and when I do, nothing happen, no error and the directory is still there. If I refresh with F5 or action reload:all, the directory is still there.

I don't know what I do wrong. I use nvim and I try to delete a repository which is inside nvim working directory, using Ubuntu 20.04. I have no problem to delete this file with command line or with an explorer.

Thank you for your work and your pluggin! :)

**Comment by lambdalisue** [comment]
Maybe an error message is showed. Check `:mes`.

If you are trying to use `trash` action, you need additional dependencies on Linux.
https://github.com/lambdalisue/fern.vim/wiki#additional-requirements

See [`:help fern-action-trash`](https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L1045) for more detail.

**Comment by gabrielbeauchemin** [comment]
Thanks for the answer. With :mes, I can find the error, but not too sure what to do with it. It is:

[fern] ERROR: vital: Asyc.File: trash() Not supported platform.

**Comment by gabrielbeauchemin** [comment]
Oh I followed your link and found a page to solve my issue: https://github.com/andreafrancia/trash-cli. I will try.

**Comment by gabrielbeauchemin** [comment]
I installed it on Debian with: "sudo apt install trash-cli" and it worked well, thank you :)
