### ISSUE TITLE
vim-airline buffer is flashing when opening fern

### ISSUE THREAD

**Issue by luathn** [lambdalisue/fern.vim#306]
I had this issue when open Fern: It's flashing airline buffer.
Could you look at this? Thank you!
![vim-buffer-flashing](https://user-images.githubusercontent.com/20609495/109444768-92a2ca00-7a70-11eb-8061-79cf8b320422.gif)

**Comment by lambdalisue** [comment]
I've no idea what you are talking about... Maybe you need to ask it on vim-airline instead?

**Comment by luathn** [comment]
@lambdalisue Thank you for your reply.
You can look at my gif. A buffer is created and close very quickly.
PS: I tested on lightline and did'nt see this bug. So maybe this is airline bug.

**Comment by lambdalisue** [comment]
I see. So it's like airline automatically close fern buffer, right?

It's prob a bug on airline side. Please close it once you've post an issue report on the airline side.

**Comment by luathn** [comment]
You're right. Thank you for your support :100:

**Comment by chrisbra** [comment]
I think this happens, because Fern does set `nobuflisted` and therefore airline updates the highlighting group, since the current buffer is not visible in the tabline. I wouldn't call this a bug in airline.

**Comment by lambdalisue** [comment]
@chrisbra 

Well, maybe I mis-understood the situation. I've no idea why you are talking about highlighting group...

My understanding is "when user open a fern buffer with airline, the fern buffer is open and closed quickly and peridodically somehow".

**Comment by chrisbra** [comment]
well, the issue title is about buffer flickering. So I suppose this is what is showing on the screen capture. the User repeatedly hitting a key, that triggers showing/disabling fern.vim. Which causes vim-airline to re-create some highlighting groups for the tabline, which cause a screen redraw, which make it flicker. 

vim-airline is just a tabline/statusline plugin. It should never just open/close some buffer/window

**Comment by lambdalisue** [comment]
> the User repeatedly hitting a key

Got it. That's what I mis-understood.

> vim-airline is just a tabline/statusline plugin. It should never just open/close some buffer/window

That's why I thought it's a bug. Sorry for the misinterpretation.
