### ISSUE TITLE
Vim search (next / previous, i.e. n / Shift-N) not working in fern.vim drawer

### ISSUE THREAD

**Issue by victoriastuart** [lambdalisue/fern.vim#307]
Hello: I just (yesterday) started using `fern.vim`, as `NERDtree` was too slow opening large directories.

[`netrw` opened those large directories efficiently; however, while I appreciate the native simplicity of `netrw`, it lacks polish and features, e.g. decent bookmarking; other issues, e.g. navigation.]

In `NERDtree`, with a open directory I was able to [edit: using `/`-search in `Vim`] search a term,  using the standard `Vim` mappings `n` | `Shift-N` to navigate through those matches.

How can I regain that search functionality in `fern.vim`?

My `~/.vimrc` entries:

```vim
let g:fern#disable_default_mappings   =  1
let g:fern#disable_drawer_auto_quit   = 1
let g:fern#disable_viewer_hide_cursor = 1

noremap <silent> <C-n> :Fern . -drawer -width=75 -toggle<CR><C-w>=
noremap <silent> <Leader>f :Fern . -drawer -reveal=% -width=75<CR><C-w>=
noremap <silent> <Leader>. :Fern %:h -drawer -width=75<CR><C-w>=

function! FernInit() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-expand-collapse)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:select)<ESC><BAR>:FernDo close<CR>",
        \   "\<Plug>(fern-action-expand)",
        \   "\<Plug>(fern-action-collapse)",
        \ )
  nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> <2-LeftMouse> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> m <Plug>(fern-action-mark:toggle)j
  nmap <buffer> N <Plug>(fern-action-new-file)
  nmap <buffer> K <Plug>(fern-action-new-dir)
  nmap <buffer> B <Plug>(fern-action-save-as-bookmark)
  nmap <buffer> T <Plug>(fern-action-trash)
  nmap <buffer> V <Plug>(fern-action-move)
  nmap <buffer> R <Plug>(fern-action-rename)
  nmap <buffer> s <Plug>(fern-action-open:split)
  nmap <buffer> v <Plug>(fern-action-open:vsplit)
  nmap <buffer> r <Plug>(fern-action-reload)
  nmap <buffer> <nowait> d <Plug>(fern-action-hidden:toggle)
  nmap <buffer> <nowait> < <Plug>(fern-action-leave)
  nmap <buffer> <nowait> > <Plug>(fern-action-enter)
endfunction

augroup FernEvents
  autocmd!
  autocmd FileType fern call FernInit()
augroup END

" NerdTREE-like presentation:
let g:fern#mark_symbol                       = '●'
let g:fern#renderer#default#collapsed_symbol = '▷ '
let g:fern#renderer#default#expanded_symbol  = '▼ '
let g:fern#renderer#default#leading          = ' '
let g:fern#renderer#default#leaf_symbol      = ' '
let g:fern#renderer#default#root_symbol      = '~ '

" Bookmarks:
let g:fern#mapping#bookmark#disable_default_mappings = 0
let g:fern#scheme#bookmark#store#file = "~/.vim/fern-bookmark.json"
```

**Comment by lambdalisue** [comment]
I'm sorry but I've no idea about

> In NERDtree, with a open directory I was able to search a term, and use n | Shift-N to navigate through those matches.

Could you explain the feature with some screencast or screenshots?

Or do you just talking about Vim's search feature by hitting `/` or `?`?

**Comment by victoriastuart** [comment]
The latter: open the `fern.vim` drawer, then search (Vim: `/`) for a string.  In a document, `n/N` will find the next/previous match.  I'm not seeing that in the `fern` drawer.

I'll do a screen capture later and amend this comment.

**Comment by lambdalisue** [comment]
![Kapture 2021-03-04 at 12 02 20](https://user-images.githubusercontent.com/546312/109905022-7c4f7500-7ce1-11eb-9bd8-5d3b4ea6eead.gif)

It seems search works as expect in my environment. Note that `N` is mapped to "New file" in default thus `N` does not work unless you disable the mapping.

Please make a minimal vimrc and minimal steps to reproduce. Starts from the following vimrc

```vim
if exists('+compatible') && &compatible
  set nocompatible
endif

if has('nvim')
  set runtimepath^=~/.vim
  set runtimepath+=~/.vim/after
  set packpath^=~/.vim
endif

" Specify fern.vim directory here
set runtimepath+=~/fern.vim

packloadall

filetype plugin indent on
syntax on

echomsg "Custom vimrc has loaded"
```

**Comment by victoriastuart** [comment]
Hi again - thank you for your response, appreciated. I commented out the `nmap <buffer> N <Plug>(fern-action-new-file)` line and looked around my `.vimrc` but didn't see anything of note.

With that change, in the `fern.vim` drawer I can do a `/` search as in a regular buffer (and the `NERDtree` buffer) and when I press `n` to find the next match, it goes to that line and stays there, even if there are more matches in following lines.

If there are gaps (non-matched lines) between search results, I can `j` below the current match, then `n` again takes me to (only) the next match and stays there (even if more matches, below).

The reverse search, `N`, works normally.

Again, this is only in the `fern.vim` buffer / drawer.

I also tried your minimal `.vimrc` with the `fern.vim` settings but it wouldn't work properly -- missing other things apparently to make this work.  Frankly, I'm not interested in pursuing that approach, as if needed I'll return to `NERDtree` and use `netrw` for opening directories with large (100s / 1000s) files.

**Comment by lambdalisue** [comment]
Well, **"I"** need minimal vimrc and steps to reproduce your situation. Otherwise I cannot fix or help. That's why I'm asking you to start from that minimal vimrc.

Anyway, it's fine if you go back to NERDTree or netrw or whatever. It's up to you. Please close this issue then.

**Comment by Shougo** [comment]
You can use any other file manager plugins.
They are free to use and no warranty.

**Comment by lambdalisue** [comment]
Maybe the following helps?

```
let g:fern#disable_viewer_smart_cursor = 1
```

**Comment by victoriastuart** [comment]
Adding

`let g:fern#disable_viewer_smart_cursor = 1`

to the `minimal .vimrc"` (comments below) PARTIALLY solved the /-search issue:

* `n` (forward) worked;
* `N` (reverse search) brought up the `New file: ` dialog (rather than searching).

HOWEVER, adding

`let g:fern#disable_viewer_smart_cursor = 1`

to my full `~/.vimrc` restored a properly working `Vim` /-search (`n`: forward | `N`: reverse).

---

Here is the issue / frustration I had with the "minimal" `.vimrc` (note the number of paths to identically-named, yet different, `fern.vim` files).

```vim
if exists('+compatible') && &compatible
  set nocompatible
endif

if has('nvim')
  set runtimepath^=~/.vim
  set runtimepath+=~/.vim/after
  set packpath^=~/.vim
endif

" Specify fern.vim directory here
" set runtimepath+=~/fern.vim

" In sequential order
"   (re: `find` command, `fern.vim`, `fern` installed via `vim-plug):
"   Restart Vim to reload.

" YES:
set runtimepath+=/home/victoria/.vim/plugged/fern.vim
"   ... BUT no Vim /-search `n' only finds / stalls at first match,
"   and `N` calls 'New file: '.

" NOPE ('E492: Not an editor command: Fern .'):
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/autoload/fern.vim
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/ftplugin/fern.vim
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/plugin/fern.vim
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/autoload/fern/internal/command/fern.vim
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/autoload/fern.vim
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/autoload/vital/fern.vim
" set runtimepath+=/home/victoria/.vim/plugged/fern.vim/autoload/vital/_fern.vim

packloadall

filetype plugin indent on
syntax on

echomsg "Custom vimrc has loaded"

" TEST:
" :Fern .

" `:buffers` to list buffers

" [victoria@victoria ~]$ pwd
"   /home/victoria
" [victoria@victoria ~]$ find . -iname  '*fern.vim'
"   ./.vim/plugged/fern.vim
"   ./.vim/plugged/fern.vim/ftplugin/fern.vim
"   ./.vim/plugged/fern.vim/plugin/fern.vim
"   ./.vim/plugged/fern.vim/autoload/fern/internal/command/fern.vim
"   ./.vim/plugged/fern.vim/autoload/fern.vim
"   ./.vim/plugged/fern.vim/autoload/vital/fern.vim
"   ./.vim/plugged/fern.vim/autoload/vital/_fern.vim
" [victoria@victoria ~]$
```

**Comment by lambdalisue** [comment]
> N (reverse search) brought up the New file: dialog (rather than searching).

`N` is mapped to `new-file` in default though.

Anyway, it seems that setting solved the issue. Good.

**Comment by victoriastuart** [comment]
Thank you for your help, earlier.  I did not intend to appear ungrateful.
Sincerely, ...
