### ISSUE TITLE
Open file without focusing on it

### ISSUE THREAD

**Issue by gabrielbeauchemin** [lambdalisue/fern.vim#310]
Hello :) ,

Is there a way to open a file without focusing on it with a single key map? 

Sometimes, I just want to have a preview of what the file is, but I would like my focus to stay on the tree files. In this case I need to open the file, and then to change the focus back to fern to continue navigating the files. I wonder if I can do that in one key map?

Similarly, I wonder if it is possible to open a file and close the fern tree files with a single key map?

Thanks!

**Comment by lambdalisue** [comment]
Use `<C-w><C-p>` for getting buck to the previous window.

Check this tips to close the fern.
https://github.com/lambdalisue/fern.vim/wiki/Tips#close-fern-after-open

**Comment by gabrielbeauchemin** [comment]
Ok thank you I close the issue. I would like to suggest to add them to default open:{action} as they are very practical. Thanks!
