### ISSUE TITLE
Opens fern-rep buffer in a horizontal split, how to avoid it showing up?

### ISSUE THREAD

**Issue by reportaman** [lambdalisue/fern.vim#311]
Since some commit, ``Fern .`` or perhaps something like ``Fern . -drawer`` also opens a ``fern-rep`` buffer in a new split (split made in last focussed buffer). How can I disable that from happening? When I had first installed this plugin, it didn't do anything like that (I just want to see drawer, for instance, when I run ``Fern . -drawer``) Thanks!

Here's a GIF that shows the problem:

![Screen Recording 2021-03-13 at 7 49 20 PM](https://user-images.githubusercontent.com/71736629/111056670-c6e59580-8435-11eb-8522-a631327aa819.gif)

**Comment by lambdalisue** [comment]
We have no idea about `fern-rep`. Probably, that comes from your configuration.

See https://github.com/lambdalisue/fern.vim/issues/290#issuecomment-769325553 to try fern.vim with minimal vimrc.

**Comment by reportaman** [comment]
@lambdalisue Narrowed down to the following minimal configuration. You should be able to reproduce this behavior with it.

```
if exists('+compatible') && &compatible
  set nocompatible
endif

set packpath=
set runtimepath^=~/.vim/plugged/fern.vim/
filetype plugin indent on
syntax on

augroup nofoldonopen
    autocmd!
    autocmd BufWinEnter * normal zR
augroup END
```

**Comment by lambdalisue** [comment]
Because `R` is mapped to `rename` action. Use `normal!` instead like

```
augroup nofoldonopen
    autocmd!
    autocmd BufWinEnter * normal! zR
augroup END
```

**Comment by reportaman** [comment]
@lambdalisue Thanks!
