### ISSUE TITLE
Enhancement: Move cursor to column 0 when Fern buffer is focussed

### ISSUE THREAD

**Issue by reportaman** [lambdalisue/fern.vim#312]
When Fern buffer is reopened, the cursor is at the correct line number, but in column-1 instead of column-0. Given column 1 can have file icon, depending on cursor properties the icon can look hidden or ambiguous.

The following GIF shows that happens:
![Screen Recording 2021-03-13 at 7 59 42 PM](https://user-images.githubusercontent.com/71736629/111056959-8dfaf000-8438-11eb-935e-a4c4f2b04067.gif)

**Comment by lambdalisue** [comment]
Because this kind of unstable behavior, I'm actually planning to remove the first column.
https://github.com/lambdalisue/fern.vim/issues/308

If you care about that, use Neovim and `let s:fern#smart_cursor = 'hide'`

**Comment by lambdalisue** [comment]
#314 has merged. Now use the following instead

```
let g:fern#hide_cursor = 1
```

**Comment by reportaman** [comment]
@lambdalisue Thanks!
