### ISSUE TITLE
Enhancement: Case-insensitive and interleaved sort of filenames and directories

### ISSUE THREAD

**Issue by reportaman** [lambdalisue/fern.vim#313]
At present, if there are four directories with names:``aaa_d,AAA_d,bbb_d,BBB_d,ccc_d,CCC_d``, and four files with names: ``aaa_f,AAA_f,bbb_f,BBB_f,ccc_f,CCC_f``, they appear like this:

```
AAA_d
BBB_d
CCC_d
aaa_d
bbb_d
ccc_d
AAA_f
BBB_f
CCC_f
aaa_f
bbb_f
ccc_f
```

Ideally, files and directories will appear in this order:

```
AAA_d
AAA_f
aaa_d
aaa_f
BBB_d
BBB_f
bbb_d
bbb_f
CCC_d
CCC_f
ccc_d
ccc_f
```

**Comment by lambdalisue** [comment]
Prob, this is what you want. https://github.com/lambdalisue/fern-comparator-lexical.vim
