### ISSUE TITLE
Example on how to get information on node under cursor, like its full path

### ISSUE THREAD

**Issue by reportaman** [lambdalisue/fern.vim#315]
How can one get information on node under the cursor in Fern drawer? I would like to get the full path of the node, and potentially also other information like is it a directory or a file? I did skim through your developer page, but couldn't understand how to do something like this.

**Comment by lambdalisue** [comment]
For...?

1. For just check, use `debug` action
2. For plugin development, read `fern-develop-helper` and actual codes

**Comment by reportaman** [comment]
@lambdalisue For extending the functionality of Fern, I couldn't understand how to use it from the develop-helper. For instance, this  ``fern-develop-helper.sync.get_cursor_node()`` looks promising, but when I try to do something like ``call fern-develop-helper.sync.get_cursor_node()``, I get error ``E107: Missing parentheses: fern-develop-helper.sync.get_cursor_node()``

**Comment by lambdalisue** [comment]
> A helper instance is used for writing features in mappings. Developers can
pass a helper instance to the first argument of functions by calling the
function with |fern#helper#call()| or create a new helper instance of the
current buffer by calling |fern#helper#new()|.
