### ISSUE TITLE
Fern and session restore

### ISSUE THREAD

**Issue by iamvoidcoder** [lambdalisue/fern.vim#318]
Neovim 0.4.4, MacOS 11.2.3

When restoring a saved nvim session (nvim -S) which includes an active Fern buffer I'm getting this funny message at the bottom of empty nvim window: 

```
"Tinker/imx8/sa998/imx-scfw/src/scfw_export_mx8/Makefile" 519L, 13943C
"fern://drawer:1/file:///Users/vcd/Tinker/imx8/sa998/imx-scfw;$" [Not edited] --No lines in buffer--
Press ENTER or type command to continue
```

After pressing Enter the session resumes with Fern drawer buffer on the left as it should. Is this a known issue?

**Comment by lambdalisue** [comment]
That is Vim's feature. If you'd love to disable that, see https://github.com/lambdalisue/fern.vim/issues/291#issuecomment-781086250

**Comment by iamvoidcoder** [comment]
Thanks
