### ISSUE TITLE
how to expand full folder tree

### ISSUE THREAD

**Issue by amit777** [lambdalisue/fern.vim#320]
Hi I implemented the collapse expand tip as follows:
```viml
  " collapse expand"
  nmap <buffer><expr>
      \ <Plug>(fern-my-expand-or-collapse)
      \ fern#smart#leaf(
      \   "\<Plug>(fern-action-collapse)",
      \   "\<Plug>(fern-action-expand)",
      \   "\<Plug>(fern-action-collapse)",
      \ )

  nmap <buffer><nowait> o <Plug>(fern-my-expand-or-collapse)
```
Is it possible to map "O" (capital O) to expand/collapse the entire folder tree under the cursor?  Like a recursive expand?

btw, what an awesome project. I stumbled upon it when I was playing around with NerdTree and then Coc-Explorer.  It seems like your way is the neatest.

**Comment by amit777** [comment]
btw, what I'm looking for is the equivalent of NerdTree's "O" action..

**Comment by lambdalisue** [comment]
Unfortunately no. And I'm not going to implement it because it's quite difficult while fern is asynchronous.

**Comment by lambdalisue** [comment]
Close this while I'm not going to implement it, sorry.
