### ISSUE TITLE
Reveal doesn't work when there are too many files in the same folder?

### ISSUE THREAD

**Issue by nyngwang** [lambdalisue/fern.vim#323]
My mapping:

    nnoremap <nowait><silent><expr> ;
            \ (&readonly<bar><bar>&filetype=="fern"<bar><bar> &filetype==""? "" : ":w\<CR>")
            \ .":Fern %:p:h:h -drawer -width=36 -toggle -reveal=%\<CR>"

How to reproduce: 

I cloned many projects on my `Desktop/` folder and to reproduce this error just goto a folder contains the target file, say `test.c` open it and type `;`, the cursor will just go topmost(as first pic.) in the drawer, no focus the target file. In other situation (folder with no too many files) there is no such problem.

<img src="https://user-images.githubusercontent.com/24765272/113502732-c89c0800-9560-11eb-93d0-25a098e4b8b6.png" width="500"/>

<img src="https://user-images.githubusercontent.com/24765272/113502862-511aa880-9561-11eb-96ab-0d5372217207.png" width="150"/>

**Comment by lambdalisue** [comment]
It's quite hard to reproduce the issue you've faced with your explanation. Please provide the followings

1. **MINIMAL** vimrc
2. **MINIMAL** steps

I'm sorry for emphasizing **MINIMAL** but usually people gives me a part of them vimrc instead of minimal vimrc though.
