### ISSUE TITLE
open:system doesnt work in Neovim

### ISSUE THREAD

**Issue by GGCristo** [lambdalisue/fern.vim#324]
The action ``open:system`` doesn't work in Neovim bit it does in Vim.
I have tried 'x' and the ``open:system`` action
Sorry for not creating a more detailed report I am very busy lately with college, if you can't reproduce it I will create a more elaborated one.

I am using one of the latest version of Neovim (0.5.0), compiled.

It works fine with PDF (okular to be more specific).

**Comment by lambdalisue** [comment]
I am using Neovim 0.5.0 (cc1851c9f) on macOS Catalina and `open:system` works properly.

**Comment by GGCristo** [comment]
I think it's a  KDE problem with some programs, because the browser can't open discover (graphical package manager) with ``xdg-open``, so I am going to close it. If  I discover that fern can do something about it, or it's related, I will reopen it.
