### ISSUE TITLE
How to close Fern UI just after go to file?

### ISSUE THREAD

**Issue by przepompownia** [lambdalisue/fern.vim#325]
Currently I have a custom mapping with

```vim
function! s:tabDrop() abort
  let l:helper = fern#helper#new()
  let l:node = l:helper.sync.get_cursor_node()

  execute 'tab drop ' . l:node._path
endfunction
```
To close Fern drawer just after jump to selected file I can change it to 
```vim
  let l:bufnr = bufnr()

  execute 'tab drop ' . l:node._path
  execute l:bufnr . 'bunload'
```
but it would be better to close the drawer by some helper method to avoid such workarounds. 

Please also allow to autoclose Fern UI after successfully execution each standard action that causes jumping from Fern to another buffer associated with a node (like `open*`).

**Comment by lambdalisue** [comment]
Maybe https://github.com/lambdalisue/fern.vim/wiki/Tips#close-fern-after-open

**Comment by ismay** [comment]
I was wondering the same thing. I've taken a look at the example you've linked @lambdalisue, but I'm wondering how to apply it to this kind of mapping:

```vim
function! s:init_fern() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-expand-collapse)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:select)",
        \   "\<Plug>(fern-action-expand)",
        \   "\<Plug>(fern-action-collapse)",
        \ )
  nmap <buffer> l <Plug>(fern-my-open-expand-collapse)
endfunction

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
```

How would you recommend integrating your linked example with settings like the one above?

**Comment by lambdalisue** [comment]
I haven't tested but something like

```vim
function! s:init_fern() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-expand-collapse)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:select)",
        \   "\<Plug>(fern-action-expand)",
        \   "\<Plug>(fern-action-collapse)",
        \ )
  nmap <buffer> l <Plug>(fern-my-open-expand-collapse)

  nmap <buffer><silent> <Plug>(fern-action-open-and-close)
      \ <Plug>(fern-action-open)
      \ <Plug>(fern-close-drawer)
  nmap <buffer> <CR> <Plug>(fern-action-open-and-close)

endfunction

nnoremap <Plug>(fern-close-drawer) :<C-u>FernDo close -drawer -stay<CR>

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
```

It's more like question for Vim itself so please use stackoverflow or whatever instead for more details.

**Comment by ismay** [comment]
> It's more like question for Vim itself so please use stackoverflow or whatever instead for more details.

You're absolutely right, sorry about that. My laziness got the better of me 😅.

**Comment by przepompownia** [comment]
I need some free time to test and response. Please do not close this issue yet.

**Comment by przepompownia** [comment]
- mappings with compound `<Plug>` RHS do not work for me. I still use the workaround.
- even if they work, it still need to be defined separately for open, split, vsplit etc.

**Comment by lambdalisue** [comment]
> mappings with compound <Plug> RHS do not work for me. I still use the workaround.

Unfortunately, "do not work" tells nothing so I cannot help. Please make a minimal vimrc and minimal steps to reproduce the situation and explain what is your expectation.

> even if they work, it still need to be defined separately for open, split, vsplit etc.

This is by design. I'm not going to change that while I don't think it's too difficult to define that.

**Comment by przepompownia** [comment]
Obviously, it is neither difficult nor worth big work. It would be only for convenience and reduce repetition in config file. The second assumption allows to close this issue especially the first problem is not Fern specific. 

Independently, I found that I used `nnoremap` with `<Plug>` in RHS. 
```vim
nmap <Plug>(x) :echom 'x'<CR>
nmap <Plug>(y) :echom 'y'<CR>

nnoremap ,xx 
	\ <Plug>(x)
	\ <Plug>(y)
nmap ,xy 
	\ <Plug>(x)
	\ <Plug>(y)
```
so `,xx` did not work as expected. 

Thanks!

**Comment by przepompownia** [comment]
Your proposition will be not usable for `fern-action-open:tabedit` because `FernDo` acts on the current tab, but I have defined [custom action](https://github.com/przepompownia/vim-arctgx/blob/master/autoload/fern/mapping/arctgx.vim#L8-L21) for `tab drop` and I usually do not use `tabedit`.
