### ISSUE TITLE
How to navigate to parent directory (..)?

### ISSUE THREAD

**Issue by cherrry** [lambdalisue/fern.vim#326]
Once I enter a child directory in fern drawer, how can I navigate back to its parent?

e.g.
```
foo
|- bar/ <- press <cr>
```
then it becomes:
```
bar
|- ../ <- There isn't a ../ to get back
|- bar1

**Comment by lambdalisue** [comment]
Prob `<C-h>` (or `<Backspace>`).

You can find that by hitting `?` and check mapping to `leave` (if you have not customized it) like:

![CleanShot 2021-04-10 at 16 16 22](https://user-images.githubusercontent.com/546312/114261962-3c825880-9a18-11eb-8c4f-7aab20711eac.png)

**Comment by cherrry** [comment]
Thanks very much, didn't notice `leave` means leaving the current directory.
