### ISSUE TITLE
How to make use of tcd:root properly?

### ISSUE THREAD

**Issue by windowsrefund** [lambdalisue/fern.vim#327]
Hello,

I'm pretty excited about this software and have been trying to configure it by reading through the TIPS section of the wiki, etc. One issue I'm not understanding at all is how to have fern automatically set the root to a directory I enter? There are a few sections of that wiki page that speak to tcd:root but the docs are written in a way that assumes the reader has a solid understanding of al the terminology and behavior in advance. As a new user, I don't have that understanding.

Assuming Fern (in drawer mode) is shows the following
```

foo
|+ bar/ 
|+ baz/
```
I press <CR> on the bar/ directory which has a few files in it (a, b, c)

My desired end state would be to see Fern show the following:

```
bar
 |  a
 |  b
 |  c
```
My Enter key is mapped like so via the initialization function

```
function! s:init_fern() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-expand-collapse)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:select)",
        \   "\<Plug>(fern-action-expand)",
        \   "\<Plug>(fern-action-collapse)",
        \ )
  nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)
endfunction
```

**Comment by lambdalisue** [comment]
Well, I'm sorry but I don't get your desire...

You've mentioned `tcd:root` thus I guessed that you would like to perform `tcd` on the root node after `enter` or `leave` action, right? Then what you need to refer is ["Perform `tcd` on the root node after `enter` or `leave` action](https://github.com/lambdalisue/fern.vim/wiki/Tips#perform-tcd-on-the-root-node-after-enter-or-leave-action) section. And the `s:init_fern()` function would be

```vim
function! s:init_fern() abort
  " Define mapping (action) which perform `tcd:root` after `enter`
  nmap <buffer> <Plug>(fern-my-enter-and-tcd)
      \ <Plug>(fern-action-enter)
      \ <Plug>(fern-wait)
      \ <Plug>(fern-action-tcd:root)

  " Define mapping (action) which perform `tcd:root` after `leave`
  nmap <buffer> <Plug>(fern-my-leave-and-tcd)
      \ <Plug>(fern-action-leave)
      \ <Plug>(fern-wait)
      \ <Plug>(fern-action-tcd:root)

  " The following mappings respect fern's default one
  nmap <buffer> <CR> <Plug>(fern-my-enter-and-tcd)
  nmap <buffer> <BS> <Plug>(fern-my-leave-and-tcd)
endfunction
```

Let me know if I mis-understood your desire.

> There are a few sections of that wiki page that speak to tcd:root but the docs are written in a way that assumes the reader has a solid understanding of al the terminology and behavior in advance. As a new user, I don't have that understanding.

Please feel free to improve that tips.

**Comment by windowsrefund** [comment]
Very much appreciated! :) Thank you.
