### ISSUE TITLE
Different ways to open fern at startup

### ISSUE THREAD

**Issue by SciPhy-Two** [lambdalisue/fern.vim#328]
I am quite new to nvim and I had initiialy used NERDTree. After switching to fern, one of the features I miss is the startup options. Could you give me the settings which will act equivalent  to : 

```vim
" Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
```
I have been trying various options myself but nothing's working. I saw [this](https://github.com/lambdalisue/fern.vim/wiki/Tips#start-fernvim-on-vim-startup-with-a-particular-directoryl) in fern wiki but it doesn't quite do the job. 

It would also be great if examples from [this NERDTree section](https://github.com/preservim/nerdtree#how-do-i-open-nerdtree-automatically-when-vim-starts) is provided in the 'Tips' page.

**Comment by lambdalisue** [comment]
> I have been trying various options myself but nothing's working. I saw this in fern wiki but it doesn't quite do the job.

For me, it did the job. What do you expect? Please explain it as a step by step procedure.
Like you are not familiar with fern, I'm not familiar with NERDTree.

> It would also be great if examples from this NERDTree section is provided in the 'Tips' page.

Wiki is opened for anyone so you can write that 👍

**Comment by SciPhy-Two** [comment]
Oh, what I really meant was that NERDTree has given examples for :

1. Start NERDTree and leave the cursor in it.
2. Start NERDTree and put the cursor back in the other window.
3. .
4. .
5. etc
 Like that, the option I want is ` Start NERDTree. If a file is specified, move the cursor to its window.` in fern. [This](https://github.com/lambdalisue/fern.vim/wiki/Tips#start-fernvim-on-vim-startup-with-a-particular-directoryl) provides info on how to open a specific directoy when nvim is open. It doesn't change to the correct path when a file is opened.

**Comment by lambdalisue** [comment]
I haven't tested and not sure but the following might help?

```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * ++nested Fern -drawer %:h | if argc() > 0 || exists("s:std_in") | wincmd p | endif
```
