### ISSUE TITLE
Clean up clutter by hiding line number column/gutter

### ISSUE THREAD

**Issue by abdl-dev** [lambdalisue/fern.vim#336]
I have gone through the docs and can't seem to find anything that allows me to disable the line number gutter (while still having it enabled in editing buffers. I'm coming from NERDTree where the directory tree window does not have a number column, so having the extra column makes it hard to fit the same number of splits per screen.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Tips#how-to-customize-fern-buffer

You can customize the fern buffer. Fern does not touch the `number` option by itself while I think it's the user's choice.

**Comment by abdl-dev** [comment]
Ah, I see, thanks! I originally looked for a toggle option instead of a user-defined command.
