### ISSUE TITLE
Question: Is there a way for an open Fern drawer to follow cwd

### ISSUE THREAD

**Issue by thecontinium** [lambdalisue/fern.vim#338]
Hi 

When I cd in a buffer and I have the Fern drawer open I would like the root of the Fern drawer to change to the cwd of the buffer. Is this possible ?

Perhaps the way to do this is to write an autocmd on DirChanged event to call `Fern . -stay -drawer `but I only want to do this if the drawer is open. Is there a way to test if the drawer is open ?

Cheers.

**Comment by lambdalisue** [comment]
It's a bit tricky but 

```
:FernDo Fern\ .\ -drawer\ -stay -drawer -stay
```

might do what you want.

**Comment by thecontinium** [comment]
Hi - Thanks for that.

From an interactive session this works well but if I move it to an autocmd like this:

`autocmd user_events DirChanged * FernDo Fern\ .\ -drawer\ -stay -drawer -stay`

and with an open Fern drawer and a change of directory in another buffer results in the following:

1. The Fern drawer buffer goes blank.
2. If I go in the Fern drawer buffer and refresh ( <Plug>(fern-action-redraw) ) the buffer it shows correctly
3. When I return to the original buffer the Fern buffer goes blank again !

Thanks

**Comment by lambdalisue** [comment]
You need `++nested` probably.

**Comment by thecontinium** [comment]
This seems to do the trick:

`:autocmd user_events DirChanged * ++nested execute printf('FernDo Fern\ %s\ -drawer\ -stay -drawer -stay',deepcopy(v:event).cwd)`

**Comment by lambdalisue** [comment]
Prob, you don't need `deepcopy` while you don't change the value of `v:event`

**Comment by lambdalisue** [comment]
Please close the issue if your problem is solved.

**Comment by thecontinium** [comment]
Thanks
