### ISSUE TITLE
fern#hide_cursor not working for Macvim (GUI Vim)

### ISSUE THREAD

**Issue by jlxz** [lambdalisue/fern.vim#339]
Hi, 
The way hide_cursor functionality is implemented in cursor.vim file, only works for Vim executed on a terminal, but it doesn't work for other Vim GUIs such as Macvim. It would work if the GUI fix would be applied not only for nvim but for other VIM GUIs.

A possible solution could be changing line 12 in cursor.vim with this:
if has('nvim') || has('gui_running') 

Thanks.

**Comment by lambdalisue** [comment]
@jlxz Please try #340

**Comment by jlxz** [comment]
Hi,

Thanks @lambdalisue it works. I have tested it in Macvim. Once its merged with the main branch I will be able to test it in GVim on Windows. 

Thank you very much.
