### ISSUE TITLE
Is it possible to open in the drawer mode by default?

### ISSUE THREAD

**Issue by your-diary** [lambdalisue/fern.vim#341]
I prefer the drawer mode so I'd be glad if I can open Fern in the drawer mode just by `:Fern .` or `:e .` (if `fern-hijack.vim` is used). Is it possible?

**Comment by lambdalisue** [comment]
Fern does not provide such a feature. Please define your own command instead.

**Comment by your-diary** [comment]
Thank you. I'll do that.
