### ISSUE TITLE
How to change the color of the leftmost column?

### ISSUE THREAD

**Issue by your-diary** [lambdalisue/fern.vim#342]
By default, the leftmost column of the Fern window is highlighted. This is where `*` is displayed when you mark a file.

How to change the color of the column? I tried setting `ctermbg=100` for all of the highlight group explained in `:help fern` with no success:

```
highlight FernSpinner ctermbg=100
highlight FernMarkedLine ctermbg=100
highlight FernMarkedText ctermbg=100
highlight FernRootSymbol ctermbg=100
highlight FernRootText ctermbg=100
highlight FernLeafSymbol ctermbg=100
highlight FernLeafText ctermbg=100
highlight FernBranchSymbol ctermbg=100
highlight FernBranchText ctermbg=100
highlight FernWindowSelectIndicator ctermbg=100
highlight FernWindowSelectStatusLine ctermbg=100
```

**Comment by your-diary** [comment]
<img width="321" alt="Screen Shot 2021-05-27 at 23 53" src="https://user-images.githubusercontent.com/58146437/119848816-16246800-bf47-11eb-945c-bd646f28bdb5.png">

**Comment by lambdalisue** [comment]
That's the sign column that the fern does not touch the highlight.

**Comment by your-diary** [comment]
Thank you for your suggestion. The answer was `:highlight SignColumn ctermbg=100`.
