### ISSUE TITLE
Help needed: How do I change statusline of inactive buffer to hide fern's buffer name?

### ISSUE THREAD

**Issue by geoyws** [lambdalisue/fern.vim#344]
<img width="428" alt="Screenshot 2021-06-03 at 10 44 59 AM" src="https://user-images.githubusercontent.com/1738396/120578797-f74b3780-c458-11eb-9384-bb8c1fdd9cbf.png">

This only happens when my focus is on another window.
Thanks very much!

**Comment by lambdalisue** [comment]
That's end of fern's buffer name and nothing wrong on fern side I think. Probably you need to ask how to change statusline of inactive buffer and that's absolutely not reated to fern itself.

**Comment by geoyws** [comment]
Apologies, let me change my question title.

**Comment by geoyws** [comment]
Apologies again, I managed to figure it out!

Had a look in the [options](https://github.com/itchyny/lightline.vim/blob/master/doc/lightline.txt) section and found that I could omit parts of the status bar.

```vimrc
let g:lightline = {
\ 'colorscheme': 'gruvbox',
\ 'inactive': {
\   'left': [ [] ],
\   'right': [ [ 'lineinfo' ],
\            [ 'percent' ] ] },
\ 'active': {
\   'left': [ [ 'mode', 'paste' ],
\             [ 'cocstatus', 'currentfunction', 'readonly', 'responsiveAbsolutePath', 'modified' ] ]
\ },
\ 'component_function': {
\   'cocstatus': 'coc#status',
\   'currentfunction': 'CocCurrentFunction',
\   'responsiveAbsolutePath': 'ResponsiveAbsolutePath'
\ },
\}
```

**Comment by lambdalisue** [comment]
So closable?

**Comment by SciPhy-Two** [comment]
I had this same issue with galaxyline. But I fixed after changing the config a lot. So, can't really point out the exact issue. However, it might have to do with BufType which needs to replaced with filetype. Then 'FERN' will be shown instead. Here's my relevant part from galaxyline config

```
gls.short_line_left[1] = {
  BufferType = {
    provider = 'FileTypeName',
    separator = ' ',
    separator_highlight = {'NONE',colors.black},
    highlight = {colors.blue,colors.black,'bold'}
  }
}

gls.short_line_left[2] = {
  SFileName = {
    provider =  'SFileName',
    condition = condition.buffer_not_empty,
    highlight = {colors.white,colors.black,'bold'}
  }
}

gls.short_line_right[1] = {
  BufferIcon = {
    provider= 'BufferIcon',
    highlight = {colors.white,colors.black}
  }
}
```

**Comment by geoyws** [comment]
Yup closeable!
