### ISSUE TITLE
tmux-navigator issue

### ISSUE THREAD

**Issue by timsofteng** [lambdalisue/fern.vim#345]
Hello. When i use `vim-tmux-navigator` plugin I expect to move from window to window with `ctrl-h/j/k/l`. Unfortunately `fern` doesn't  support this shortcuts.

https://github.com/christoomey/vim-tmux-navigator

**Comment by lambdalisue** [comment]
Well, so is it **fern's** issue? I even don't really understand what did you mean by "`fern` doesn't support this shortcuts."

**Comment by timsofteng** [comment]
> Well, so is it **fern's** issue? I even don't really understand what did you mean by "`fern` doesn't support this shortcuts."

But I've described everything and put link to prevent misunderstanding...
I mean shortcuts like `ctrl-h` instead of `ctrl-w-h`.

**Comment by lambdalisue** [comment]
Is it a fern's issue? I don't think so.

**Comment by timsofteng** [comment]
> Is it a fern's issue? I don't think so.

Navigation shortcuts work in all vim windows except fern. I guess it is fern issue.

**Comment by lambdalisue** [comment]
May https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L396 help?

**Comment by timsofteng** [comment]
> May https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L396 help?

yep, it works with disabling default keymap

**Comment by hamensman** [comment]
> May https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L396 help?

Which option was this referring to? At least right now, line 396 is an empty line.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/blob/dd365ec17e9ff1d87a5ce4ade8abf123ecfd007a/doc/fern.txt#L385

This one.

**Comment by hartigan43** [comment]
@timsofteng stumbled upon your issue here and then found this one, specifically relating to `vim-tmux-navigator`:

https://github.com/lambdalisue/fern.vim/issues/235#issuecomment-1787208198
