### ISSUE TITLE
Unable to delete nodes (neovim)

### ISSUE THREAD

**Issue by JaoCR** [lambdalisue/fern.vim#347]
The behaviour:

![Peek 2021-06-17 18-12](https://user-images.githubusercontent.com/54376346/122473042-b7776a80-cf97-11eb-8333-bc18dd303660.gif)

Relevant parts of my init.vim:
``` Vim
" Plugins
call plug#begin('~/.config/nvim/autoload/plugged')

    " Tree
    Plug 'lambdalisue/fern.vim'
    Plug 'lambdalisue/fern-git-status.vim'
    Plug 'lambdalisue/fern-hijack.vim'
    Plug 'lambdalisue/nerdfont.vim'
    Plug 'lambdalisue/fern-renderer-nerdfont.vim'

call plug#end()

" Fern
let g:fern#renderer = "nerdfont"
```

My full init.vim: [init.vim.zip](https://github.com/lambdalisue/fern.vim/files/6673271/init.vim.zip)

Also tested without all the extra plugins, the problem persists.

**Comment by JaoCR** [comment]
Also, I am using the `D` command, for `trash`. I notice there is a `remove` thing listed there when I hit `?` but with no mapping.

**Comment by lambdalisue** [comment]
Maybe https://github.com/lambdalisue/fern.vim/wiki#additional-requirements help?

**Comment by JaoCR** [comment]
Ow yes, my bad, this is it. Thanks!
