### ISSUE TITLE
How can I run fern automatically on startup neovim?

### ISSUE THREAD

**Issue by WIttyJudge** [lambdalisue/fern.vim#348]
I want to open fern automatically when I enter to vim.
I tried to do this using ``autocmd VimEnter * Fern . -drawer -toggle``, but something went wrong and it's not works as except.
Thank you in advance!

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Tips#start-fernvim-on-vim-startup-with-a-particular-directory

Prob `++nested`.

**Comment by WIttyJudge** [comment]
Thank you very match, I missed it in the documentation

**Comment by lambdalisue** [comment]
Please close if your problem is solved 👍
