### ISSUE TITLE
It is available to open fern on every new opened tabs?

### ISSUE THREAD

**Issue by WIttyJudge** [lambdalisue/fern.vim#349]
When I used to NERDTree, this plugins ``https://github.com/jistr/vim-nerdtree-tabs`` fixed that issuer.
Does fern have something similar? 
Thank you in advance!

**Comment by lambdalisue** [comment]
Unfortunately no but you can implement it with the following autocmd I guess.

```
							*TabNew*
TabNew				When creating a new tab page. |tab-page|
				After WinEnter.
				Before TabEnter.
							*TabNewEntered*
TabNewEntered			After entering a new tab page. |tab-page|
				After BufEnter.
```

**Comment by lambdalisue** [comment]
A bit related to #348
