### ISSUE TITLE
Highlight for fern background

### ISSUE THREAD

**Issue by samrath2007** [lambdalisue/fern.vim#353]
Change the background of the buffer for fern. nvim-tree.lua implements this. The background of the explorer is a different color than the rest of the buffers.

**Comment by lambdalisue** [comment]
I've no idea what you are talking about. Please explain the situation or whatever more clearly.

**Comment by dragonlobster** [comment]
is there a way to change the `Normal` highlight group of a fern window only? for example a highlight group like `FernNormal` which is the background color:

<img width="965" height="923" alt="Image" src="https://github.com/user-attachments/assets/4a7d0e03-ed6c-4aa5-9a12-7f220f95ec33" />

**Comment by dragonlobster** [comment]
> is there a way to change the `Normal` highlight group of a fern window only? for example a highlight group like `FernNormal` which is the background color:
> <img alt="Image" width="965" height="923" src="https://private-user-images.githubusercontent.com/63202668/475884270-4a7d0e03-ed6c-4aa5-9a12-7f220f95ec33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ2MzM4NDIsIm5iZiI6MTc1NDYzMzU0MiwicGF0aCI6Ii82MzIwMjY2OC80NzU4ODQyNzAtNGE3ZDBlMDMtZWQ2Yy00YWE1LTlhMTItN2YyMjBmOTVlYzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA4VDA2MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5OTIwYTUwN2RkOTcyYzE0ODM1YjJlZGUwYzAwZDY5OWNjYTBiOGRmZDc2NGNlMjEzOWVhNDYwMzFhMzQxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Yib7rh6MqQTW1P9-6LSXY9IEdvc9dxCqiYaKgXAvRs">

i realized it can be achieved with winhighlight. `:help winhighlight`
