### ISSUE TITLE
fern+kyazdani42 / nvim-web-devicons

### ISSUE THREAD

**Issue by Trid-collab** [lambdalisue/fern.vim#359]
I am using Neovim nightly and am using nvim-web-devicons instead of ryanoasis/vim-devicons. Wanted to check if fern would run with the nvim-web--devicons. I have installed the nvim-deb--devicons because it works with my other lua based plugins. But I also want to use fern.

Also is there going to be a perceptible performance issue between fern and other lua based tree plugin like nvim- tree from which I plan to migrate to fern

**Comment by lambdalisue** [comment]
As long as I know, there is no such renderer. You can ask if @Shatur made one (See https://github.com/lambdalisue/fern-renderer-nerdfont.vim/issues/7)

**Comment by Shatur** [comment]
I switched to https://github.com/kyazdani42/nvim-tree.lua
It's good if you want a lua-based config.

**Comment by lambdalisue** [comment]
> Also is there going to be a perceptible performance issue between fern and other lua based tree plugin like nvim- tree from which I plan to migrate to fern

I don't know. I've never faced performance issues of fern. Note that performance is NOT first priority of the fern while Vim script is quite slow (so I really care about latency but throughput).
Probably tree viewer written in Lua is faster if you really need performance.

**Comment by lambdalisue** [comment]
> I switched to https://github.com/kyazdani42/nvim-tree.lua
It's good if you want a lua-based config.

I see. It's sad but your choice 👍 
Well, then @Trid-collab  needs to wait if someone made it or make it by yourselves 👍

**Comment by Trid-collab** [comment]
I am presenting using nvim-tree.lua and working to transition back to fern as I do not find some features marking multiple files , bookmarking , top project file etc . I am not sure if these exits in nvim-tree.lua but could'nt find it. Hence I wanted to use fern.

**Comment by bluz71** [comment]
Performance, for very huge directories such as `node_modules`, is a little bit faster in nvim-tree.lua (on first open) than fern (say 0.5secs vs 1.5secs, something like that). For the most part though performance is quite comparable between both file drawers.

Both nvim-tree.lua and fern.vim are much **MUCH** faster than NERDtree, orders of magnitude faster for big trees. NERTree would take 15 to 40 seconds to open a huge `node_modules` directory last time I checked.

I do use Neovim, but I am so used to fern.vim's multi-marking feature that I can't see the benefit of switching away. fern is a great plugin.

The only feature of nvim-tree.lua that I would like in fern.vim is the ability to highlight executable files and read-only files in a different color (with my colorscheme). nvim-tree.lua highlights executable files in color and I really find that quite useful. I wonder if that is possible with the fern architecture?

**Comment by bluz71** [comment]
@Trid-collab & @lambdalisue,

Adding support for *nvim-web-devicons* should be very easy. I don't believe a new plugin is required, rather the existing [fern-renderer-devicons](https://github.com/lambdalisue/fern-renderer-devicons.vim) can be extended.

My own [moonfly-statusline](https://github.com/bluz71/vim-moonfly-statusline) was recently extended with support for both *vim-devicons* and *nvim-web-devicons*, the code in question is [this](https://github.com/bluz71/vim-moonfly-statusline/blob/master/autoload/moonfly_statusline.vim#L27):

```viml
    if exists('g:nvim_web_devicons')
        return luaeval("require'nvim-web-devicons'.get_icon(vim.fn.expand('%'), vim.fn.expand('%:e'))") . ' '
    elseif exists('g:loaded_webdevicons')
        return WebDevIconsGetFileTypeSymbol() . ' '
    else
        return ''
    endif
```

The *fern-renderer-devicons* code of interest is likely [this](https://github.com/lambdalisue/fern-renderer-devicons.vim/blob/master/autoload/fern/renderer/devicons.vim#L69):

```viml
 if a:node.status is# s:STATUS_NONE
    let symbol = WebDevIconsGetFileTypeSymbol(a:node.bufname, 0)
  elseif a:node.status is# s:STATUS_COLLAPSED
    let symbol = WebDevIconsGetFileTypeSymbol(a:node.bufname, 1)
  else
    let symbol = g:DevIconsDefaultFolderOpenSymbol
  endif
  return symbol . '  '
```

It shouldn't be hard to add in ` if exists('g:nvim_web_devicons')` and then do `luaeval("require'nvim-web-devicons'.get_icon...` else fallback to existing `WebDevIconsGetFileTypeSymbol` calls. Maybe only 10-15 lines of code needed.

I do think this is worthwhile to do since Neovim users who like icons will likely be using *nvim-web-devicons*.

**Comment by lambdalisue** [comment]
Please create a new one while nobody needs both.

**Comment by lambdalisue** [comment]
>The only feature of nvim-tree.lua that I would like in fern.vim is the ability to highlight executable files and read-only files in a different color (with my colorscheme). nvim-tree.lua highlights executable files in color and I really find that quite useful. I wonder if that is possible with the fern architecture?

Interesting but difficult. Quite similar to https://github.com/lambdalisue/fern.vim/issues/264

**Comment by bluz71** [comment]
> Please create a new one (maybe "fern-renderer-nvim-web-devicons"?) while nobody needs both (this is the reason why there are fern-renderer-devicon and fern-renderer-nerdfont)

I think *fern-render-devicons.nvim* would be a good name (with nvim extension).
The existing plugin is *fern-renderer-devicons.vim* (with vim extension).
