### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by hrsh7th** [lambdalisue/fern.vim#36]
便利なプラグインをありがとうございます。
いくつか機能要望と質問と不具合報告をさせてください。

#### 不具合報告

1. `Fern /` が正しく動作しない？
/etc や /usr などが表示されることを期待していましたが、適切に表示できない気がします。

#### 機能要望

1. `autoload/fern.vim` あたりに利用者向けの API があると嬉しいです。
例えば、カーソル上のノードを取得したり、現在表示中のルートパスを取得したり、cd したりなどです。（file provider 以外の場合にこまる可能性がないとも言えないので、あくまでも要望として）

#### 質問

1. 表示中に Fern バッファのルートパスを変更する正しい方法は `Fern %path%` をバッファ上で叩くで正しいでしょうか？

**Comment by lambdalisue** [comment]
1. 確認しました。修正します 👍 
2. 一応正式リリースでは用意する予定です 👍 
3. Yes 👍 

これくらいの分量であれば Slack で全然OKでした 🙇
