### ISSUE TITLE
Reveal the siblings of the parent folder, but within project folder?

### ISSUE THREAD

**Issue by nyngwang** [lambdalisue/fern.vim#360]
Current:

```
nnoremap <silent> <Plug>(my-fern-toggle) :Fern %:p:h -drawer -reveal=%:p -width=33 -toggle<CR>
```

I like the result of using `%:p:h:h`, which is what I meant "reveal the siblings of the parent folder" in the title. For example:

<img src="https://user-images.githubusercontent.com/24765272/129467991-daf8f73d-16cb-4cc8-881a-63a533399e53.png" width="500">

But in some case I don't want this, i.e. when the files/folders outside of the project folder are revealed. For example:

<img src="https://user-images.githubusercontent.com/24765272/129467962-c625e442-1930-472c-a556-aeb615061976.png" width="500">

What I expect is:

<img src="https://user-images.githubusercontent.com/24765272/129468051-44aec052-8c7e-435f-b408-d786cdac66a9.png" width="500">

Consider the setup flow, I expect:

1. With any file under the target parent folder open.
2. Type some command to aim this folder, so the ceiling of revealing is set. The opening of drawer thereafter will not reveal files outside of this target parent folder.

I think this sure can be done, please shed some light for me, thanks!

**Comment by lambdalisue** [comment]
Well, it's not exactly fern's question but it's more like a question about Vim script itself. What you need is a function that properly returns a path depending on your situation. For example

```vim
function! s:get_fern_path() abort
  " Do more clever things here
  return expand("%:p")
endfunction

nnoremap <silent> <Plug>(my-fern-toggle) :Fern <C-r>=<SID>get_fern_path()<CR> -drawer -reveal=%:p -width=33 -toggle<CR>
```

You need to know how to write a body of `s:get_fern_path()` function above. So please ask how to write such a function in StackOverflow or so on.
