### ISSUE TITLE
vsplit opens on the left - options for right? 

### ISSUE THREAD

**Issue by sozoalvin** [lambdalisue/fern.vim#363]
Dear lamdalisue, thank you for your great work - just a qustion . 

Does fern default vsplit windows from the left? 

i.e.g fern window has file1, file2, file3 in the project directory. 

**when u look at the screen from the left to the right**
v splits file 1, the file1 now appears on the left of fern 
v splits file 2, files will look like : file1, file2, fern table
v splits file 3, files will look like : file3, file2, file1, fern table 

is this a normal behavior? Was hoping that we could configure fern to vsplit buffer windows to the right side instead

**Comment by lambdalisue** [comment]
I'm not sure I understand your question correctly but fern provides a lot more actions like `fern-action-open:right`. See `:help fern-action-open:right` or around for details.

**Comment by sozoalvin** [comment]
Dear lamdalisue, 

may i know what is the default behavior? 
The fern view is always the first thing to open in vim when i open a project folder. 

Subsequently i navigate to a file that i want to open, i press v for a v split and this file ends up on the left of the fern tree. 

Is it supposed to v split to the right, or to the left of the fern tree? 

This is what i have in my .vimrc file. 

```
  nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> <2-LeftMouse> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> m <Plug>(fern-action-mark:toggle)j
  nmap <buffer> N <Plug>(fern-action-new-file)
  nmap <buffer> K <Plug>(fern-action-new-dir)
  nmap <buffer> D <Plug>(fern-action-remove)
  nmap <buffer> V <Plug>(fern-action-move)
  nmap <buffer> R <Plug>(fern-action-rename)
  nmap <buffer> s <Plug>(fern-action-open:split)
  nmap <buffer> v <Plug>(fern-action-open:vsplit)
 nmap <buffer> r <Plug>(fern-action-reload)
 nmap <buffer> <nowait> d <Plug>(fern-action-hidden:toggle)
 nmap <buffer> <nowait> < <Plug>(fern-action-leave)
 nmap <buffer> <nowait> > <Plug>(fern-action-enter)

**Comment by lambdalisue** [comment]
While you are using `vsplit` and there is only one window, that's correct behavior unless you changed `splitright` option.
Reading `:help fern-glossary-anchor` may help.

**Comment by sozoalvin** [comment]
ill give that a read. As a solution, i've permanently have splits open on the right with
```set splitright``` in my .vimrc file.
