### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sozoalvin** [lambdalisue/fern.vim#364]
Dear Lambdalisue, 

thanks again for this great plugin. 

Need some suggestions: currently, i have this line of code 
```noremap <silent> <Leader>e :Fern . -drawer -reveal=% -stay<CR><C-w>=```
This allows me to stay on my current buffer, and assuming the fern drawer is open, allows me to display the current buffer's directory at will. 

I have a question - is there any ways to update fern drawer automatically when i switch buffers/split screens without executing _leader+e_ all the time? 

Hope you understand my question!

**Comment by lambdalisue** [comment]
See `:help WinEnter` and `:help autocmd-nested`

**Comment by sozoalvin** [comment]
thank you - that will be something i will explore further down the road. lots of reading to do!
