### ISSUE TITLE
Add warning if you try to delete but didn't install the dependencies

### ISSUE THREAD

**Issue by GGCristo** [lambdalisue/fern.vim#365]
I was trying to delete a folder, but it didn't get deleted, and I didn't have any feedback. It turns out I didn't have the trash.cli installed, so is my bad, but I think it should be some kind of warning, so users can realize what's going on.

**Comment by lambdalisue** [comment]
@GGCristo Could you try https://github.com/lambdalisue/fern.vim/pull/368

**Comment by GGCristo** [comment]
It works, but the message is not persistent, I don't even get to see it. I have to use the :messages command.

**Comment by lambdalisue** [comment]
> I have to use the :messages command.

Yes. You have to use `:mes` while the message is showed asynchronously. It's kind limitation for Vim/Neovim
