### ISSUE TITLE
Add an option to prevent prompt confirmation

### ISSUE THREAD

**Issue by bgaillard** [lambdalisue/fern.vim#366]
Hi, i'm just starting to use Fern as a replacement for NERDTree and I already love it ! Thanks for the huge work you did to create this plugin.

As others I chose this plugin to speed-up my work, I just created the following mapping to quickly delete files.

```vim
function! s:init_fern() abort
  map <nowait><buffer> d <Plug>(fern-action-remove)
endfunction
```

It correctly calls the delete code but I think the confirmation prompt is very annoying and makes me lost time when I have several files to delete.

```bash
The following 1 files will be removed
/home/baptiste/workspace/bgaillard-unix/scripts/learn-shell.sh
Are you sure to continue (Y[es]/no):
```

I know I can select several files with the `-` key and then delete them in one shot but I think it's still not fast enough.

In my case I never use Vim without being on a GIT project, so when I delete a file accidentally it's not a problem and the standard practice is simply to revert the change with GIT.

In this case I think the confirmation prompt is not necessary, neither the trash option.

So, to be able to speedup things even more I would propose to add a new `g:fern#disable_confirm_prompts`  option.

```md
g:fern#disable_confirm_prompts
    Disable all confirmation prompts (i.e Y[es]/no questions) when files remove or rename are done.
```

What do you think about this proposition ?

**Comment by lambdalisue** [comment]
@bgaillard Please try https://github.com/lambdalisue/fern.vim/pull/367 and give me your feedback.

**Comment by bgaillard** [comment]
Hi @lambdalisue, thanks a lot for this PR and for your reactivity !

I just tested it with the following and it works perfectly :+1: 

```vim
function! s:init_fern() abort
  map <nowait><buffer> d <Plug>(fern-action-remove=)y<CR><CR>
endfunction
```

For those interested I had to add 2 `<CR>` in my mapping to prevent entering `ENTER` when we need to delete several files in one shot. Otherwise the following message will be displayed.

```bash
2 items are removed
Press ENTER or type command to continue
```

**Comment by bgaillard** [comment]
I have an other question, I want to have a configuration in such a way I always have 2 windows like this (even if I delete files).

```bash
|------------|-----------------|
| Fern       | Buffers to edit |
|            |                 |
|            |                 |
|------------|-----------------|
```

I configured Fern to be automatically opened when I open vim on a specific folder.

```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * ++nested if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | set number! | exe 'Fern' argv()[0] '-drawer' '-stay' '-keep' | set number | endif
```

Opening works correctly, but when I delete files I cannot succeed to let the "Buffers to edit" window to be opened.

See this example where I first open file `a1` and then I delete `a2`. I'm expecting to keep `a1` opened in the "Buffers to edit" window but it's not the case.

![delete-file](https://user-images.githubusercontent.com/1327782/133837822-6dd98403-a530-4993-b64c-de10580c3f59.gif)

Do you know what is the problem and what can I do to prevent this ?

**Comment by lambdalisue** [comment]
Too many factors to test. Please reduce.

**Comment by bgaillard** [comment]
Hi @lambdalisue, sorry for the delete providing a simple environment to reproduce the problem.

You can clone this GIT repo and follow the instructions to reproduce it (it takes less than 1 minute to setup) : https://github.com/bgaillard/ferm.vim-366

I you need more details do not hesitate to ask. 

Thanks

**Comment by lambdalisue** [comment]
I'm sorry but the following does not tell how to reproduce. Please write a step by step guide with actual commands, mappings so that I can follow your situation.

```
# Then do the following to reproduce the problem with fern
#  1. Open the 'test1.txt' file
#  2. Delete the 'text2.txt' file
#
# You should observe that the right side of the screen is closed
```

**Comment by bgaillard** [comment]
Hi, ok, here is the procedure.

1. Checkout branch associated to https://github.com/bgaillard/ferm.vim-366 `cd /tmp; git clone git@github.com:bgaillard/ferm.vim-366.git; cd ferm.vim-366`
2. Execute `vim -N -u .vimrc .`
3. Hit `<C-w>h`
4. Hit `j` `j` `l`
5. Hit `<C-w>h`
6. Hit `j` `d`

Right side is closed but it should not.

Thanks

**Comment by lambdalisue** [comment]
I followed your procedure but nothing happens...

https://user-images.githubusercontent.com/546312/137578941-e6f6835c-94b5-43b3-8754-260c4cad77a6.mp4

I don't have plug.vim thus I replaced it with Vim's native pack feature (showed as git diff in the first part of the video)

**Comment by lambdalisue** [comment]
So is this what you've faced?

https://user-images.githubusercontent.com/546312/137579130-a3185a63-94a8-4252-86e6-d110260d7019.mp4

And what was your expectation? (what do you think a **correct** behavior?)

**Comment by lambdalisue** [comment]
@bgaillard 
Sorry for the late reply.

Well, it seems your mapping is incorrect. Use `nmap <nowait><buffer> d <Plug>(fern-action-remove=)y<CR>` instead.


https://user-images.githubusercontent.com/546312/147625819-23349b6c-5177-4dcb-80e3-1677dc291bf3.mp4


1. `vim -N -u .vimrc .`
2. `:Fern . -drawer -stay -keep`
3. HIt `<C-w>h`
4. Hit `jjl`
5. Hit `<C-w>h`
6. Hit `j`
7. Hit `d`

I've tried with the following minimal vimrc.

```vim
set runtimepath^=~/ghq/github.com/lambdalisue/fern.vim

function! s:init_fern() abort
  nmap <nowait><buffer> d <Plug>(fern-action-remove=)y<CR>
endfunction

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
```
