### ISSUE TITLE
Remove the slash "/" at the end of directory node names

### ISSUE THREAD

**Issue by alexandersokolow** [lambdalisue/fern.vim#370]
Title is self explanatory I think. Is there a way to do this in fern? Haven't found anything in :help fern

**Comment by alexandersokolow** [comment]
Have got it to work for me by changing the render method in the source code, unfortunately the syntax-highlighting was dependend on having this slash in the end. 
As I have custom symbols for directory nodes I just use those for the syntax highlighting now. Maybe it's possible to generalize that & use the user-defined symbols for expanded/collapsed directories, not sure whether you can use variables for syntax highlighting in vimscript though. 
If it was setup like that, a config variable could be added for removing those slashes at the end (or using a custom string there).

Maybe I could try to do that, as I'd prefer it to maintaining my own fork, would you be interested in a PR for that?

**Comment by lambdalisue** [comment]
Duplicated https://github.com/lambdalisue/fern.vim/issues/223
