### ISSUE TITLE
Remapping Enter key not working

### ISSUE THREAD

**Issue by himat** [lambdalisue/fern.vim#376]
I followed the instructions in the wiki to define a key to make fern expand or collapse instead of going into a directory. https://github.com/lambdalisue/fern.vim/wiki/Tips#perform-expand-or-collapse-directory

But I wanted the Enter key (CR) to do that action, so I changed the mapping as you can see here
```
function! s:init_fern() abort
  nmap <buffer><expr>
      \ <Plug>(fern-my-expand-or-collapse)
      \ fern#smart#leaf(
      \   "\<Plug>(fern-action-collapse)",
      \   "\<Plug>(fern-action-expand)",
      \   "\<Plug>(fern-action-collapse)",
      \ )

  nmap <buffer><nowait><CR> <Plug>(fern-my-expand-or-collapse) " enter key defined here
endfunction
```

But even with this, when I press Enter while on a directory name, it still makes Fern go into the directory instead of just expanding it.

How do I fix this?

**Comment by himat** [comment]
Additionally, trying to map `r` to something also does not work (from the wiki as well https://github.com/lambdalisue/fern.vim/wiki/Tips#define-nerdtree-like-mappings)
`nmap <buffer> r <Plug>(fern-action-reload)`

When I press `r`, the vim status line shows me `E21: Cannot make changes, 'modifiable' is off`
I assume it's trying to do the normal mode mapping of `r` which is to replace the character under the cursor.

How can I override the `r` key?

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Tips#how-to-customize-fern-buffer might help?

**Comment by himat** [comment]
Whoops I missed that, my bad. Thanks
