### ISSUE TITLE
Close fern buffer after opening file

### ISSUE THREAD

**Issue by himat** [lambdalisue/fern.vim#378]
After I select a file within the fern viewer, it seems like the fern buffer is still available in vim

Which means that when I then do `:b#` to go back to my previous file, it is opening the fern buffer instead.

Is there a way to auto close the buffer after I select/open a file?
I saw https://github.com/lambdalisue/fern.vim/wiki/Tips#close-fern-after-open but not really sure what "Close fern" means for that tip. Does it close the buffer or does it close all of fern somehow?

**Comment by lambdalisue** [comment]
It sounds fern behave properly in your case from your explanation. 

I think using `:b#` is not a proper way to get back a previous file. Maybe what you need is https://github.com/Bakudankun/BackAndForward.vim or similar plugin.

**Comment by himat** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Tips#close-fern-after-open What does "Close fern" exactly do?

**Comment by lambdalisue** [comment]
Close fern window.
