### ISSUE TITLE
Unable to keep autofocus on file node with autocommands

### ISSUE THREAD

**Issue by tinny-blueleo** [lambdalisue/fern.vim#382]
Hi Lambdalisue!

I'm sorry I posted this in the wrong repository earlier.  I'm trying to get autofocus in a Fern drawer on so that it automatically switches and opens folders recursively till it focuses on a file even if I open it with another tool like Telescope:

	  vim.cmd([[
	  	if !isdirectory(expand('%:p'))
			augroup fern-dir-startup
				autocmd! *
			augroup END
		else 
			augroup fern-dir-startup
				autocmd! *
				autocmd VimEnter * ++nested Fern <afile> -drawer -reveal=% -stay
			augroup END
		endif
		augroup fern-startup
			autocmd! *
			autocmd BufEnter * ++nested Fern . -drawer -reveal=% -stay
		augroup END

**Expected behavior:** that on opening a file in a given focused buffer via any means (either Telescope, :e, etc) that Fern should open tree nodes and focus in on the specified file.

**Actual behavior:** auto command hits a recursion error and Neovim glitches by opening multiple panes

**Actual behavior without ++nested parameter:** the Fern drawer goes blank

Any help would be greatly appreciated!

**Comment by lambdalisue** [comment]
I'm not sure if I understand your question correctly but it sounds like your request is the reason why `FernDo` and `FernReveal` exist for.

Executing the following will reveal the current buffer on the fern window. See `:help FernDo` or `:help FernReveal` for details.

```vim
:execute printf('FernDo FernReveal %s', expand('%:p'))
```

https://user-images.githubusercontent.com/546312/147915795-a2e6cdf0-11a1-4a46-8dc7-c5abcc139805.mp4

**Comment by tinny-blueleo** [comment]
Hi Alisue!  Thank you for the quick reply.  It looks like using FernDo and FernReveal in the editor works great and immediately jumps to the file in the explorer.  I'm hoping to get that working with also opening the file with other tools like Fzf or Telescope using the BufRead or BufEnter autocommand.  For clarity:

**Expected behavior:** If I use the right autocommand to switch files in a buffer I'd like the Fern drawer to auto navigate to the corresponding leaf.

**Actual behavior:**  Given the following script, I have to use Telescope to switch to the file twice before it navigates to the corresponding leaf:

	" function to reveal Fern leaf if it's a path that's not empty
	" not of type fern, and not in a .git folder path
	function! RevealFern()
		let leafPath = expand('%')
		if &filetype == 'fern'
			return
		elseif strlen(leafPath) < 1
			return
		" don't expand git paths
		elseif leafPath =~? '.*\.git/.*'
			return
		endif
		execute printf('FernDo -stay FernReveal %s', expand('%'))
	endfunction
	" don't start fern drawer if viming into a file instead of a folder
	if !isdirectory(expand('%'))
		augroup fern-startup
			autocmd! *
		augroup END
	else 
		augroup fern-startup
			autocmd! *
			autocmd VimEnter * ++nested Fern <afile> -drawer -reveal=% -stay
			autocmd BufEnter * call RevealFern()
			autocmd BufRead * ++nested call RevealFern()
		augroup END
	endif


Here's the video of the behavior:


![FernBufRead](https://user-images.githubusercontent.com/83375390/148075885-503bb529-331f-4ab7-9bbb-837185a15e85.gif)

**Comment by lambdalisue** [comment]
Is `BufEnter` triggered properly after you open a buffer?

**Comment by tinny-blueleo** [comment]
It's a little difficult for me to tell, at the top of my function I put this statement and this is the output:

echom "In Fern leaf: " . leafPath

![image](https://user-images.githubusercontent.com/83375390/148116216-2a89f674-6370-4641-b298-3d1bb656a1e8.png)

Do you know why the autocommand for VimEnter in the tips page suggests ++nested but using that for BufEnter throws a recursive error?

**Comment by tinny-blueleo** [comment]
Just to clarify for the above these were my following actions:

- Open neovim
- Use telescope to navigate to plugins.lua
- Use telescope to navigate to init.lua
- Use telescope to navigate back to plugins.lua

**Comment by lambdalisue** [comment]
> Do you know why the autocommand for VimEnter in the tips page suggests ++nested but using that for BufEnter throws a recursive error?

Because `FernDo` changes the current window to fern and back to the original, and then `BufEnter` is triggered.
