### ISSUE TITLE
Fern's buffer isn't restored properly when it's on a different tab

### ISSUE THREAD

**Issue by Paveloom** [lambdalisue/fern.vim#386]
This issue is somewhat similar to #116, but for a separate tab.

Step-by-step (tested with Neovim):
1. Use the default [minimal `.vimrc`](https://github.com/lambdalisue/fern.vim/wiki/Minimal-vimrc) as a configuration file
2. Open any file in the editor
3. Open Fern either as a drawer panel or as a split window
4. Open any other file in a separate tab

	  Here's what is should look like:
	  ![fern-issue-1](https://user-images.githubusercontent.com/49961859/149776901-53f02b17-11dd-4044-bd76-c51a45f65fc9.png)

5. Now switch to the second tab and save the session: `mksession! Session.vim`
6. Restart the editor and load the session: `source Session.vim`
7. Switch back to the first tab

	The Fern's window appears to be empty:
	![fern-issue-2](https://user-images.githubusercontent.com/49961859/149777007-db3f9c9c-795e-4ac9-8c54-d6caa11a284e.png)

	It's still functional, though. However, calling the `reload` action causes this:
    ![fern-issue-3](https://user-images.githubusercontent.com/49961859/149777218-9bd151c1-f130-43fc-b002-6086e96d9f5f.png)
	
    Changing the root directory or closing/reopening the tree viewer fixes these visual bugs.

**Comment by Paveloom** [comment]
Here you go.

<details>
<summary><code>Session.vim</code></summary>
<pre>
let SessionLoad = 1
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
silent only
silent tabonly
cd ~/Playground/fern-issue
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
argglobal
%argdel
$argadd vimrc.min
set stal=2
tabnew
tabrewind
edit vimrc.min
let s:save_splitbelow = &splitbelow
let s:save_splitright = &splitright
set splitbelow splitright
wincmd _ | wincmd |
vsplit
1wincmd h
wincmd w
let &splitbelow = s:save_splitbelow
let &splitright = s:save_splitright
wincmd t
let s:save_winminheight = &winminheight
let s:save_winminwidth = &winminwidth
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
exe 'vert 1resize ' . ((&columns * 30 + 78) / 156)
exe 'vert 2resize ' . ((&columns * 125 + 78) / 156)
argglobal
enew
file fern://drawer:1/file:///home/paveloom/Playground/fern-issue;\$
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
wincmd w
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let &fdl = &fdl
let s:l = 1 - ((0 * winheight(0) + 19) / 38)
if s:l < 1 | let s:l = 1 | endif
keepjumps exe s:l
normal! zt
keepjumps 1
normal! 0
wincmd w
exe 'vert 1resize ' . ((&columns * 30 + 78) / 156)
exe 'vert 2resize ' . ((&columns * 125 + 78) / 156)
tabnext
edit vimrc.min
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let &fdl = &fdl
let s:l = 1 - ((0 * winheight(0) + 19) / 38)
if s:l < 1 | let s:l = 1 | endif
keepjumps exe s:l
normal! zt
keepjumps 1
normal! 0
tabnext 2
set stal=1
badd +0 vimrc.min
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0 && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToOF
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save
set hlsearch
nohlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
</pre>
</details>

**Comment by lambdalisue** [comment]
> Changing the root directory or closing/reopening the tree viewer fixes these visual bugs.

For a temporal workaround, use `:e` to reload fern.

**Comment by lambdalisue** [comment]
@Paveloom 

I'm sorry for the late reply. The issue was a bit tough.

https://github.com/lambdalisue/fern.vim/pull/394 would solve the issue so could you try?
