### ISSUE TITLE
Rename in a case-sensitive way

### ISSUE THREAD

**Issue by ibuibu** [lambdalisue/fern.vim#389]
I tried to rename a file `userController.tsx` to `UserController.tsx`, but "already exist" error occured.

Is it possible to make renaming case-sensitive?

**Comment by lambdalisue** [comment]
Probably no. What is your OS?

**Comment by ibuibu** [comment]
macOS Catalina
version 10.15.7

**Comment by lambdalisue** [comment]
In normal macOS, the file system is not case-sensitive. So it's not possible from an OS perspective.
