### ISSUE TITLE
Reveal does not work for relative files that begin with `./`

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern.vim#393]
Hello,

Interesting issue with reveal. If a file begins with `./` reveal does not work, however, if the `./` is stripped away then reveal does work.

Steps to reproduce:

* Check out `fern.vim` repository

* Launch Vim/Neovim from base directory as follows: `vim test/fern/helper.vimspec`

* Do reveal as follows: `Fern . -drawer -reveal=%`; this works

* Now launch Vim/Neovim from base directory with `vim ./test/fern/helper.vimspec`

* Do reveal as follows: `Fern . -drawer -reveal=%`; this does **not** work, file will not be revealed in the tree.

Since with and without `./` is the same thing fern.vim should always correctly reveal the file in the drawer tree either way.

Hopefully an easy fix.

I only noticed this now since Neovim, all of a sudden, is producing lots of `./` instances where it didn't before (I don't know what changed). It's not wrong, just different.

Best regards.

**Comment by lambdalisue** [comment]
Fixed.

**Comment by bluz71** [comment]
Thank you @lambdalisue, fix works perfect.

Best regards.
