### ISSUE TITLE
Highlight groups for hidden files, symlinks, and custom defined files?

### ISSUE THREAD

**Issue by riddlew** [lambdalisue/fern.vim#400]
I switched to Fern from nvim-tree and I've been loving it so far. There are 2 features that I miss from nvim-tree that I would love to see added to Fern:

1. Highlight groups for symlinks and hidden files so that they can be colored differently from regular files.
2. The ability to define a list of filenames that should receive their own highlight group (for example, coloring all of the Makefiles red to make it stand out).

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L695

You can invoke your custom syntax codes by above autocmd thus you can do what ever you want on fern buffer 👍

**Comment by eiji03aero** [comment]
I think what @riddlew meant was highlighting FernLeafText by looking at specific file name or file extension.
I would love to know if this is possible.
So far I have been trying a some function like below, but not working 🤔 
Is there constraints on this?

```
function! s:fernHighlight(extension, fg, bg)
  exec 'autocmd filetype fern highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg
  exec 'autocmd filetype fern syntax match ' . a:extension . ' /' . a:extension . '/'
endfunction

call s:fernHighlight('json',       '208',          'none')
```

**Comment by lambdalisue** [comment]
I'm sorry for the late reply.

Use `User FernSyntax` autocmd instead of `FileType fern`.

**Comment by eiji03aero** [comment]
@lambdalisue 
Hi, thanks for the reply 🙇 

```
function! s:fernHighlight(extension, fg, bg)
  exec 'autocmd User FernHighlight highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg
  exec 'autocmd User FernHighlight syntax match ' . a:extension . ' /' . a:extension . '/'
endfunction

call s:fernHighlight('json',       '208',          'none')
```

tried something like above, but  the color of json file name is still not changing ...
<img width="375" alt="Screen Shot 2022-08-01 at 23 00 24" src="https://user-images.githubusercontent.com/13347338/182165032-87dd0218-ed8b-49fa-b82a-d23b499ae938.png">

Sorry I'm not really familiar with vim script, but am I doing something wrong here?

**Comment by lambdalisue** [comment]
Try

```vim
function! s:syntax() abort
  syntax match Foo /.*\.vim/
endfunction

augroup my_fern
  autocmd!
  autocmd User FernSyntax call s:syntax()
augroup END

highlight Foo guibg=#ff0000
```

If you have more question, please use stackoverflow or whatever while this is Vim's question rather than Fern itself.

**Comment by eiji03aero** [comment]
yeah that is right, thanks for the help though 🙇
