### ISSUE TITLE
How can I open file in a new tab

### ISSUE THREAD

**Issue by ydzhou** [lambdalisue/fern.vim#401]
Hi, I did not find an action to open in new tab. Do you support this? or any available plugin?

**Comment by ydzhou** [comment]
Oh found the action `fern-action-open:tabedit`

Another question, is there a way to keep the new tab having the same fern opened in the previous buffer? similar to `vim-nerdtree-tabs`

**Comment by brandon1024** [comment]
@ydzhou it sounds like the feature you're looking for defeats the purpose of tabs in Vim, you might be misusing vim tabs. I used to be in the same boat back when I was new to vim; coming from editors and IDEs it was easy to use tabs two work on multiple files at once. That's what buffers and windows are for.

Tabs are collections of windows, each window displaying a buffer. They are meant as a way of editing files without messing with your window layout, as mentioned here [here](https://vimhelp.org/tabpage.txt.html#tab-page-intro):

> Tabs are also a nice way to edit a buffer temporarily without changing the current window layout.  Open a new tab page, do whatever you want to do and close the tab page.

Also [put nicely](https://stackoverflow.com/a/103590/4501022):

> This is not how Vim's tabs are designed to be used. In fact, they're misnamed. A better name would be "viewport" or "layout", because that's what a tab is—it's a different layout of windows of all of your existing buffers.

The fern window is just a window like the others. You get to decide when you want to see the window or not in your current tab (_viewport_). Implementing a facility for displaying the fern window in other/new tabs defeats the spirit of tabs. I'd recommend learning to embrace buffers and windows. Write [your own tabline](https://github.com/brandon1024/.dotfiles/blob/master/.vim/pack/config/opt/interface/plugin/tabline.vim) to show visible buffers! Consider creating mappings for opening files the way you want, in vertical/horizontal splits with the size/position you want. Embrace the idea of using tabs as _viewports_.

**Comment by lambdalisue** [comment]
> Another question, is there a way to keep the new tab having the same fern opened in the previous buffer? similar to vim-nerdtree-tabs

I did but I closed because I didn't need it.
https://github.com/lambdalisue/fern.vim/pull/261

Please make a new issue as a feature request if you desire that feature. I may reconsider that.
