### ISSUE TITLE
Recursively expand directory under cursor

### ISSUE THREAD

**Issue by iworkinpixels** [lambdalisue/fern.vim#412]
I may be missing something in the mappings, but I have been looking for something that is the equivalent of "O" in NERDTree... that is, I want to recursively expand the directory under the cursor, and all of its children as well... 

From the docs it looked as though Reveal might be the thing that I was looking for, but testing it on a directory with lots of children, it only expanded the top level directory and did not expand the children. 

Does Fern have an equivalent to "O" in NERDTree?

**Comment by Shougo** [comment]
I think you can use `:Fern -reveal` for it.

```
							*fern-reveal*
	If {reveal} is specified, parent nodes of the node which is identified
	by the {reveal} are expanded and the node will be focused.
	The {reveal} must be a relative path separated by "/" from the
	specfied {url}.
	Note that if the {url} is for "file" scheme, an absolute path can be
	specified to the {reveal}.
```

**Comment by Shougo** [comment]
Hm...  It does not support under the cursor.
It seems `-search` feature in defx.nvim.

**Comment by lambdalisue** [comment]
Probably this. https://github.com/lambdalisue/fern.vim/issues/39

**Comment by iworkinpixels** [comment]
> Hm... It does not support under the cursor. It seems `-search` feature in defx.nvim.

The other reason why -reveal is not a good option is it only works in the other direction. For instance, I can do the following in my main wordpress directory:

`:Fern . -drawer -reveal=./wp-content/themes/twentytwentytwo/functions.php`

And that will open Fern with functions.php selected, and all of its ancestors all the way up to the current directory will be expanded, but all of the other nodes in the project will remain collapsed.

After labmdalisue's reply, apparently the "Expand all the children of this node recursively" feature is difficult to implement, so it's looking like my choices for this feature are to write a way to do it myself or else go back to NERDTree and deal with everything that comes with that. What's really funny is that I don't use this myself at all, the only thing I use it for is when my colleagues want to take a look at my screen, they desperately want to see a fully expanded project tree on the left. :D
