### ISSUE TITLE
Fern buffer is broken by `open:vsplit` after `s:restore_winfiwidth` is called

### ISSUE THREAD

**Issue by asmka** [lambdalisue/fern.vim#416]
Relates: #413 

Same problem occurs with following procedure.
1. Boot Neovim
1. `:Fern . -drawer -stay`
1. `:q`
1. Open file with `<Plug>(fern-action-open:edit)`
1. `:Fern . -drawer -stay`
1. `:q`
1. Open file with `<Plug>(fern-action-open:edit)`
1. `:Fern . -drawer`
1. Open file with `<Plug>(fern-action-open:vsplit)`

I guess `b:fern_drawer_auto_restore_winfixwidth` is unlet forever after `s:restore_winfixwidth()` is called.  
Is this line necessary?
https://github.com/lambdalisue/fern.vim/blob/1237977da5ae1fb5901d712745b1b5d0eeecdc51/autoload/fern/internal/drawer/auto_restore_winfixwidth.vim#L19

**Comment by lambdalisue** [comment]
Could you try https://github.com/lambdalisue/fern.vim/pull/417

**Comment by asmka** [comment]
Thanks for the quick fix! 🙇 
I confirmed problem didn't occur by #417.

I guess, however, there is extra line.
I commented on #417. Please check it.

**Comment by lambdalisue** [comment]
@asmka I couldn't find you comment.

**Comment by asmka** [comment]
Sorry, comment was pending.
I updated it.
