### ISSUE TITLE
Popup is shifted when drawer is displayed on the right side

### ISSUE THREAD

**Issue by rapan931** [lambdalisue/fern.vim#418]
## reproduce
0. add fern.vim/ at path/to/pack_path/pack/m/opt/
1. gvim.exe --clean
2. `:set packpath=path/to/pack_path`
3. `:packadd fern.vim`
4. `:Fern -drawer -right .`
5. move the cursor so that the popup appears

![image](https://user-images.githubusercontent.com/24415677/162790278-d483de42-7eba-424b-a792-4c4cf4b5be6e.png)

## env
- windows 10
- gvim.exe(1-4314)
- fern.vim(1237977da5ae1fb5901d712745b1b5d0eeecdc51)

**Comment by rapan931** [comment]
Thank you!

**Comment by brandon1024** [comment]
Interesting, this used to work correctly when I originally implemented this functionality. I presume there may have been a regression in 10dd4bb705fa21dbfabdafb592c7d58454af01e6.

**Comment by lambdalisue** [comment]
> I presume there may have been a regression in https://github.com/lambdalisue/fern.vim/commit/10dd4bb705fa21dbfabdafb592c7d58454af01e6.

I'm sorry but what was the **correct** behavior? I couldn't imagine thus I disabled that on right side.

**Comment by brandon1024** [comment]
No worries, here's what it looks like in the initial revision (63b79ab7440095a1adc1c10f2bfdba4ceb46080a).

<img width="932" alt="image" src="https://user-images.githubusercontent.com/22732449/170689565-e2e73843-5c26-4290-b77b-ac41c998536b.png">
<img width="932" alt="image" src="https://user-images.githubusercontent.com/22732449/170689495-ee86b7b7-4141-449f-866b-a8f9580a18b3.png">
<img width="932" alt="image" src="https://user-images.githubusercontent.com/22732449/170689612-f871159c-2070-4e77-9245-050b9686636c.png">

**Comment by lambdalisue** [comment]
Got it. I'm not sure if the behavior is the best but I feel it's fair enough.

This issue should be re-opened to re-implement that behavior.

**Comment by brandon1024** [comment]
Agreed, it was a bit of a nightmare getting that to work on the right drawer so I ended up settling with that behaviour. It would almost be better if the pop up was shifted over to the left instead of wrapping like that.
