### ISSUE TITLE
Failed to find a proper window to locate when popup is shown

### ISSUE THREAD

**Issue by bstaint** [lambdalisue/fern.vim#422]
neovim 0.8.0 dev

reproduce step:
```
let g:fern#drawer_width = 25
```
xxxxxxxxxxxxxx.c (The file name must be long enough)
![GIF 2022-05-09 09-11-01](https://user-images.githubusercontent.com/5853792/167324591-eb0000e2-814f-4489-85c9-60ac9925fad0.gif)

It will affect Window selector `auto_select` not work.

**Comment by lambdalisue** [comment]
It seems the popup buffer introduced by https://github.com/lambdalisue/fern.vim/pull/398 and https://github.com/lambdalisue/fern.vim/pull/403 is `buflisted`.

**Comment by bstaint** [comment]
other related issue

reproduce step:
cursor on popup buffer filename
`q:` open cmdline window

![GIF 2022-05-09 17-58-26](https://user-images.githubusercontent.com/5853792/167387083-97a21843-d87d-48c8-808d-7125b2139571.gif)

**Comment by lambdalisue** [comment]
I thougt this is because `nobuflisted` is not configured on the buffer but it was configured. https://github.com/lambdalisue/fern.vim/blob/master/autoload/fern/internal/drawer/hover_popup.vim#L76-L76

**Comment by lambdalisue** [comment]
This will be fixed by https://github.com/lambdalisue/vital-Whisky/pull/43

**Comment by lambdalisue** [comment]
@bstaint I'm sorry for late. Could you try https://github.com/lambdalisue/fern.vim/pull/425

**Comment by bstaint** [comment]
help:
```
`relative` is empty for normal windows.
```
`nvim_win_get_config(wi.winid).relative ==# ''` will fixed.

**Comment by lambdalisue** [comment]
Aha, fixed.

**Comment by bstaint** [comment]
> neovim 0.8.0 dev
> 
> reproduce step:
> 
> ```
> let g:fern#drawer_width = 25
> ```
> 
> xxxxxxxxxxxxxx.c (The file name must be long enough) ![GIF 2022-05-09 09-11-01](https://user-images.githubusercontent.com/5853792/167324591-eb0000e2-814f-4489-85c9-60ac9925fad0.gif) [ ](https://user-images.githubusercontent.com/5853792/167324591-eb0000e2-814f-4489-85c9-60ac9925fad0.gif) ![GIF 2022-05-09 09-11-01](https://user-images.githubusercontent.com/5853792/167324591-eb0000e2-814f-4489-85c9-60ac9925fad0.gif) [ ](https://user-images.githubusercontent.com/5853792/167324591-eb0000e2-814f-4489-85c9-60ac9925fad0.gif)
> 
> It will affect Window selector `auto_select` not work.

**Comment by bstaint** [comment]
patch:
``` diff
diff --git a/autoload/fern/internal/drawer/auto_restore_focus.vim b/autoload/fern/internal/drawer/auto_restore_focus.vim
index fcee18e..869e4a9 100644
--- a/autoload/fern/internal/drawer/auto_restore_focus.vim
+++ b/autoload/fern/internal/drawer/auto_restore_focus.vim
@@ -16,6 +16,7 @@ function! s:auto_restore_focus_pre() abort
         \ 'nwin': winnr('$'),
         \ 'tabpage': tabpagenr(),
         \ 'prev': win_getid(winnr('#')),
+        \ 'relative': nvim_win_get_config(win_getid(winnr('$'))).relative
         \}
   call timer_start(0, { -> extend(s:, {'info': v:null}) })
 endfunction
@@ -24,7 +25,7 @@ function! s:auto_restore_focus() abort
   if s:info is# v:null
     return
   endif
-  if s:info.tabpage is# tabpagenr() && s:info.nwin > winnr('$')
+  if s:info.tabpage is# tabpagenr() && s:info.nwin > winnr('$') && s:info.relative ==# ''
     call win_gotoid(s:info.prev)
   endif
   let s:info = v:null
```

**Comment by lambdalisue** [comment]
I'm sorry for late. Well, the patch doesn't make sense so I cannot approve that.

**Comment by lambdalisue** [comment]
OK. The latest #425 should fix the issue as well. Could you try? @bstaint

**Comment by bstaint** [comment]
Tks.
