### ISSUE TITLE
Hide status (Power) line for Fern buffer

### ISSUE THREAD

**Issue by s9chroma** [lambdalisue/fern.vim#429]
Does anyone know how I can hide the status line, hence Powerline/Airline, for Fern buffers? Can the status line be set to blank or something like that. Right now it shows a lot of information and looks very cluttered.

![image](https://user-images.githubusercontent.com/35374338/173119065-5b688c9e-b35f-4a5a-9a6f-97ac957e3360.png)

**Comment by lambdalisue** [comment]
Fern does nothing for powerline/airline so you need to ask questions on those.
