### ISSUE TITLE
Unexpected characters "^_" after file names in browser

### ISSUE THREAD

**Issue by Noahyt** [lambdalisue/fern.vim#433]
Every file in the browser is followed by the string "^_". What does this mean and how do I get rid of it? See screenshot:
<img width="191" alt="Screen Shot 2022-07-14 at 12 24 19 PM" src="https://user-images.githubusercontent.com/23128135/179030642-bcb454b7-5d4b-4a23-8b3d-41c4551d10d3.png">

**Comment by lambdalisue** [comment]
Maybe https://github.com/lambdalisue/fern.vim/issues/396#issuecomment-1073507080
