### ISSUE TITLE
[FEATURE REQUEST]: Integrate git and netrw hijack

### ISSUE THREAD

**Issue by xmready** [lambdalisue/fern.vim#438]
It would be nice if git and netrw hijack were not plugins, and instead integrated into fern.vim as global variables that can be set. The extra plugin lines are not needed in the .vimrc. 

"Customizability is less important than simplicity "

They are depends that can be integrated.

**Comment by lambdalisue** [comment]
I'm sorry but it should not because both features are not fundemental for fern.vim.

**Comment by xmready** [comment]
In my opinion those integrations should be fundamental to any modern tree viewer used by a coder

**Comment by lambdalisue** [comment]
In my opinion, that's not.
