### ISSUE TITLE
neovim nightly version fern toggle empty 

### ISSUE THREAD

**Issue by bstaint** [lambdalisue/fern.vim#442]
neovim version:
`NVIM v0.8.0-dev-957-g946c0aa66`

`:Fern . -drawer -toggle` don't fired `BufReadCmd`, can't load `fern_viewer_cache_content`.

screenshot:
![GIF 2022-08-26 16-57-28](https://user-images.githubusercontent.com/5853792/186867605-e6b085b7-6e7b-4a0f-9b23-a3d3c48da67c.gif)

**Comment by lambdalisue** [comment]
Not sure but prob Neovim's regression? It should be reported on Neovim's issue.

**Comment by bstaint** [comment]
Sry, it has been fixed https://github.com/neovim/neovim/commit/900a151bf541c7fa77a56b4881c4836a1cabcde6
