### ISSUE TITLE
Dead link in Concepts section of README

### ISSUE THREAD

**Issue by rguidice** [lambdalisue/fern.vim#444]
[This link](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/) from the Concepts section of the [README](https://github.com/lambdalisue/fern.vim/blob/main/README.md) gives a 403 forbidden error.

**Comment by lambdalisue** [comment]
I can access. I guess your environment problem.

**Comment by rguidice** [comment]
Yeah it works fine now. I think their site was down earlier today as I checked on multiple devices before I opened the issue - sorry about that though.
