### ISSUE TITLE
g:fern#disable_viewer_spinner = 1 doesn't work

### ISSUE THREAD

**Issue by beautiful-boyyy** [lambdalisue/fern.vim#445]
<img width="492" alt="Screen Shot 2022-09-04 at 12 04 47" src="https://user-images.githubusercontent.com/66351806/188296801-6617561a-24c3-4151-b903-719ef3870b62.png">

I want to disable the sign column, I did this according to the fern.txt， but sign column still show up

vim version: 9.0.350
terminal: iTerm2 3.4.16

**Comment by lambdalisue** [comment]
It does not disable sign column. See `:help signcolumn` and overwrite it by yourselve on `FileType` autocmd or so on.

**Comment by lambdalisue** [comment]
Note that I don't recommend to do that because fern use sign column to show not only spinner but marks as well.
