### ISSUE TITLE
can not open view as a tree

### ISSUE THREAD

**Issue by HCY-ASLEEP** [lambdalisue/fern.vim#446]
First, I use :Fern . -reveal=% to open exploer :
![image](https://user-images.githubusercontent.com/76894615/188771568-8c399e8b-7bbe-406f-b0e0-71daff00ab1a.png)
But when I press enter, it becomes this :
![image](https://user-images.githubusercontent.com/76894615/188771901-93aafd31-fb9d-4a20-a6ab-b2ef59c458df.png)
What I want is like this, a 'tree' view :
![image](https://user-images.githubusercontent.com/76894615/188772109-651bea9f-db23-40e8-9c94-7fb4f3d666e6.png)
How can solve this problem?

**Comment by lambdalisue** [comment]
`<Return>` is mapping to `enter` action so your explanation is equal to what the mapping should does.
Probably, what you want is `open-or-expand` (or simply just `expand`) that is mapped from `l` in default.

Hit `?` on fern buffer to see other mappings.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Mappings may help you as well

**Comment by HCY-ASLEEP** [comment]
Thanks!
