### ISSUE TITLE
[FR] Is there any way to leave to the parent node, but with the current node focused?

### ISSUE THREAD

**Issue by gou4shi1** [lambdalisue/fern.vim#450]
Thanks for any reply :)

**Comment by lambdalisue** [comment]
Well, I think it already does...

https://user-images.githubusercontent.com/546312/196222367-4124bf75-96e5-4e73-a7d6-c4279d29e544.mp4

**Comment by gou4shi1** [comment]
LOL, it does work now. Maybe sometimes it just has a little delay: jump to the first line firstly, then jump to the previous directory.

**Comment by gou4shi1** [comment]
It seems that `:Fern %:h -reveal=%` doesn't work like this.
I want it can open on the parent dir, focus on the current buffer.

**Comment by lambdalisue** [comment]
> It seems that :Fern %:h -reveal=% doesn't work like this.

Reproduced. Could you create a new issue as a bug report?
