### ISSUE TITLE
[feature] <Plug>(fern-action-zoom:half-toggle) <Plug>(fern-action-zoom:full-toggle)

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/fern.vim#451]
`<Plug>(fern-action-zoom:XXX-toggle)` is `<Plug>(fern-action-zoom:XXX)` or `<Plug>(fern-action-zoom:reset)`.

Thanks!

**Comment by lambdalisue** [comment]
I don't get what you mean

**Comment by Freed-Wu** [comment]
> `<Plug>(fern-action-zoom:XXX-toggle)` is `<Plug>(fern-action-zoom:XXX)` or `<Plug>(fern-action-zoom:reset)`.

Sorry, I mean:

![Screenshot from 2022-10-19 14-11-13](https://user-images.githubusercontent.com/32936898/196610799-618b044c-b2f2-44dc-9055-244297f9205d.png)
Now press `<plug>(fern-action-zoom:half-toggle)` equal to `<plug>(fern-action-zoom:half)`

![Screenshot from 2022-10-19 14-11-07](https://user-images.githubusercontent.com/32936898/196610809-c2e90d36-1a36-455d-9938-da85e315f010.png)
Now press `<plug>(fern-action-zoom:half-toggle)` equal to `<plug>(fern-action-zoom:reset)`

Maybe should be named `<plug>(fern-action-zoom:half-or-reset)`?

A simple method is just set a `b:half` and if `b:half == 1` `<plug>(fern-action-zoom:half-or-reset)` is `<plug>(fern-action-zoom:reset)` and `let b:half = 0`. Else `<plug>(fern-action-zoom:half-or-reset)` is `<plug>(fern-action-zoom:half)` and `let b:half = 0`. Or detect the window width to choose different behavior.

**Comment by lambdalisue** [comment]
Got it but I think it's easy to implement it by using `<expr>` like

```vim
nnoremap <buffer><expr> winwidth(0) > 10 ? "\<Plug>(fern-action-zoom:reset)" : "\<Plug>(fern-action-zoom:half)"
```

**Comment by Freed-Wu** [comment]
Thanks! :heart:
