### ISSUE TITLE
Change height of buffer when tiled vertically

### ISSUE THREAD

**Issue by cickes** [lambdalisue/fern.vim#454]
Thank you for your work on this.  It is greatly valued.

Is there a way to change the height of a buffer when tiled vertically?  In drawer mode, opening 2 buffers has them stacked vertically, each taking up 50%.  I'd like the top buffer to take up 80% and bottom to take up 20%, for example.

Even more specific, I would like this to happen only when executing a specific command.  An example here would be using [vim-flutter](https://github.com/thosakwe/vim-flutter).

`:FlutterRun` would open in the buffer window on the bottom, using 20% of the vertical screen, for example.

**Comment by lambdalisue** [comment]
You can use Vim's native `:resize` command I guess. Note that there are some issue on drawer mode with 2 buffers #452
