### ISSUE TITLE
Failed to open on the parent directory and focus on the current buffer.

### ISSUE THREAD

**Issue by gou4shi1** [lambdalisue/fern.vim#456]
see https://github.com/lambdalisue/fern.vim/issues/450#issuecomment-1296967177

**Comment by lambdalisue** [comment]
Oops. I'm sorry. This is a feature and you need to use `:Fern %:h -reveal=%:p` instead because `-reveal` requires an absolute path or a relative path from the tree root and `%` is a relative path from the current dir.

**Comment by gou4shi1** [comment]
Thanks, it works!
