### ISSUE TITLE
New fern renderer for nvim-web-devicons

### ISSUE THREAD

**Issue by TheLeoP** [lambdalisue/fern.vim#458]
I saw some closed issues about the lack of a renderer for fern that leverages nvim-web-devicons and, since it was a minor change, I created such renderer using 99% of the code of the deprecated [fern-renderer-devicons](https://github.com/lambdalisue/fern-renderer-devicons.vim), the repo of the new renderer is [fern-renderer-web-devicons.nvim](https://github.com/TheLeoP/fern-renderer-web-devicons.nvim).

I didn't know if it was ok for me to comment on those closed issues so I instead created this new one, I'm sorry if that isn't ok either.

**Comment by lambdalisue** [comment]
You can add it to https://github.com/lambdalisue/fern.vim/wiki/Plugins and/or use add `fern-vim-plugin` topic https://github.com/topics/fern-vim-plugin

**Comment by TheLeoP** [comment]
Done. Thanks :3
