### ISSUE TITLE
Unable to move a file without a specific fern error with getcurpos

### ISSUE THREAD

**Issue by nickjj** [lambdalisue/fern.vim#459]
I don't know when this started to happen because I only update plugins once in a while but I can say about 4-5 months ago this wasn't an issue. My environment hasn't changed, this is with Vim 8.1 running within WSL 2. I've been using the same fern configuration as I had for years.

When I select a file within fern and try to move it:

- It prompts me to input the source and destination within Vim's command window where everything is filled out already and I'm expected to provide the new destination path (this is normal)
- I type the new file name and hit enter (this is normal)
- It throws the error below (this is unexpected):

```
Error detected while processing function <lambda>961[1]..<SNR>204_show:
line   33:
E118: Too many arguments for function: getcurpos
Press ENTER or type command to continue
1 items are moved
Press ENTER or type command to continue
```

Any thoughts on where to go from here?

**Comment by lambdalisue** [comment]
It seems this line cause that issue https://github.com/lambdalisue/fern.vim/blob/main/autoload/fern/internal/drawer/hover_popup.vim#L66-L66

I need to find which Vim version add an optional argument to the `getcurpos`. If that is added after Vim 8.1.2269, I'll label it as a bug.

**Comment by lambdalisue** [comment]
https://github.com/vim/vim/commit/99ca9c4868bb1669706b9e3de9a9218bd11cc459

Found it. So it was introduced from 8.2.1727 that is not supported version of fern so it's a feature.

**Comment by nickjj** [comment]
Wow nice detective work. By the way I am using Vim 8.1.2269. I'm surprised they made a breaking change in a patch release.

**Comment by lambdalisue** [comment]
@nickjj Could you try #460?
