### ISSUE TITLE
Is there some way to open all the selected files?

### ISSUE THREAD

**Issue by lourenci** [lambdalisue/fern.vim#46]
Hi, thanks for the plugin. I've been finding a good alternative for the NERDTree and I think I have found it. :)

Is there some way to open all the selected nodes? I don't find anything in the readme neither in the `?`.

**Comment by lambdalisue** [comment]
Unfortunately no. Currently all "open" related actions are applied to a cursor node. But I'm not sure if it's worthwhile because Vim would messed-up. Could you tell me the situation you've met so that I can imagine the worth of that action.

**Comment by lourenci** [comment]
Often, I've a tree like that:
```
- Component/
  - index.js
  - reducers.js
  - actions.js
```
Work on in the `Component` probably means to work on its reducers/actions too. It'd be nice if I could open all the 3 buffers.

**Comment by lourenci** [comment]
The fern could activate the first file selected and open the others. Just like when I open my vim in this way: `nvim index.js reducers.js actions.js`.

**Comment by lambdalisue** [comment]
Hum... I'm not sure but could you try https://github.com/lambdalisue/fern.vim/pull/48

**Comment by lambdalisue** [comment]
Merged
