### ISSUE TITLE
[Feature request] New 'FernLeadingText' highlight group

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern.vim#461]
Hello @lambdalisue,

I have been experimenting with Fern visual style via these setting:

```viml
let g:fern#renderer#default#leading = '▏ '
let g:fern#renderer#default#leaf_symbol = '*  '
```

However, I notice the highlighting does not look good as seen in this screenshot:

![Fern_1](https://user-images.githubusercontent.com/11382509/208347480-34631182-0c21-4c54-9653-f5779eadf973.png)

I want the `leaf_symbol` (currently `*`) styled in blue and `collapsed_symbol` / `expanded_symbol` and `leading` (indent character) in dark grey.

Currently there are two main highlight groups effecting this area: `FernBranchSymbol` and `FernLeafSymbol`. The leading text inherits its style from both of these highlight groups depending if the current line contains leaves or nodes. So the leading (indent) text sometimes is blue, other times grey. Which looks bad.

For consistency, I believe the `leading` text should always be styled with the same color; hence the request for a new highlight group `FernLeadingText`. An alternative would be to always style `leading` with `FernBranchSymbol` highlighting. That would also solve my issue.

Best regards.

**Comment by bluz71** [comment]
Note, in the above example:

- `FernBranchSymbol` is set to dark grey.
- `FernLeafSymbol` is set to blue.

**Comment by bluz71** [comment]
The code in question is in `autoload/fern/renderer/default.vim` (from line 40).

I spent some time there, but in reality I don't understand how that code works, so I will be unable to assist here. I suspect behaviour will stay as is I suppose.

**Comment by brandon1024** [comment]
I've got a fix for this. I'll open a pull request over the weekend :+1: 

![image](https://user-images.githubusercontent.com/22732449/215102611-e5c103fc-7228-432a-a26f-9eac75341de7.png)

**Comment by bluz71** [comment]
Wonderful. That look perfect. Very much looking forward to the PR.

**Comment by bluz71** [comment]
Thank you @brandon1024 and @lambdalisue, this is a very nice update to fern.vim.

I have updated my themes [moonfly](https://github.com/bluz71/vim-moonfly-colors) and [nightfly](https://github.com/bluz71/vim-nightfly-colors) with the new highlight groups & behaviour.

Cheers.

**Comment by lambdalisue** [comment]
Wow. I didn't know that and I really like nightfly theme thanks 🎉
