### ISSUE TITLE
Is there a way to automatically redraw fern when a buffer is written?

### ISSUE THREAD

**Issue by jclsn** [lambdalisue/fern.vim#466]
Well the title says it all. I guess this is not possible, is it? Instead of pressin <C-L>, I would like to automatically redraw when a file is saved.

**Comment by lambdalisue** [comment]
Just invoke Vim's native `edit` command through `FernDo` command on appropriate autocmd.

**Comment by jclsn** [comment]
Can you give more details?

**Comment by lambdalisue** [comment]
See `:help autocmd-nested`

**Comment by jclsn** [comment]
Yes, this works. Thank you

```
autocmd BufWritePost *  ++nested :FernDo  e! -drawer
```
