### ISSUE TITLE
When opening a file, auto-hide or auto-defocus fern

### ISSUE THREAD

**Issue by ydzhou** [lambdalisue/fern.vim#467]
Hi

Do we have the configuration to auto hide fern if I open a file?

Also when I open a file, can we re-focus to the file we opened, instead of staying in the fern? So if I click one file in the fern, the active buffer will set to my newly opened file automatically.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/wiki/Tips

**Comment by ydzhou** [comment]
Hi, looks like the `fern-close-drawer` is not closing the fern when I do `tab open`. Do you have any thought?

```
nnoremap <Plug>(fern-close-drawer) :<C-u>FernDo close -drawer -stay<CR>
nmap <buffer> t <Plug>(fern-action-open:tabedit) <Plug>(fern-close-drawer)
```

**Comment by lambdalisue** [comment]
Unfortunately, `FernDo` only works on the current tabpage I think. Please create a new issue as a feature request if you need that feature on `FernDo`

**Comment by ydzhou** [comment]
Sure. Filed a new issue. Will close this one.
