### ISSUE TITLE
Is it possible to search files by their names?

### ISSUE THREAD

**Issue by your-diary** [lambdalisue/fern.vim#479]
By `grep` action, you can search files by regex, but is it possible to search by their names [like in VSCode](https://stackoverflow.com/a/71060133/8776746)?

**Comment by lambdalisue** [comment]
https://github.com/MeF0504/fern-mapping-search-ctrlp.vim
https://github.com/LumaKernel/fern-mapping-fzf.vim
https://github.com/KosukeMizuno/ctrlp-fern-action.vim

Not sure what you want but aboves may helps you?

**Comment by your-diary** [comment]
@lambdalisue 
Thank you This is exactly what I wanted.
