### ISSUE TITLE
Remote authentication required but no callback set

### ISSUE THREAD

**Issue by EricEWeir** [lambdalisue/fern.vim#487]
Non-coding vim user here. I have installed fern.vim and begun to explore its usage. I attempted to install the fern-hijack-vim plugin but got the text I used as title of this post as an error message. I have no idea what it means or what I am to do.

When I first tried to install fern a few weeks ago I got the same message. Today it went through without a hitch.

**Comment by EricEWeir** [comment]
Again, non-coding non-techie. Searching about this message, it seems some type of credential is being requested which is normally, or was not previously, required. This is a matter way over my head. Assistance desperately requested.

Alternatively, is there another way to install the plugin?

**Comment by lambdalisue** [comment]
I see, it appears that the issue you're encountering is not related to Fern itself, as Fern does not produce such messages or have that feature. It may be a problem with the installation or configuration of the plugin manager you are using. I would recommend reaching out to the author of the plugin manager for assistance in resolving this issue.

**Comment by EricEWeir** [comment]
I have updated my post about this issue on the github site of the plugin manager. I have since installed five plugins, including fern, without getting this message.

I have in the paste gotten the message when trying to install fern and nerdtree.
