### ISSUE TITLE
vim like mapping for zz?

### ISSUE THREAD

**Issue by pbwn** [lambdalisue/fern.vim#488]
(Thanks for making fern)

Is it possible to centre the view, equivalent to `zz` in vim. I find myself at the bottom of the file tree and doing `ctrl-d ctrl-u` to achieve something like `zz`. I can see on the tips page that you can map some keys using `s:init_fern()` but when I attempt to map eg `C-z` to `<C-d><C-u>` in my vimrc it doesn't work (i don't know what i'm doing). Has anyone created a mapping like this?

**Comment by lambdalisue** [comment]
![CleanShot 2023-10-17 at 01 04 18](https://github.com/lambdalisue/fern.vim/assets/546312/a80c6d5e-b6ef-4a31-9dd6-cbc02ed67f7d)

maybe because of above? just unmap works i guess

```vim
unmap <buffer> z
```

**Comment by brandon1024** [comment]
I use `zz` quite a bit too, and every once in a while I accidentally do `zz` in the fern window and it catches me off guard.

@lambdalisue would you be open to dropping the `z` mapping in fern?

**Comment by lambdalisue** [comment]
Well, it's just a default mapping so I don't think we have to change it.

**Comment by brandon1024** [comment]
Ahh, @pbwn you can get `zz` by disabling the default mappings explicitly:

```vim
let g:fern#disable_default_mappings = 1
```

No fern changes needed :-)

**Comment by pbwn** [comment]
thanks, but then nothing works, ie i use a lot of the usual mappings such as l to open file. If i unmap as someone suggests above with `unmap <buffer> z` then how would i set the zz mapping i want? As i say above, i tried using `s:init_fern()` but it didn't work, and i don't really know what i'm doing

**Comment by brandon1024** [comment]
@pbwn have you had a chance to try the snippet I posted above? If it works for you, we can wrap up this issue :-)

**Comment by pbwn** [comment]
thanks
re "I'm not sure where you're getting s:init_fern() to be honest.", i say at the top "I can see on the tips page that you can map some keys using s:init_fern()"

re "I wager your unmap doesn't work because it's not run in the context of the fern buffer.", i think you're right, i don't know how to define the mapping to be used in fern, i'm way too busy to give it any thought and put it on the back burner. You could wrap up this issue, no idea when i'll ever get to it ... i think i tried it and it didn't work, but i can't remember
