### ISSUE TITLE
How to open multiple files

### ISSUE THREAD

**Issue by tracyone** [lambdalisue/fern.vim#490]
I don't see any doc that talk about visual selection .

Like toggle_select_visual function in defx plugin

https://github.com/Shougo/defx.nvim/blob/master/doc/defx.txt#L541

**Comment by lambdalisue** [comment]
In short, use `-` to toggle mark. Hit `?` or execute `help` action on fern.vim to see other options.

**Comment by tracyone** [comment]
OK
