### ISSUE TITLE
Change action help mapping from ? to g?

### ISSUE THREAD

**Issue by lourenci** [lambdalisue/fern.vim#51]
I can't perform a backward search because the plugin show the actions help. Is there some way to change that behavior?

`vim-fugitive` uses the `g?` to avoid this conflict. I think it'd be a good alternative.

Thanks.

**Comment by lambdalisue** [comment]
You are totally correct. fern.vim overwrite `?` and it's better to NOT overwrite Vim's builtin mappings. But I'm not really sure if people rely on backward search...

Give me time to think about the default mappings for that.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/commit/bb634747cd1fa67a2ae2192aece8ee44d1593624

Now you can disable that mapping by defining alternative mapping like
```vim
nmap g? <Plug>(fern-action-help)
```
Note that this feature exists only for `?`, `.`, `a` while these mappings are critical in fern.
