### ISSUE TITLE
List of possible actions with tab?

### ISSUE THREAD

**Issue by lourenci** [lambdalisue/fern.vim#52]
Hi, I have another suggestion to do. Sorry about that, but I'm very eager about this plugin.

In `coc.nvim`, when I can perform actions under some item, I can press the tab on it and a list of actions is showing in the buffer.

![image](https://user-images.githubusercontent.com/2339362/73607840-29fdcb00-459a-11ea-8f60-41204878d591.png)

What do you think about that? This prevents the user to keep track of all the shortcuts the plugin has, besides to show him new options easily without the need to check the help or the readme.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim#actions

> To execute actions, hit a on a fern buffer and input an action to perform. To see all actions available, hit ? or execute help action then all available actions will be listed.

**Comment by lambdalisue** [comment]
Ah, prob. you missed that `<tab>` completion is enabled on the action prompt 👍
