### ISSUE TITLE
Wrong relative path when opening a file with fern

### ISSUE THREAD

**Issue by lourenci** [lambdalisue/fern.vim#74]
`fern.vim` is not opening a file relative to the pwd dir.

A file opened with `fern`:
![image](https://user-images.githubusercontent.com/2339362/74033615-513b0a80-4995-11ea-9230-79d3cad5f39a.png)

A file opened with `fzf`:
![image](https://user-images.githubusercontent.com/2339362/74033649-6748cb00-4995-11ea-9d5e-f6e2063ff50e.png)

Both were opened in the same vim session.

**Comment by lambdalisue** [comment]
Ah... I don't get the point. So fern.vim opens a wrong file?

**Comment by lourenci** [comment]
Sorry, I forgot to type some essential information.

I think `fern` is not considering the `pwd` path. The last line of both prints is the `pwd` path. When I open a file through the `fern` (the former print), it is opening a file relative to the `~/` path.

**Comment by lambdalisue** [comment]
Got it but I don't think it's an issue. Do you have any actual problems with this behavior?

**Comment by lourenci** [comment]
Yes, not a big deal tough: when I need to copy the relative path to the clipboard or when I open a deep file in my project tree I can't see the entire file path on the `statusline` because it's cluttered with the `~/` path.

**Comment by lambdalisue** [comment]
I think that's Vim's display issue while `~/hogehoge/foo/bar.txt` and `./bar.txt` is exactly the same if you are in `~/hogehoge/foo`. For example, the statusline is different between following two cases

1. `:e ./bar.txt` then `:e ~/hogehoge/foo/bar.txt` shows `bar.txt` in statusline
2. `:e ~/hogehoge/foo/bar.txt` then `:e ./bar.txt` shows `~/hogehoge/foo/bar.txt` in statusline
