### ISSUE TITLE
Is there some way to wipe out the fern buffer?

### ISSUE THREAD

**Issue by lourenci** [lambdalisue/fern.vim#79]
When I choose some file and in that file I press to alternate <c-^>`, the fern buffer takes place.

Is this some way to change that behavior and after I choose some file in the `fern`, the fern buffer wipe out itself, so I can't alternate to the previous file before I had opened the `fern`?

**Comment by lambdalisue** [comment]
I'll make it configurable. Thanks for the suggestion 👍

**Comment by lambdalisue** [comment]
Prob #80 solves your problem 👍

**Comment by lourenci** [comment]
Thanks for that.

Just a warning: the master branch is broken (I'm using macOS). When I open fern (`:Fern .`), the buffer shows up empty. I've changed my update channel to the release tags.

**Comment by lambdalisue** [comment]
> Just a warning: the master branch is broken (I'm using macOS). When I open fern (:Fern .), the buffer shows up empty. I've changed my update channel to the release tags.

I'm using macOS as well but fern works OK both in Vim and Neovim. Check your cache or whatever.
