### ISSUE TITLE
Weird buffer behavior with open:edit

### ISSUE THREAD

**Issue by wallace11** [lambdalisue/fern.vim#82]
Please consider the following scenario:
```
:e a.file
:e b.file
:bd
```
The result would be `a.file` open.

Doing the same with `:Fern -drawer`:
```
open:edit a.file
open:edit b.file
:bd
```
The result: vim quits (unless any changes were done to the files).

Would be nice to have opened buffers to act like regular ones (I don't really understand how this is possible to have another type of buffer, but maybe I'm missing something here... Didn't look at the source of fern)

**Edit:** Apparently it only happens with `-drawer`. Still investigating...

**Comment by lambdalisue** [comment]
Use `-keep` to avoid quitting like

```
:Fern . -drawer -keep
```

Then you'll get **an empty buffer** which is **proper** behavior while `:bd` close the buffer if there are extra buffers. So you need to compare behavior with the following instead.

```
:new
:e a.file
:e b.file
:bd
```

Thus, you said "Weird" but the behavior is correct.

**Comment by wallace11** [comment]
Hi, I was out of town for the weekend, hence the late reply.

I was actually playing with `-keep` and the other `open:` options but never found something that matches a "normal workflow" (at least "normal" in my terms...).

Maybe I'm missing something, and maybe this not exactly part of the scope of this issue, but is there a way to achieve a workflow where you open a bunch of files using Fern and individually closing them, automatically moving to the next buffer, without going through an empty buffer first?

I've managed to avoid using tree plugins (Nerdtree, etc.) up until now, using only `:e` and `:FZF`, but fern looked so well-made so I thought I'd give it a try, so maybe I lack the proper knowledge of how to work with tree plugins. Would you be kind enough to explain the benefits of this design choice?  This could serve as an example question for people like me, who their entire vim world consists of "classic" buffers only...

**Comment by lambdalisue** [comment]
> I was actually playing with -keep and the other open: options but never found something that matches a "normal workflow" (at least "normal" in my terms...).

If you are using `-drawer` option, there are TWO buffers. So the behavior you've explained first was not correct for comparison (there is ONE buffer). I think the term "normal" means it follows Vim's native behavior and I think fern follows Vim's manner in the case.

> Maybe I'm missing something, and maybe this not exactly part of the scope of this issue, but is there a way to achieve a workflow where you open a bunch of files using Fern and individually closing them, automatically moving to the next buffer, without going through an empty buffer first?

Well, it quite depends. Maybe you can

1. Mark target nodes (`<C-j>/<C-k>/-`)
2. Use `open:tabedit` to open files in individual tab pages
3. Goto the last tab page (`:tabl`)
4. Do something and close tabs

Or whatever. Note that I don't open a bunch of files so the above might not be useful enough.
It's definitely off the topics of this issue so please make a new issue if you are not satisfied with my answer and want to continue.

> I've managed to avoid using tree plugins (Nerdtree, etc.) up until now, using only :e and :FZF, but fern looked so well-made so I thought I'd give it a try, so maybe I lack the proper knowledge of how to work with tree plugins. Would you be kind enough to explain the benefits of this design choice? This could serve as an example question for people like me, who their entire vim world consists of "classic" buffers only...

Thanks. But I'm not sure what do you want to know here... Which design choice you are talking about? Things not listed in [docs](https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L29-L87)?
It's definitely off the topics of this issue so please make a new issue if you are not satisfied with my answer and want to continue.
