### ISSUE TITLE
Fern is not showing any files

### ISSUE THREAD

**Issue by lourenci** [lambdalisue/fern.vim#83]
Hi. Thanks for the plugin.

When I open fern with the command `:Fern .` no files show up. It's not happening with the last tag release or with the `:Fern . -drawer` command. I've already removed the plugin and installed it again to keep the cache problem away.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2339362/74589433-16178780-4fe4-11ea-9ea9-0abad25c1b7b.gif)

**Comment by lambdalisue** [comment]
It's really strange. At least for now, nobody except you hit that situation. To clarify the issue, could you fill the following?

1. Which OS and version you use
2. Which Vim/Neovim version you use

And could you try `:Fern .` with the following minimal vimrc?

```vim
" How to use this vimrc.min
" vim -u ~/vimrc.min
" nvim -u ~/vimrc.min
if has('vim_starting')
  set nocompatible
endif

" Rewrite it to path/to/your/fern.vim
set runtimepath+=~/.ghq/github.com/lambdalisue/fern.vim

filetype plugin indent on
syntax on
```

**Comment by phongnh** [comment]
Same problem here. The issue happened on Ubuntu 18.04 and VIM 8.0 patch 1-1453 and NeoVim v0.3.8

Please check here: https://asciinema.org/a/OKHiGWObbGop59dTuxl2TFIPP

Thanks.

**Comment by lourenci** [comment]
Your minimal config worked for me. I tried to verify some plugins conflict, then as soon as I disabled the [vim-projectionist](https://github.com/tpope/vim-projectionist) the `fern` came back to work.

I'm using macOS 10.15.3 and neovim v0.5.0-ead61e5a5.

**Comment by lambdalisue** [comment]
> Your minimal config worked for me

Then it's not an issue of fern. Please report it to that plugin.

P.S.

I'm not sure and I'm not going to investigate it more but `let g:projectionist_ignore_fern = 1` might solves your problem.

https://github.com/tpope/vim-projectionist/blob/master/plugin/projectionist.vim#L82

**Comment by lambdalisue** [comment]
@phongnh 

Please create a new issue if the reason is not vim-projectionist. Note that please try it with a minimal vimrc above.

**Comment by phongnh** [comment]
> @phongnh
> 
> Please create a new issue if the reason is not vim-projectionist. Note that please try it with a minimal vimrc above.

Tried to run minimal vimrc on vim 8.1 and vim 8.2 and neovim 0.4.2, the problem has gone.
