### ISSUE TITLE
Fern reveal does not work

### ISSUE THREAD

**Issue by phongnh** [lambdalisue/fern.vim#86]
I'm at my home dir `~`, editing file `~/fern/info.txt`

Tried to use one of the following commands, none of them works

```
Fern . -reveal=%
Fern %:h -reveal=%
Fern %:p:h -reveal=%
```

I got this error `fern: {base} ("Users/phong/fern") must be an absolute path`.

I'm using vim 8.2 and latest fern.vim, please check details here:     https://asciinema.org/a/9oVxreInZhp3MnsCyvD6nOsVa

**Comment by lambdalisue** [comment]
Oops. It's regression. Use v0.13.0 for now.

**Comment by lambdalisue** [comment]
Now, this should be fixed and v0.14.1 has released.

**Comment by phongnh** [comment]
@lambdalisue Thanks for quick fix.
