### ISSUE TITLE
New buffers open in the drawer if it has focus

### ISSUE THREAD

**Issue by Shatur95** [lambdalisue/fern.vim#89]
**Steps to reproduce:**
```vim
:Fern . -drawer
:e anyfile
```

**Actual behavior:**
`anyfile` opened in Fern drawer split.

**Expected behavior:**
`anyfile` opened in other split

**Screenshot:**
![изображение](https://user-images.githubusercontent.com/22453358/76305647-30384300-62ce-11ea-9cbf-0bd6ea5c9b7b.png)

**Comment by lambdalisue** [comment]
That's definitely expected behavior. The `:e` is Vim's command which opens a specified file **on the current buffer**

**Comment by lambdalisue** [comment]
I've no idea why you need to execute `:e` on the fern buffer but if you need to do something like that, try `-stay` which does NOT move focus on the fern buffer like

```
:Fern . -drawer -stay
:e anyfile
```

**Comment by Shatur95** [comment]
`:e` is just as an example. When I have focus on Fern, and I execute any other command that opens the buffer (`fzf`, for example), it opens buffer in fern split. So, to open new buffer from fuzzy finder and If I have Fern focused for some reason I always need to remember to change focus because there is no case to open new buffer in drawer split. I understand that Fern is just a split window, but as for me it would be convenient to prevent opening new windows with `-drawer` option.

**Comment by lambdalisue** [comment]
Got it. But I'm sure that it's bad idea to hook where to open a buffer invoked by **non fern commands**. Most of people would be surprised by such behavior.

I guess what you need is a feature on other commands (e.g. `fzf`) which opens a buffer more intelligent way. For example, I think you will be happy if **fzf avoids** opening a buffer on small windows, such as fern's drawer (actually this is what fern does internally to select suitable window to open a new buffer.)

**Comment by Shatur95** [comment]
Yes, you're right, it would be better to add such an option to `fzf`.

**Comment by Shatur95** [comment]
Hmm ... I noticed that with Fugitive the same problem. And I think this is not limited to two plugins :(
Maybe it would be nice to have an option that will prevent window opening.

**Comment by lambdalisue** [comment]
Well, prevent then... what?

**Comment by Shatur95** [comment]
Sorry for my English, I meant that maybe it's still worth having such an option in Fern (to prevent opening new buffers in Fern drawer, just open it in adjacent), because there are many plugins that can open new buffers.
I understand that you most likely will not agree, I will try to configure this behavior separately for my config.
