### ISSUE TITLE
Change parent node color

### ISSUE THREAD

**Issue by jericdeleon** [lambdalisue/fern.vim#93]
First of all, thanks for this awesome plugin! Been using it to great effect.

Just one bit: I wish to change parent node (folder) colors (specifically, I'm aiming to switch normal / marked folder colors, as shown here: https://github.com/lambdalisue/fern-renderer-devicons.vim). Is there an easy way to do that?

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/fern.vim/blob/master/autoload/fern/renderer/default.vim#L61-L64

I'm not sure if I understand what you meant but try defining a custom highlight of `FernBranch`.

**Comment by jericdeleon** [comment]
This is sufficient, thanks!
